// src/components/modules/layout/designBoard/index.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2024-04-10 23:02:46
 * @Description: 主画布
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-12-28 14:12:33
-->
<template>
  <div id="main">
    <div id="page-design" ref="page_design" :style="{ paddingTop: dPaddingTop + 'px', minWidth:  (dPage.width * dZoom) / 100 + (padding ?? dPresetPadding) * 2 + 'px' }">
      <div
        id="out-page"
        class="out-page"
        :style="{
          padding: padding ?? dPresetPadding + 'px',
          width: (dPage.width * dZoom) / 100 + (padding ?? dPresetPadding) * 2 + 'px',
          height: (dPage.height * dZoom) / 100 + (padding ?? dPresetPadding) * 2 + 'px',
          opacity: 1 - (dZoom < 100 ? dPage.tag : 0),
        }"
      >
        <slot />
        <resize-page v-if="needTools" :width="(dPage.width * dZoom) / 100" :height="(dPage.height * dZoom) / 100" />
        <watermark :customStyle="{ height: (dPage.height * dZoom) / 100 + 'px' }">
          <div
            :id="props.pageDesignCanvasId"
            class="design-canvas"
            :data-type="dPage.type"
            :data-uuid="dPage.uuid"
            :style="{
              width: dPage.width + 'px',
              height: dPage.height + 'px',
              transform: 'scale(' + dZoom / 100 + ')',
              transformOrigin: (dZoom >= 100 ? 'center' : 'left') + ' top',
              backgroundColor: dPage.backgroundGradient ? undefined : dPage.backgroundColor,
              backgroundImage: dPage.backgroundImage ? `url(${dPage?.backgroundImage})` : dPage.backgroundGradient || undefined,
              backgroundSize: dPage.backgroundTransform?.x ? 'auto' : 'cover',
              backgroundPositionX: (dPage.backgroundTransform?.x || 0) + 'px',
              backgroundPositionY: (dPage.backgroundTransform?.y || 0) + 'px',
              opacity: dPage.opacity + (dZoom < 100 ? dPage.tag : 0),
            }"
            @mousemove="dropOver($event)"
            @drop="drop($event)"
            @mouseup="drop($event)"
          >
            <!-- <grid-size /> -->
            <component :is="layer.type" v-for="layer in getlayers()" :id="layer.uuid" :key="layer.uuid" :class="[{ 'layer':needTools }, { 'layer-hover': layer.uuid === dHoverUuid || dActiveElement?.parent === layer.uuid, 'layer-no-hover': dActiveElement?.uuid === layer.uuid }]" :data-title="layer.type" :params="layer" :parent="dPage" :data-type="layer.type" :data-uuid="layer.uuid">
              <template v-if="layer.isContainer">
                <!-- :class="{
                  layer: true,
                  'layer-active': getIsActive(widget.uuid),
                  'layer-no-hover': dActiveElement.uuid !== widget.parent && dActiveElement.parent !== widget.parent,
                  'layer-hover': widget.uuid === dHoverUuid,
                }" -->
                <component :is="widget.type" v-for="widget in getChilds(layer.uuid)" :key="widget.uuid" child :class="[{ 'layer':needTools }, { 'layer-no-hover': dActiveElement?.uuid !== widget.parent && dActiveElement?.parent !== widget.parent }]" :data-title="widget.type" :params="widget" :parent="layer" :data-type="widget.type" :data-uuid="widget.uuid" />
              </template>
            </component>

            <!-- What Moveable snaps to when a ruler guide is in the way -->
            <snap-guides v-if="needTools" />

            <!-- <ref-line v-if="dSelectWidgets.length === 0" /> -->
          </div>
        </watermark>
      </div>
    </div>
    <slot name="bottom" />
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted } from 'vue'
import { getTarget } from '@/common/methods/target'
import setWidgetData from '@/common/methods/DesignFeatures/setWidgetData'
import PointImg from '@/utils/plugins/pointImg'
import getComponentsData from '@/common/methods/DesignFeatures/setComponents'
import { debounce } from 'throttle-debounce'
import { move, moveInit } from '@/mixins/move'
import { useCanvasStore, useControlStore, useWidgetStore } from '@/store'
import { storeToRefs } from 'pinia'
import { TPageState } from '@/store/design/canvas/d'
import resizePage from './comps/resize.vue'
import watermark from './comps/pageWatermark.vue'
import snapGuides from './comps/snapGuides.vue'
import { TdWidgetData } from '@/store/design/widget'
import { useRoute } from 'vue-router'
const route = useRoute()

// 页面设计组件
type TProps = {
  pageDesignCanvasId: string
  /** 以下参数仅用于图片渲染html */
  padding?: number
  /** 用于生成渲染图片 */
  renderDPage?: TPageState
  renderDWdigets?: TdWidgetData[]
  zoom?: number
}

type TParentData = {
  width?: number
  height?: number
}

type TSetting = Partial<TPageState>

const controlStore = useControlStore()
const widgetStore = useWidgetStore()
const canvasStore = useCanvasStore()

const props = defineProps<TProps>()

const needTools = computed(() => route.name !== 'Draw' && route.name !== 'Html')
const { dPage: curDPage } = storeToRefs(useCanvasStore())
const { dZoom: curZoom, dPresetPadding, dPaddingTop, dScreen } = storeToRefs(canvasStore)
const { dDraging, showRotatable, dAltDown, dSpaceDown } = storeToRefs(controlStore)
const { dWidgets: curWidgets, dActiveElement, dSelectWidgets, dHoverUuid } = storeToRefs(widgetStore)

const dPage = computed(() => props.renderDPage ?? curDPage.value)
const dWidgets = computed(() => props.renderDWdigets ?? curWidgets.value)
const dZoom = computed(() => props.zoom ?? curZoom.value)

let _dropIn: string | null = ''
let _srcCache: string | null = ''

onMounted(() => {
  getScreen()
  const pageDesignEl = document.getElementById('page-design')
  if (!pageDesignEl) return
  pageDesignEl.addEventListener('mousedown', handleSelection, false)
  // pageDesignEl.addEventListener('mousemove', debounce(100, false, handleMouseMove), false)
  // 绑定空格事件
  const scrollContainer: any = document.querySelector('#main')
  const dragContainer: any = pageDesignEl
  dragContainer.onmousedown = (e: any) => {
    let mouseDownScrollPosition = {
      scrollLeft: scrollContainer.scrollLeft,
      scrollTop: scrollContainer.scrollTop,
    }
    let mouseDownPoint = {
      x: e.clientX,
      y: e.clientY,
    }
    dragContainer.onmousemove = (e: any) => {
      if (!dSpaceDown.value) return
      let dragMoveDiff = {
        x: mouseDownPoint.x - e.clientX,
        y: mouseDownPoint.y - e.clientY,
      }
      scrollContainer.scrollLeft = mouseDownScrollPosition.scrollLeft + dragMoveDiff.x
      scrollContainer.scrollTop = mouseDownScrollPosition.scrollTop + dragMoveDiff.y
    }
    document.onmouseup = (e) => {
      dragContainer.onmousemove = null
      document.onmouseup = null
    }
  }
})

// components: {lineGuides},
// mixins: [moveInit],
// ...mapActions(['updateScreen', 'selectWidget', 'deleteWidget', 'addWidget', 'addGroup']),

// getBackground(data) {
//   if (data.startsWith('http')) return `url(${data})`
//   if (data.startsWith('linear-gradient')) return data
// },

async function dropOver(e: MouseEvent) {
  if (!dActiveElement.value) return
  if (dActiveElement.value.editable || dActiveElement.value.lock) {
    return false
  }
  e.preventDefault()
  let { data, type } = widgetStore.selectItem
  if (!data) return
  if (type !== 'image') {
    return
  }
  if (!e || !e.target) return
  const eventTarget = e.target as HTMLElement
  const target = await getTarget(eventTarget)
  if (!target) return
  const uuid = target.getAttribute('data-uuid')

  widgetStore.setDropOver(uuid ?? '-1')
  // store.dispatch('setDropOver', uuid)

  const imgEl = target?.firstElementChild?.firstElementChild as HTMLImageElement
  if (eventTarget.getAttribute('putIn')) {
    _dropIn = uuid
    const imgUrl = data.value.thumb || data.value.url
    !_srcCache && (_srcCache = imgEl.src)
    imgEl.src = imgUrl
  } else {
    _srcCache && (imgEl.src = _srcCache)
    _srcCache = ''
    _dropIn = ''
  }
}

async function drop(e: MouseEvent) {
  if (!dDraging.value) {
    return
  }
  if (!e || !e.target) return
  const eventTarget = e.target as HTMLElement

  controlStore.setDraging(false)
  // store.commit('setDraging', false)

  const dropIn = _dropIn
  _dropIn = ''

  widgetStore.setDropOver('-1')
  // store.dispatch('setDropOver', '-1')

  // store.commit('setShowMoveable', false) // Clear the previous selection
  controlStore.setShowMoveable(false) // Clear the previous selection

  let lost = eventTarget.className !== 'design-canvas' // className === 'design-canvas' , id: "page-design-canvas"
  // e.stopPropagation()
  e.preventDefault()
  let { data: item, type } = JSON.parse(JSON.stringify(widgetStore.selectItem))
  // 清除临时数据
  widgetStore.setSelectItem({})
  // store.commit('selectItem', {})

  let setting: TSetting = {}
  if (!type) {
    return
  }
  // 处理数据
  setting = await setWidgetData(type, item, setting)
  // 绝对坐标
  const canvasEl = document.getElementById('page-design-canvas')
  if (!canvasEl) return
  const lostX = e.x - canvasEl.getBoundingClientRect().left
  const lostY = e.y - canvasEl.getBoundingClientRect().top
  // 放置组合
  if (type === 'group') {
    let parent: TParentData = {}
    const componentItem = await getComponentsData(item)
    // item = await getComponentsData(item)
    componentItem.forEach((element) => {
      if (element.type === 'w-group') {
        parent.width = element.width
        parent.height = element.height
      }
    })
    const half = {
      x: parent.width ? (parent.width * dZoom.value) / 100 / 2 : 0,
      y: parent.height ? (parent.height * dZoom.value) / 100 / 2 : 0,
    }
    componentItem.forEach((element) => {
      element.left += (lost ? lostX - half.x : e.layerX - half.x) * (100 / dZoom.value)
      element.top += (lost ? lostY - half.y : e.layerY - half.y) * (100 / dZoom.value)
    })
    widgetStore.addGroup(componentItem)
    // store.dispatch('addGroup', componentItem)
    // addGroup(item)
  }
  // 设置坐标
  const half = {
    x: setting.width ? (setting.width * dZoom.value) / 100 / 2 : 0,
    y: setting.height ? (setting.height * dZoom.value) / 100 / 2 : 0,
  }
  // const half = { x: (this.dDragInitData.offsetX * this.dZoom) / 100, y: (this.dDragInitData.offsetY * this.dZoom) / 100 }
  setting.left = (lost ? lostX - half.x : e.layerX - half.x) * (100 / dZoom.value)
  setting.top = (lost ? lostY - half.y : e.layerY - half.y) * (100 / dZoom.value)
  if (lost && type === 'image') {
    // 如果不从画布加入，且不是图片类型，则判断是否加入到svg中
    const target = await getTarget(eventTarget)
    if (!target) return
    const targetType = target.getAttribute('data-type')
    const uuid = target.getAttribute('data-uuid')
    if (targetType === 'w-mask') {
      // Container
      // store.commit('setShowMoveable', true) // Restore selection
      controlStore.setShowMoveable(true) // Restore selection

      const widget = dWidgets.value.find((item: { uuid: string }) => item.uuid === uuid)
      if (!widget) return
      widget.imgUrl = item.value.url
      // if (e.target.className.baseVal) {
      //   !widget.imgs && (widget.imgs = {})
      //   widget.imgs[`${e.target.className.baseVal}`] = item.value.url
      // }
    } else {
      if (dropIn) {
        const widget = dWidgets.value.find((item: { uuid: string }) => item.uuid == dropIn)
        if (!widget) return
        widget.imgUrl = item.value.url
        // store.commit('setShowMoveable', true) // Restore selection
        controlStore.setShowMoveable(true) // Restore selection
      } else {
        widgetStore.addWidget(setting as Required<TPageState>)
        // store.dispatch('addWidget', setting) // 正常加入面板
      }
    }
  } else if (type === 'bg') {
    console.log('Background image position')
  } else if (type !== 'group') {
    widgetStore.addWidget(setting as Required<TPageState>)
    // store.dispatch('addWidget', setting) // 正常加入面板
  }
  // 清除临时数据
  // this.$store.commit('selectItem', {})
}

function getScreen() {
  const pageDesignEl = document.getElementById('page-design')
  if (!pageDesignEl) return
  canvasStore.updateScreen({
    width: pageDesignEl.offsetWidth,
    height: pageDesignEl.offsetHeight,
  })
  // store.dispatch('updateScreen', {
  //   width: pageDesignEl.offsetWidth,
  //   height: pageDesignEl.offsetHeight,
  // })
}

async function handleMouseMove(e: MouseEvent) {
  if (!e || !e.target) return
  const imageTarget = e.target as HTMLImageElement
  const pImg = new PointImg(imageTarget)
  const { rgba } = pImg.getColorXY(e.offsetX, e.offsetY)
  if (rgba && rgba === 'rgba(0,0,0,0)') {
    console.log('Read the pixel colour: ', rgba)
    let target = await getTarget(imageTarget)
    if (!target) return
    target.style.pointerEvents = 'none'
    setTimeout(() => {
      if (!target) return
      target.style.pointerEvents = 'auto'
    }, 300)
  }
}

async function handleSelection(e: MouseEvent) {
  if (e.which === 3) {
    return
  }
  if (!e || !e.target) return
  let target = await getTarget(e.target as HTMLElement)
  if (!target) return
  let type = target.getAttribute('data-type')

  if (type) {
    let uuid = target.getAttribute('data-uuid')
    if (uuid !== '-1' && !dAltDown.value) {
      let widget = dWidgets.value.find((item: { uuid: string }) => item.uuid === uuid)
      if (!widget || !dActiveElement.value) return
      if (widget.parent !== '-1' && widget.parent !== dActiveElement.value.uuid && widget.parent !== dActiveElement.value.parent) {
        uuid = widget.parent || null
      }
    }

    // Set the selected element
    // this.$store.commit('setMoveable', false)
    if (showRotatable.value !== false) {
      widgetStore.selectWidget({
        uuid: uuid ?? ' -1',
      })
      // store.dispatch('selectWidget', {
      //   uuid: uuid,
      // })
    }

    if (uuid !== '-1') {
      moveInit.methods.initmovement(e) // 参见 mixins
    }
  } else {
    // Deselect元素
    widgetStore.selectWidget({
      uuid: '-1',
    })
    // store.dispatch('selectWidget', {
    //   uuid: '-1',
    // })
  }
}

function getlayers() {
  return dWidgets.value.filter((item) => item.parent === dPage.value.uuid)
}

function getChilds(uuid: string) {
  return dWidgets.value.filter((item) => item.parent === uuid)
}
// getIsActive(uuid) {
//   if (this.dSelectWidgets.length > 0) {
//     let widget = this.dSelectWidgets.find((item) => item.uuid === uuid)
//     if (widget) {
//       return true
//     }
//     return false
//   } else {
//     return uuid === this.dActiveElement.uuid
//   }
// },
</script>

<style lang="less" scoped>
#main {
  overflow: auto;
  position: relative;
}
#page-design {
  scrollbar-width: none;
  min-height: 100%;
  overflow: auto;
  position: relative;
  // width: 100%;
  .out-page {
    margin: 0 auto;
    // padding: 60px;
    position: relative;
    .design-canvas {
      // 解决拖拽残影问题
      outline: 1px solid transparent;
      // transition: all 0.3s;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      box-shadow: @shadow-page;
      margin: 0 auto;
      position: relative;
      // z-index: -9999;
      // overflow: hidden;
      // overflow: auto;
    }
    // .design-canvas ::-webkit-scrollbar {
    //   display: none; /* Chrome Safari */
    // }
  }
}
</style>

// react/src/components/modules/layout/designBoard/DesignBoard.tsx
import { memo, useEffect, useMemo, useRef, type ReactNode } from 'react'
import { useSnapshot } from 'valtio'
import { canvasState, controlState, widgetState } from '@/store/state'
import { updateScreen } from '@/store/canvas'
import { setShowMoveable, setDraging } from '@/store/control'
import { addGroup, addWidget } from '@/store/widget'
import { setDropOver, setSelectItem, selectWidget } from '@/store/widget'
import { getTarget } from '@/common/methods/target'
import setWidgetData from '@/common/methods/DesignFeatures/setWidgetData'
import getComponentsData from '@/common/methods/DesignFeatures/setComponents'
import { moveInit } from '@/mixins/move'
import { useEditorMode } from '@/common/hooks/useEditorMode'
import type { TdWidgetData, TPageState } from '@/store/types'
import { widgetComponents } from '../../widgets/registry'
import { cx } from '@/utils/dom'
import ResizePage from './comps/ResizePage'
import PageWatermark from './comps/PageWatermark'
import SnapGuides from './comps/SnapGuides'
import './designBoard.less'

type Props = {
  pageDesignCanvasId: string
  padding?: number
  renderDPage?: TPageState
  renderDWidgets?: TdWidgetData[]
  zoom?: number
  className?: string
  children?: ReactNode
  bottom?: ReactNode
}

const Layers = memo(function Layers({
  needTools,
  pageUuid,
  parentLeft,
  parentTop,
  widgets,
}: {
  needTools: boolean
  pageUuid: string
  parentLeft: number
  parentTop: number
  /** Supplied by the render-only screens, which draw a page they hold themselves. */
  widgets?: TdWidgetData[]
}) {
  const snap = useSnapshot(widgetState)
  const hoverUuid = snap.dHoverUuid
  const activeUuid = snap.dActiveElement?.uuid
  const activeParent = snap.dActiveElement?.parent

  const parent = useMemo(() => ({ left: parentLeft, top: parentTop, uuid: pageUuid }), [parentLeft, parentTop, pageUuid])

  const layers = useMemo(() => {
    if (widgets) return widgets.filter((item) => item.parent === pageUuid)
    const raw = widgetState.dWidgets
    const out: TdWidgetData[] = []
    for (let i = 0; i < raw.length; i++) {
      if (snap.dWidgets[i].parent === pageUuid) out.push(raw[i])
    }
    return out
  }, [snap.dWidgets, pageUuid, widgets])

  return (
    <>
      {layers.map((layer) => {
        const Comp = widgetComponents[layer.type]
        if (!Comp) return null
        return (
          <Comp
            key={layer.uuid}
            id={layer.uuid}
            params={layer}
            parent={parent}
            className={cx({ layer: needTools }, { 'layer-hover': layer.uuid === hoverUuid || activeParent === layer.uuid, 'layer-no-hover': activeUuid === layer.uuid })}
            data-title={layer.type}
            data-type={layer.type}
            data-uuid={layer.uuid}
          >
            {layer.isContainer ? (
              <Children parentLayer={layer} needTools={needTools} activeUuid={activeUuid} activeParent={activeParent} widgets={widgets} />
            ) : null}
          </Comp>
        )
      })}
    </>
  )
})

function Children({
  parentLayer,
  needTools,
  activeUuid,
  activeParent,
  widgets,
}: {
  parentLayer: TdWidgetData
  needTools: boolean
  activeUuid?: string
  activeParent?: string
  widgets?: TdWidgetData[]
}) {
  const snap = useSnapshot(widgetState)
  const childs = useMemo(() => {
    if (widgets) return widgets.filter((item) => item.parent === parentLayer.uuid)
    const raw = widgetState.dWidgets
    const out: TdWidgetData[] = []
    for (let i = 0; i < raw.length; i++) {
      if (snap.dWidgets[i].parent === parentLayer.uuid) out.push(raw[i])
    }
    return out
  }, [snap.dWidgets, parentLayer.uuid, widgets])

  return (
    <>
      {childs.map((widget) => {
        const Comp = widgetComponents[widget.type]
        if (!Comp) return null
        return (
          <Comp
            key={widget.uuid}
            id={widget.uuid}
            child
            params={widget}
            parent={parentLayer}
            className={cx({ layer: needTools }, { 'layer-no-hover': activeUuid !== widget.parent && activeParent !== widget.parent })}
            data-title={widget.type}
            data-type={widget.type}
            data-uuid={widget.uuid}
          />
        )
      })}
    </>
  )
}

export default function DesignBoard({
  pageDesignCanvasId,
  padding,
  renderDPage,
  renderDWidgets,
  zoom,
  className,
  children,
  bottom,
}: Props) {
  const mode = useEditorMode()
  const needTools = mode !== 'draw' && mode !== 'html'

  const canvas = useSnapshot(canvasState)
  const dPage = renderDPage ?? (canvas.dPage as TPageState)
  const dZoom = zoom ?? canvas.dZoom
  const { dPresetPadding, dPaddingTop } = canvas

  const dropIn = useRef<string | null>('')
  const srcCache = useRef<string | null>('')

  useEffect(() => {
    getScreen()
    const pageDesignEl = document.getElementById('page-design')
    if (!pageDesignEl) return
    pageDesignEl.addEventListener('mousedown', handleSelection, false)

    const scrollContainer = document.querySelector('#main') as HTMLElement
    const dragContainer = pageDesignEl as any
    dragContainer.onmousedown = (e: MouseEvent) => {
      const mouseDownScrollPosition = {
        scrollLeft: scrollContainer.scrollLeft,
        scrollTop: scrollContainer.scrollTop,
      }
      const mouseDownPoint = { x: e.clientX, y: e.clientY }
      dragContainer.onmousemove = (ev: MouseEvent) => {
        if (!controlState.dSpaceDown) return
        const dragMoveDiff = {
          x: mouseDownPoint.x - ev.clientX,
          y: mouseDownPoint.y - ev.clientY,
        }
        scrollContainer.scrollLeft = mouseDownScrollPosition.scrollLeft + dragMoveDiff.x
        scrollContainer.scrollTop = mouseDownScrollPosition.scrollTop + dragMoveDiff.y
      }
      document.onmouseup = () => {
        dragContainer.onmousemove = null
        document.onmouseup = null
      }
    }

    return () => {
      pageDesignEl.removeEventListener('mousedown', handleSelection, false)
      dragContainer.onmousedown = null
      dragContainer.onmousemove = null
    }
  }, [])

  function currentWidgets() {
    return renderDWidgets ?? widgetState.dWidgets
  }

  function currentZoom() {
    return zoom ?? canvasState.dZoom
  }

  async function dropOver(event: React.MouseEvent) {
    const e = event.nativeEvent
    const active = widgetState.dActiveElement
    if (!active) return
    if (active.editable || active.lock) {
      return false
    }
    e.preventDefault()
    const { data, type } = widgetState.selectItem
    if (!data) return
    if (type !== 'image') {
      return
    }
    if (!e || !e.target) return
    const eventTarget = e.target as HTMLElement
    const target = await getTarget(eventTarget)
    if (!target) return
    const uuid = target.getAttribute('data-uuid')

    setDropOver(uuid ?? '-1')

    const imgEl = target?.firstElementChild?.firstElementChild as HTMLImageElement
    if (eventTarget.getAttribute('putIn')) {
      dropIn.current = uuid
      const imgUrl = (data as any).value.thumb || (data as any).value.url
      !srcCache.current && (srcCache.current = imgEl.src)
      imgEl.src = imgUrl
    } else {
      srcCache.current && imgEl && (imgEl.src = srcCache.current)
      srcCache.current = ''
      dropIn.current = ''
    }
  }

  async function drop(event: React.MouseEvent) {
    const e = event.nativeEvent as MouseEvent & { layerX: number; layerY: number }
    if (!controlState.dDraging) {
      return
    }
    if (!e || !e.target) return
    const eventTarget = e.target as HTMLElement

    setDraging(false)

    const droppedIn = dropIn.current
    dropIn.current = ''

    setDropOver('-1')
    setShowMoveable(false)

    const lost = eventTarget.className !== 'design-canvas'
    e.preventDefault()
    const { data: item, type } = JSON.parse(JSON.stringify(widgetState.selectItem))
    setSelectItem({})

    let setting: Partial<TPageState> = {}
    if (!type) {
      return
    }
    setting = await setWidgetData(type, item, setting)
    const canvasEl = document.getElementById('page-design-canvas')
    if (!canvasEl) return
    const lostX = e.x - canvasEl.getBoundingClientRect().left
    const lostY = e.y - canvasEl.getBoundingClientRect().top
    const zoomValue = currentZoom()

    if (type === 'group') {
      const parent: { width?: number; height?: number } = {}
      const componentItem = await getComponentsData(item)
      componentItem.forEach((element) => {
        if (element.type === 'w-group') {
          parent.width = element.width
          parent.height = element.height
        }
      })
      const groupHalf = {
        x: parent.width ? (parent.width * zoomValue) / 100 / 2 : 0,
        y: parent.height ? (parent.height * zoomValue) / 100 / 2 : 0,
      }
      componentItem.forEach((element) => {
        element.left += (lost ? lostX - groupHalf.x : e.layerX - groupHalf.x) * (100 / zoomValue)
        element.top += (lost ? lostY - groupHalf.y : e.layerY - groupHalf.y) * (100 / zoomValue)
      })
      addGroup(componentItem)
    }

    const half = {
      x: setting.width ? (setting.width * zoomValue) / 100 / 2 : 0,
      y: setting.height ? (setting.height * zoomValue) / 100 / 2 : 0,
    }
    setting.left = (lost ? lostX - half.x : e.layerX - half.x) * (100 / zoomValue)
    setting.top = (lost ? lostY - half.y : e.layerY - half.y) * (100 / zoomValue)
    if (lost && type === 'image') {
      const target = await getTarget(eventTarget)
      if (!target) return
      const targetType = target.getAttribute('data-type')
      const uuid = target.getAttribute('data-uuid')
      if (targetType === 'w-mask') {
        setShowMoveable(true)
        const widget = currentWidgets().find((w) => w.uuid === uuid)
        if (!widget) return
        widget.imgUrl = item.value.url
      } else {
        if (droppedIn) {
          const widget = currentWidgets().find((w) => w.uuid == droppedIn)
          if (!widget) return
          widget.imgUrl = item.value.url
          setShowMoveable(true)
        } else {
          addWidget(setting as TdWidgetData)
        }
      }
    } else if (type === 'bg') {
      // background image position
    } else if (type !== 'group') {
      addWidget(setting as TdWidgetData)
    }
  }

  function getScreen() {
    const pageDesignEl = document.getElementById('page-design')
    if (!pageDesignEl) return
    updateScreen({
      width: pageDesignEl.offsetWidth,
      height: pageDesignEl.offsetHeight,
    })
  }

  async function handleSelection(e: MouseEvent) {
    if (e.which === 3) {
      return
    }
    if (!e || !e.target) return
    const target = await getTarget(e.target as HTMLElement)
    if (!target) return
    const type = target.getAttribute('data-type')

    if (type) {
      let uuid = target.getAttribute('data-uuid')
      if (uuid !== '-1' && !controlState.dAltDown) {
        const widget = currentWidgets().find((item) => item.uuid === uuid)
        const active = widgetState.dActiveElement
        if (!widget || !active) return
        if (widget.parent !== '-1' && widget.parent !== active.uuid && widget.parent !== active.parent) {
          uuid = widget.parent || null
        }
      }

      if (controlState.showRotatable !== false) {
        selectWidget({ uuid: uuid ?? ' -1' })
      }

      if (uuid !== '-1') {
        moveInit.initmovement(e)
      }
    } else {
      selectWidget({ uuid: '-1' })
    }
  }

  const outPadding = padding ?? dPresetPadding

  return (
    <div id="main" className={className}>
      <div
        id="page-design"
        style={{ paddingTop: dPaddingTop + 'px', minWidth: (dPage.width * dZoom) / 100 + outPadding * 2 + 'px' }}
      >
        <div
          id="out-page"
          className="out-page"
          style={{
            padding: padding ?? dPresetPadding + 'px',
            width: (dPage.width * dZoom) / 100 + outPadding * 2 + 'px',
            height: (dPage.height * dZoom) / 100 + outPadding * 2 + 'px',
            opacity: 1 - (dZoom < 100 ? dPage.tag : 0),
          }}
        >
          {children}
          {needTools ? <ResizePage width={(dPage.width * dZoom) / 100} height={(dPage.height * dZoom) / 100} /> : null}
          <PageWatermark customStyle={{ height: (dPage.height * dZoom) / 100 + 'px' }}>
            <div
              id={pageDesignCanvasId}
              className="design-canvas"
              data-type={dPage.type}
              data-uuid={dPage.uuid}
              style={{
                width: dPage.width + 'px',
                height: dPage.height + 'px',
                transform: 'scale(' + dZoom / 100 + ')',
                transformOrigin: (dZoom >= 100 ? 'center' : 'left') + ' top',
                backgroundColor: dPage.backgroundGradient ? undefined : dPage.backgroundColor,
                backgroundImage: dPage.backgroundImage ? `url(${dPage?.backgroundImage})` : dPage.backgroundGradient || undefined,
                backgroundSize: dPage.backgroundTransform?.x ? 'auto' : 'cover',
                backgroundPositionX: (dPage.backgroundTransform?.x || 0) + 'px',
                backgroundPositionY: (dPage.backgroundTransform?.y || 0) + 'px',
                opacity: dPage.opacity + (dZoom < 100 ? dPage.tag : 0),
              }}
              onMouseMove={dropOver}
              onDrop={drop as any}
              onMouseUp={drop}
            >
              <Layers
                needTools={needTools}
                pageUuid={dPage.uuid}
                parentLeft={dPage.left}
                parentTop={dPage.top}
                widgets={renderDWidgets}
              />
              {/* What Moveable snaps to when a ruler guide is in the way */}
              {needTools ? <SnapGuides /> : null}
            </div>
          </PageWatermark>
        </div>
      </div>
      {bottom}
    </div>
  )
}
