// src/components/modules/widgets/wImage/wImageStatic.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2024-04-12 17:47:19
 * @Description: 静态组件
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-04-16 16:25:35
-->
<template>
  <div
    ref="widgetRef"
    :style="{
      position: state.position,
      left: params.left - parent.left + 'px',
      top: params.top - parent.top + 'px',
      width: params.width + 'px',
      height: params.height + 'px',
      opacity: params.opacity,
    }"
  >
    <div :style="{ transform: params.flip ? `rotate${params.flip}(180deg)` : undefined, borderRadius: params.radius + 'px', '-webkit-mask-image': `${params.mask ? `url('${params.mask}')` : 'initial'}` }" :class="['img__box', { mask: params.mask }]">
      <div v-if="params.isNinePatch" ref="targetRef" class="target" :style="{ border: `${(params.height * params.sliceData.ratio) / 2}px solid transparent`, borderImage: `url('${params.imgUrl}') ${params.sliceData.left} round` }"></div>
      <img v-else ref="targetRef" class="target" style="transform-origin: center" :src="params.imgUrl" />
    </div>
  </div>
</template>

<script lang="ts" setup>
import { CSSProperties, onMounted, reactive, ref } from 'vue'
import setting from "./wImageSetting"

type TProps = {
  params: typeof setting
  parent: {
    left: number
    top: number
  }
}

type TState = {
  position: 'absolute' | 'relative', // 'absolute'relative
  editBoxStyle: CSSProperties,
  cropWidgetXY: {
    x: number
    y: number
  }
  holdPosition: {
    left: number
    top: number
  }
}

const props = defineProps<TProps>()
const state = reactive<TState>({
  position: 'absolute', // 'absolute'relative
  editBoxStyle: {
    transformOrigin: 'center',
    transform: '',
  },
  cropWidgetXY: {
    x: 0,
    y: 0,
  },
  holdPosition: {
    left: 0,
    top: 0,
  }
})

const widgetRef = ref<HTMLElement | null>(null)
const targetRef = ref<HTMLImageElement | null>(null)

// A rotated or flipped image has to look the same here as it does on the
// canvas, otherwise thumbnails and slides quietly straighten it out. Mirrors
// what wImage.vue does on mount: the box carries the rotation, the picture
// inside it carries any crop/zoom transform.
onMounted(() => {
  if (props.params.rotate && widgetRef.value) {
    widgetRef.value.style.transform = `rotate(${props.params.rotate})`
  }
  if (props.params.transform && targetRef.value) {
    targetRef.value.style.transform = props.params.transform
  }
})
</script>

<style lang="less" scoped>
.mask {
  -webkit-mask-size: 100% 100%;
  -webkit-mask-position: center;
}
.img__box {
  width: 100%;
  height: 100%;
  overflow: hidden;
  img {
    display: block;
  }
}
.target {
  display: block;
  width: 100%;
  height: 100%;
}
</style>

// src/components/modules/widgets/wImage/wImageStatic.tsx
import { memo, useEffect, useRef } from 'react'
import { cx } from '@/utils/dom'
import type { WidgetProps } from '../types'

function WImageStatic({ params, parent, className, ...rest }: WidgetProps) {
  const p = params as any
  const widgetRef = useRef<HTMLDivElement | null>(null)
  const targetRef = useRef<HTMLImageElement | null>(null)

  // A rotated or flipped image has to look the same here as it does on the
  // canvas, otherwise thumbnails and slides quietly straighten it out. Mirrors
  // what wImage does on mount: the box carries the rotation, the picture inside
  // it carries any crop/zoom transform.
  useEffect(() => {
    if (p.rotate && widgetRef.current) widgetRef.current.style.transform = `rotate(${p.rotate})`
    if (p.transform && targetRef.current) targetRef.current.style.transform = p.transform
  }, [p.rotate, p.transform])

  return (
    <div
      {...rest}
      ref={widgetRef}
      className={className}
      style={{
        position: 'absolute',
        left: p.left - parent.left + 'px',
        top: p.top - parent.top + 'px',
        width: p.width + 'px',
        height: p.height + 'px',
        opacity: p.opacity,
      }}
    >
      <div
        style={{
          transform: p.flip ? `rotate${p.flip}(180deg)` : undefined,
          borderRadius: p.radius + 'px',
          WebkitMaskImage: `${p.mask ? `url('${p.mask}')` : 'initial'}`,
        }}
        className={cx('img__box', { mask: !!p.mask })}
      >
        {p.isNinePatch ? (
          <div
            ref={targetRef as any}
            className="target"
            style={{
              border: `${(p.height * p.sliceData.ratio) / 2}px solid transparent`,
              borderImage: `url('${p.imgUrl}') ${p.sliceData.left} round`,
            }}
          />
        ) : (
          <img ref={targetRef} className="target" style={{ transformOrigin: 'center' }} src={p.imgUrl} />
        )}
      </div>
    </div>
  )
}

export default memo(WImageStatic)
