// src/components/modules/panel/StylePanel.tsx
import { useEffect, useMemo, useState } from 'react'
import { useSnapshot } from 'valtio'
import alignIconList from '@/assets/data/AlignListData'
import IconItemSelect, { type TIconItemSelectData } from '../settings/IconItemSelect'
import AnimateWrap from '../settings/AnimateSelect/AnimateWrap'
import Button from '@/components/ui/Button'
import Segmented from '@/components/ui/Segmented'
import { DistributeHorizontalIcon, DistributeVerticalIcon } from '@/components/ui/icons'
import { widgetState } from '@/store/state'
import { setShowMoveable } from '@/store/control'
import { getCombined, realCombined } from '@/store/group'
import { distributeGeometry, setDWidgets, updateAlign } from '@/store/widget'
import type { TdWidgetData } from '@/store/types'
import LayerList from './components/LayerList'
import { styleComponents } from './styleRegistry'
import './stylePanel.less'

/** Evening out the gaps needs a gap on either side of something, so three widgets. */
const DISTRIBUTE_MINIMUM = 3

const distributeIconList: TIconItemSelectData[] = [
  { key: 'distribute', Icon: DistributeHorizontalIcon, tip: 'Distribute horizontally', value: 'horizontal' },
  { key: 'distribute', Icon: DistributeVerticalIcon, tip: 'Distribute vertically', value: 'vertical' },
]

export default function StylePanel() {
  const [activeTab, setActiveTab] = useState(0)
  const [showGroupCombined, setShowGroupCombined] = useState(false)
  const snap = useSnapshot(widgetState)
  const activeType = snap.dActiveElement?.type
  const activeUuid = snap.dActiveElement?.uuid
  const selectCount = snap.dSelectWidgets.length
  /** The page has no entrance of its own; everything drawn on it does. */
  const animatable = !!activeType && activeType !== 'page'

  useEffect(() => {
    const timer = setTimeout(() => {
      setShowGroupCombined(selectCount > 1)
    }, 100)
    return () => clearTimeout(timer)
  }, [selectCount])

  function handleCombine() {
    realCombined()
  }

  const alignItems = useMemo(
    () => [...alignIconList, ...distributeIconList.map((item) => ({ ...item, disabled: selectCount < DISTRIBUTE_MINIMUM }))],
    [selectCount],
  )

  function alignAction(item: TIconItemSelectData) {
    if (item.key === 'distribute') {
      distributeGeometry({ distribute: item.value as any, uuids: widgetState.dSelectWidgets.map((widget) => widget.uuid) })
      return
    }
    const sWidgets: TdWidgetData[] = JSON.parse(JSON.stringify(widgetState.dSelectWidgets))
    getCombined().then((group) => {
      sWidgets.forEach((element) => {
        updateAlign({ align: item.value as any, uuid: element.uuid, group })
      })
    })
  }

  function layerChange(newLayer: TdWidgetData[]) {
    setDWidgets(newLayer.slice().reverse())
    setShowMoveable(false)
  }

  const StyleComp = activeType ? styleComponents[`${activeType}-style`] : undefined

  return (
    <div id="style-panel">
      <div className="style-tab">
        <Segmented
          aria-label="Panel"
          value={activeTab === 0 ? 'settings' : 'layers'}
          options={[
            { label: 'Settings', value: 'settings' },
            { label: 'Layers', value: 'layers' },
          ]}
          onChange={(next) => setActiveTab(next === 'settings' ? 0 : 1)}
        />
      </div>
      <div className="style-wrap" style={{ display: activeTab === 0 ? undefined : 'none' }}>
        <div className="multi-select" style={{ display: showGroupCombined ? undefined : 'none' }}>
          <Button plain type="primary" className="gounp__btn" onClick={handleCombine}>
            Group
          </Button>
          <IconItemSelect label="" data={alignItems} onFinish={alignAction} />
        </div>
        {animatable ? (
          <div className="animate-slot" style={{ display: showGroupCombined ? 'none' : undefined }}>
            <AnimateWrap key={activeUuid} widget={widgetState.dActiveElement as TdWidgetData} />
          </div>
        ) : null}
        {StyleComp ? (
          // `display: contents` rather than a plain box: every style panel is
          // `height: 100%`, and a percentage height resolves against the nearest
          // box — an ordinary wrapper here silently collapses all of them to
          // their content height.
          <div style={{ display: showGroupCombined ? 'none' : 'contents' }}>
            <StyleComp />
          </div>
        ) : null}
      </div>
      <div className="layer-wrap" style={{ display: activeTab === 1 ? undefined : 'none' }}>
        <LayerList data={widgetState.dWidgets} onChange={layerChange} />
      </div>
    </div>
  )
}

// src/components/modules/panel/stylePanel.vue
<template>
  <div id="style-panel">
    <div class="style-tab">
      <span :class="['tab', { 'active-tab': activeTab === 0 }]" @click="activeTab = 0">Settings</span>
      <span :class="['tab', { 'active-tab': activeTab === 1 }]" @click="activeTab = 1">Layers</span>
    </div>
    <div v-show="activeTab === 0" class="style-wrap">
      <div v-show="showGroupCombined" style="padding: 2rem 0">
        <el-button plain type="primary" class="gounp__btn" @click="handleCombine">Group</el-button>
        <icon-item-select label="" :data="iconList" @finish="alignAction" />
      </div>
      <component :is="dActiveElement?.type + '-style'" v-show="!showGroupCombined" v-if="dActiveElement?.type" />
      <!--
        Animation sits here rather than inside each w*Style component so that
        every element type gets it from one place. The page itself is not an
        element and has nothing to animate, so it is excluded.
      -->
      <div v-if="animatable" v-show="!showGroupCombined" class="animate-slot">
        <animate-wrap :widget="dActiveElement as TdWidgetData" :key="dActiveElement?.uuid" />
      </div>
    </div>
    <div v-show="activeTab === 1" class="layer-wrap">
      <layer-list :data="dWidgets" @change="layerChange" />
    </div>
  </div>
</template>

<script setup lang="ts">
// Style面板
// const NAME = 'style-panel'
import alignIconList, { AlignListData } from '@/assets/data/AlignListData'
import iconItemSelect, { TIconItemSelectData } from '../settings/iconItemSelect.vue'
import animateWrap from '../settings/AnimateSelect/AnimateWrap.vue'
import { computed, ref, watch } from 'vue';
// import { useSetupMapGetters } from '@/common/hooks/mapGetters';
import { useControlStore, useGroupStore, useHistoryStore, useWidgetStore } from '@/store';
import { storeToRefs } from 'pinia';
import { TdWidgetData } from '@/store/design/widget';
import type { TUpdateAlignData } from '@/store/design/widget/actions/align'

const widgetStore = useWidgetStore()
const controlStore = useControlStore()
const groupStore = useGroupStore()
const historyStore = useHistoryStore()

const activeTab = ref(0)
const iconList = ref<AlignListData[]>(alignIconList)
const showGroupCombined = ref(false)

// const { dActiveElement, dWidgets, dSelectWidgets } = useSetupMapGetters(['dActiveElement', 'dWidgets', 'dSelectWidgets'])
const { dActiveElement, dWidgets, dSelectWidgets } = storeToRefs(widgetStore)

/** The page has no entrance of its own; everything drawn on it does. */
const animatable = computed(() => {
  const type = dActiveElement.value?.type
  return !!type && type !== 'page'
})

watch(
  dSelectWidgets,
  (items) => {
    setTimeout(() => {
      showGroupCombined.value = items.length > 1
    }, 100)
  },
  {
    deep: true
  }
)

function handleCombine() {
  groupStore.realCombined()
  // store.dispatch('realCombined')
}

// ...mapActions(['selectWidget', 'updateAlign', 'updateHoverUuid', 'getCombined', 'realCombined', 'ungroup', 'pushHistory']),
function alignAction(item: TIconItemSelectData) {
  const sWidgets: TdWidgetData[] = JSON.parse(JSON.stringify(dSelectWidgets.value))
  groupStore.getCombined().then(group => {
    sWidgets.forEach((element) => {
      widgetStore.updateAlign({
        align: (item.value as TUpdateAlignData['align']),
        uuid: element.uuid,
        group,
      })
    });
  })
}
function layerChange(newLayer: TdWidgetData[]) {
  widgetStore.setDWidgets(newLayer.toReversed())
  controlStore.setShowMoveable(false)
}

</script>

<style lang="less" scoped>
// The animation card is the one control that is not part of a widget's own
// style component, so it carries its own gutter.
.animate-slot {
  padding: 12px 10px 20px;
}

#style-panel {
  background-color: @surface;
  border-left: 1px solid @line;
  display: flex;
  flex-direction: column;
  height: 100%;
  position: relative;
  width: @style-panel-width;
  flex-shrink: 0;

  // A quiet two-up switch rather than a shadowed tab bar.
  .style-tab {
    display: flex;
    gap: 4px;
    padding: 10px 12px;
    border-bottom: 1px solid @line;
    width: 100%;
    z-index: 10;

    .tab {
      user-select: none;
      flex: 1;
      text-align: center;
      padding: 6px 10px;
      border-radius: @radius-sm;
      font-size: @text-base;
      font-weight: 500;
      color: @ink-3;
      cursor: pointer;
      transition: background-color 0.12s ease, color 0.12s ease;

      &:hover {
        background: @surface-2;
        color: @ink-2;
      }
    }

    .tab.active-tab {
      background: @accent-soft;
      color: @accent;
      font-weight: 600;
    }
  }

  .style-wrap {
    flex: 1;
    overflow: auto;
    width: 100%;
    padding: 4px 16px 24px;
  }

  .layer-wrap {
    flex: 1;
    overflow: auto;
    width: 100%;
  }
}

#style-panel ::-webkit-scrollbar {
  width: 6px;
}

.gounp {
  &__btn {
    width: 100%;
    margin-bottom: 1.5rem;
  }
}
</style>
