// src/views/components/UploadTemplate.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-07-12 11:26:53
 * @Description: 上传用户模板
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-08-17 10:51:11
-->
<template>
  <el-button v-show="isDone" type="primary" plain @click="prepare"><b>Upload template</b></el-button>
</template>

<script lang="ts" setup>
import api from '@/api'
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import useNotification from '@/common/methods/notification'
import { useFontStore } from '@/common/methods/fonts'
import _config from '@/config'
import github from '@/api/github'
// import { useSetupMapGetters } from '@/common/hooks/mapGetters'
import { useControlStore, useCanvasStore, useWidgetStore } from '@/store'
import { storeToRefs } from 'pinia'
import { TdWidgetData } from '@/store/design/widget'

type TProps = {
  modelValue?: string
  isDone?: boolean
}

export type TEmitChangeData = {
  downloadPercent: number | null
  downloadText: string
  downloadMsg?: string
  cancelText?: string
}

type TEmits = {
  (event: 'change', data: TEmitChangeData): void
  (event: 'update:modelValue', data: string): void
}

type TState = {
  stateBollean: false
  title: ''
  loading: false
}

// const { dWidgets } = useSetupMapGetters(['dWidgets'])
const { dPage } = storeToRefs(useCanvasStore())

const props = defineProps<TProps>()
const emit = defineEmits<TEmits>()

const route = useRoute()
const router = useRouter()

const widgetStore = useWidgetStore()
const controlStore = useControlStore()
const { dWidgets } = storeToRefs(widgetStore)
const state = reactive<TState>({
  stateBollean: false,
  title: '',
  loading: false,
})

useFontStore.init() // Load the fonts

let addition = 0 // Bytes so far
let lenCount = 0 // Total bytes
let lens = 0 // Task count
const queue: TdWidgetData[] = [] // Queue
let widgets: TdWidgetData[] = []
let page: Record<string, any> = {}

const { type } = route.query

async function prepare() {
  controlStore.setShowMoveable(false) // Clear the previous selection box

  if (Number(type) == 1) {
    // 保存组件，组合元素要保证在最后一位
    if (dWidgets.value[0].type === 'w-group') {
      const group: any = dWidgets.value.shift()
      if (!group) return
      group.record.width = 0
      group.record.height = 0
      dWidgets.value.push(group)
    }
    // TIP：上传组件必须将所有图层组合成组
    if (!dWidgets.value.some((x: Record<string, any>) => x.type === 'w-group')) {
      alert('Group all layers together before uploading.')
      return
    }
  }

  addition = 0
  lenCount = 0
  widgets = dWidgets.value
  page = dPage.value

  if (page.backgroundImage) {
    emit('change', { downloadPercent: 1, downloadText: 'Getting ready to upload', downloadMsg: 'Please wait…' })
    page.backgroundImage = await github.putPic(page.backgroundImage.split(',')[1])
  }

  for (const item of widgets) {
    if (item.type === 'w-image') {
      lenCount += item.imgUrl?.length || 0
      queue.push(item)
    }
  }
  lens = queue.length
  uploadImgs()
}

async function uploadImgs() {
  if (queue.length > 0) {
    const item = queue.pop()
    if (!item) return
    const url = await github.putPic((item?.imgUrl || '').split(',')[1])
    addition += item.imgUrl?.length || 0
    let downloadPercent: number | null = (addition / lenCount) * 100
    downloadPercent >= 100 && (downloadPercent = null)
    emit('change', { downloadPercent, downloadText: 'Uploading files', downloadMsg: `Done: ${lens - queue.length} / ${lens}` })
    item.imgUrl = url
    uploadImgs()
  } else {
    uploadTemplate()
  }
}

const uploadTemplate = async () => {
  emit('change', { downloadPercent: 95, downloadText: 'Making the cover image', downloadMsg: 'Almost done...' })
  const data = Number(type) == 1 ? JSON.stringify(widgets) : JSON.stringify({ page, widgets })
  const { id, stat, msg } = await api.home.saveTemp({ title: 'From your own design', type, data, width: page.width, height: page.height })
  stat !== 0 ? useNotification('Saved', '') : useNotification('Could not save', msg, { type: 'error' })
  router.push({ path: '/psd', query: { id }, replace: true })
  emit('change', { downloadPercent: 99.99, downloadText: 'Upload complete', cancelText: '' }) // Close
}

defineExpose({
  prepare,
})
</script>

<!-- <style lang="less" scoped></style> -->

// react/src/views/components/UploadTemplate.tsx
import { useRef } from 'react'
import api from '@/api'
import github from '@/api/github'
import useNotification from '@/common/methods/notification'
import { useFontStore } from '@/common/methods/fonts'
import { readQuery, replaceQuery } from '@/common/hooks/useRouteQuery'
import Button from '@/components/ui/Button'
import { canvasState, widgetState } from '@/store/state'
import { setShowMoveable } from '@/store/control'
import type { TdWidgetData } from '@/store/types'

export type TEmitChangeData = {
  downloadPercent: number | null
  downloadText: string
  downloadMsg?: string
  cancelText?: string
}

type Props = {
  isDone?: boolean
  onChange: (data: TEmitChangeData) => void
}

export default function UploadTemplate({ isDone, onChange }: Props) {
  const started = useRef(false)
  if (!started.current) {
    started.current = true
    useFontStore.init()
  }

  const addition = useRef(0)
  const lenCount = useRef(0)
  const lens = useRef(0)
  const queue = useRef<TdWidgetData[]>([])
  const widgets = useRef<TdWidgetData[]>([])
  const page = useRef<Record<string, any>>({})

  async function prepare() {
    setShowMoveable(false)
    const { type } = readQuery()

    if (Number(type) == 1) {
      if (widgetState.dWidgets[0].type === 'w-group') {
        const group = widgetState.dWidgets.shift()
        if (!group) return
        if (!group.record) return
        group.record.width = 0
        group.record.height = 0
        widgetState.dWidgets.push(group)
      }
      if (!widgetState.dWidgets.some((x) => x.type === 'w-group')) {
        alert('Group all layers together before uploading.')
        return
      }
    }

    addition.current = 0
    lenCount.current = 0
    widgets.current = widgetState.dWidgets
    page.current = canvasState.dPage

    if (page.current.backgroundImage) {
      onChange({ downloadPercent: 1, downloadText: 'Getting ready to upload', downloadMsg: 'Please wait…' })
      page.current.backgroundImage = await github.putPic(page.current.backgroundImage.split(',')[1])
    }

    for (const item of widgets.current) {
      if (item.type === 'w-image') {
        lenCount.current += item.imgUrl?.length || 0
        queue.current.push(item)
      }
    }
    lens.current = queue.current.length
    uploadImgs()
  }

  async function uploadImgs() {
    if (queue.current.length > 0) {
      const item = queue.current.pop()
      if (!item) return
      const url = await github.putPic((item?.imgUrl || '').split(',')[1])
      addition.current += item.imgUrl?.length || 0
      let downloadPercent: number | null = (addition.current / lenCount.current) * 100
      downloadPercent >= 100 && (downloadPercent = null)
      onChange({
        downloadPercent,
        downloadText: 'Uploading files',
        downloadMsg: `Done: ${lens.current - queue.current.length} / ${lens.current}`,
      })
      item.imgUrl = url
      uploadImgs()
    } else {
      uploadTemplate()
    }
  }

  async function uploadTemplate() {
    onChange({ downloadPercent: 95, downloadText: 'Making the cover image', downloadMsg: 'Almost done...' })
    const { type } = readQuery()
    const data = Number(type) == 1 ? JSON.stringify(widgets.current) : JSON.stringify({ page: page.current, widgets: widgets.current })
    const { id, stat, msg }: any = await api.home.saveTemp({
      title: 'From your own design',
      type,
      data,
      width: page.current.width,
      height: page.current.height,
    })
    stat !== 0 ? useNotification('Saved', '') : useNotification('Could not save', msg, { type: 'error' })
    replaceQuery({ id: String(id) })
    onChange({ downloadPercent: 99.99, downloadText: 'Upload complete', cancelText: '' })
  }

  return (
    <>
      {isDone ? (
        <Button type="primary" plain onClick={prepare}>
          <b>Upload template</b>
        </Button>
      ) : null}
    </>
  )
}
