// src/components/modules/widgets/wText/wText.vue
<template>
  <div
    :id="`${params.uuid}`"
    ref="widget"
    v-loading="state.loading"
    :class="['w-text', { editing: state.editable, 'layer-lock': params.lock }, params.uuid]"
    :style="{
      position: 'absolute',
      left: params.left - parent.left + 'px',
      top: params.top - parent.top + 'px',
      width: params.width + 'px',
      minWidth: params.fontSize + 'px',
      minHeight: params.fontSize * params.lineHeight + 'px',
      height: params.height + 'px',
      lineHeight: params.fontSize * params.lineHeight + 'px',
      letterSpacing: (params.fontSize * params.letterSpacing) / 100 + 'px',
      fontSize: params.fontSize + 'px',
      color: params.color,
      textAlign: params.textAlign,
      textAlignLast: params.textAlignLast,
      fontWeight: params.fontWeight,
      fontStyle: params.fontStyle,
      textDecoration: params.textDecoration,
      opacity: params.opacity,
      backgroundColor: params.backgroundColor,
      writingMode: params.writingMode,
      fontFamily: `'${params.fontClass.value}'`,
    }"
    @dblclick="(e) => dblclickText(e)"
  >
    <template v-if="params.textEffects && !state.editable">
      <div
        v-for="(ef, efi) in params.textEffects"
        :key="efi + 'effect'"
        :style="{ fontFamily: `'${params.fontClass.value}'`, ...effectStyle(ef) }"
        class="edit-text effect-text"
        spellcheck="false"
        v-html="params.text"
      ></div>
    </template>
    <div ref="editWrap" :style="{ fontFamily: `'${params.fontClass.value}'` }" class="edit-text" :spellcheck="spellcheck" :contenteditable="state.editable ? 'plaintext-only' : false" @input="writingText($event)" @blur="writeDone($event)" v-html="params.text"></div>
  </div>
</template>

<script lang="ts" setup>
import useSpellcheck from '@/common/hooks/useSpellcheck'
// 文本组件
// const NAME = 'w-text'

import { reactive, toRefs, computed, onUpdated, watch, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { fontMinWithDraw } from '@/utils/widgets/loadFontRule'
import effectStyle from './effectStyle'
import { wTextSetting } from './wTextSetting'
import { useForceStore, useHistoryStore, useWidgetStore } from '@/store'

export type TwTextParams = {
  rotate?: number
  lock?: boolean
  width?: number
  height?: number
} & typeof wTextSetting

type TProps = {
  params: TwTextParams
  parent: {
    left: number
    top: number
  }
}

const props = defineProps<TProps>()

/** Editor-wide preference; see common/hooks/useSpellcheck.ts. */
const { enabled: spellcheck } = useSpellcheck()
const widgetStore = useWidgetStore()
const forceStore = useForceStore()
const historyStore = useHistoryStore()
const route = useRoute()
const state = reactive({
  loading: false,
  editable: false,
  loadFontDone: '',
})
const widget = ref<HTMLElement | null>(null)
const editWrap = ref<HTMLElement | null>(null)

const dActiveElement = computed(() => widgetStore.dActiveElement)
const isDraw = computed(() => route.name === 'Draw')

onUpdated(() => {
  updateRecord()
})

onMounted(() => {
  updateRecord()

  if (!widget.value) return
  props.params.transform && (widget.value.style.transform = props.params.transform)
  props.params.rotate && (widget.value.style.transform += `translate(0px, 0px) rotate(${props.params.rotate}) scale(1, 1)`)
  // store.commit('updateRect')
})

watch(
  () => props.params,
  async (nval) => {
    updateText()
    if (state.loading) {
      return
    }
    let font = nval.fontClass
    const isDone = font.value === state.loadFontDone

    if (font.url && !isDone) {
      if (font.id && isDraw.value) {
        state.loading = false
      }
      if (fontMinWithDraw) {
        return
      }
      state.loading = !isDraw.value
      const loadFont = new window.FontFace(font.value, `url(${font.url})`)
      await loadFont.load()
      document.fonts.add(loadFont)
      state.loadFontDone = font.value
      state.loading = false
    } else {
      state.loading = false
    }
  },
  { immediate: true, deep: true },
)

watch(
  () => state.editable,
  (value) => {
    widgetStore.updateWidgetData({
      uuid: String(props.params.uuid),
      key: 'editable',
      value,
    })
  },
)

function updateRecord() {
  if (!widget.value) return
  if (dActiveElement.value && dActiveElement.value.uuid === String(props.params.uuid)) {
    let record = dActiveElement.value.record
    if (!record) return
    record.width = widget.value.offsetWidth
    record.height = widget.value.offsetHeight
    record.minWidth = props.params.fontSize
    record.minHeight = props.params.fontSize * props.params.lineHeight
    writingText()
  }
}

function updateText(e?: Event) {
  const value = e && e.target ? (e.target as HTMLElement).innerHTML : props.params.text //.replace(/\n/g, '<br/>')
  if (value !== props.params.text) {
    widgetStore.updateWidgetData({
      uuid: String(props.params.uuid),
      key: 'text',
      value,
    })
  }
}

function writingText(e?: Event) {
  // updateText(e)
  // TODO: 修正文字选框高度
  const el = editWrap.value || widget.value
  if (!el) return
  widgetStore.updateWidgetData({
    uuid: String(props.params.uuid),
    key: 'height',
    value: el.offsetHeight,
  })
  forceStore.setUpdateRect()
  // store.commit('updateRect')
}

function writeDone(e: Event) {
  state.editable = false
  updateText(e)
}

function dblclickText(_: MouseEvent) {
  if (state.editable) return
  state.editable = true
  const el = editWrap.value || widget.value
  setTimeout(() => {
    if (!el) return
    el.focus()
    if (document.selection) {
      const range = document.body.createTextRange()
      range.moveToElementText(el)
      range.select()
    } else {
      const range = document.createRange()
      range.selectNodeContents(el)
      window.getSelection()?.removeAllRanges()
      window.getSelection()?.addRange(range)
    }
  }, 100)
}

defineExpose({
  effectStyle,
  updateRecord,
  writingText,
  updateText,
  writeDone,
  dblclickText,
  widget,
  editWrap,
})
</script>

<style lang="less" scoped>
.w-text {
  // cursor: pointer;
  user-select: none;
}
.w-text.editing {
  cursor: text;
  user-select: text;
}
.edit-text {
  outline: none;
  word-break: break-word;
  white-space: pre-wrap;
  margin: 0;
}
.effect-text {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>

// src/components/modules/widgets/wText/wText.tsx
import { memo, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { useSnapshot } from 'valtio'
import { setUpdateRect } from '@/store/force'
import { widgetState } from '@/store/state'
import { updateWidgetData, updateWidgetMultiple } from '@/store/widget/widget'
import { fontMinWithDraw } from '@/utils/widgets/loadFontRule'
import { cx } from '@/utils/dom'
import { useEditorMode } from '@/common/hooks/useEditorMode'
import useSpellcheck from '@/common/hooks/useSpellcheck'
import CurvedText from './CurvedText'
import layoutCurvedText, { forgetMeasurements } from './arcLayout'
import useFontTick from './useFontTick'
import effectStyle from './effectStyle'
import type { WidgetProps } from '../types'
import './wText.less'

function WText({ params, parent, id, className, child, ...rest }: WidgetProps) {
  const p = useSnapshot(params) as any
  const mode = useEditorMode()
  const isDraw = mode === 'draw'
  /** Editor-wide preference; see common/hooks/useSpellcheck.ts. */
  const { enabled: spellcheck } = useSpellcheck()

  const [loading, setLoading] = useState(false)
  const [editable, setEditable] = useState(false)
  const fontTick = useFontTick(p.fontClass.value)
  const widgetRef = useRef<HTMLDivElement | null>(null)
  const editWrapRef = useRef<HTMLDivElement | null>(null)
  const loadFontDone = useRef('')

  const fontFamily = `'${p.fontClass.value}'`

  /**
   * The arc, when there is one. Editing drops it, the way the text effects are
   * dropped: a curved run is a character per element, and there is nothing
   * there to put a cursor in. It comes back on the way out of the caret.
   */
  const curved = useMemo(
    () =>
      editable
        ? null
        : layoutCurvedText({
            text: p.text,
            curve: p.curve,
            fontSize: p.fontSize,
            lineHeight: p.lineHeight,
            letterSpacing: p.letterSpacing,
            fontFamily,
            fontWeight: p.fontWeight,
            fontStyle: p.fontStyle,
          }),
    // Neither fontTick nor loading is read above; they are what re-measures the
    // arc once the typeface it is set in has actually arrived, since the widths
    // it is built from come out of the font.
    [editable, p.text, p.curve, p.fontSize, p.lineHeight, p.letterSpacing, fontFamily, p.fontWeight, p.fontStyle, fontTick, loading],
  )

  useLayoutEffect(() => {
    const el = editWrapRef.current
    if (el && el.innerHTML !== p.text) {
      el.innerHTML = p.text ?? ''
    }
  }, [p.text, editable])

  useEffect(() => {
    updateRecord()
  })

  // Rebuilt from the store whenever it changes rather than once on mount, or an
  // undone rotation stays on screen: Moveable writes the turn straight to the
  // element, so nothing else puts it back.
  useEffect(() => {
    const el = widgetRef.current
    if (!el) return
    let transform = p.transform || ''
    if (p.rotate) transform += `translate(0px, 0px) rotate(${p.rotate}) scale(1, 1)`
    el.style.transform = transform
  }, [p.transform, p.rotate])

  useEffect(() => {
    let cancelled = false
    const font = params.fontClass as any
    if (!font) return
    const isDone = font.value === loadFontDone.current
    if (font.url && !isDone) {
      if (fontMinWithDraw) return
      setLoading(!isDraw)
      const loadFont = new window.FontFace(font.value, `url(${font.url})`)
      loadFont
        .load()
        .then(() => {
          if (cancelled) return
          document.fonts.add(loadFont)
          // Adding a face that has already loaded is not the font set loading
          // anything, so nothing else will say that the measurements taken in
          // the fallback are out of date.
          forgetMeasurements()
          loadFontDone.current = font.value
          setLoading(false)
        })
        .catch(() => {
          if (!cancelled) setLoading(false)
        })
    } else {
      setLoading(false)
    }
    return () => {
      cancelled = true
    }
  }, [params, p.fontClass.value, p.fontClass.url, isDraw])

  /**
   * Fits the widget's box to the arc.
   *
   * Straight text is laid out by the browser and measured back off the element,
   * which is what `writingText` does. A curved run is placed by us, so nothing
   * on the page knows how big it came out and the box has to be told.
   */
  useEffect(() => {
    if (!curved) return
    const width = Math.round(curved.width)
    const height = Math.round(curved.height)
    const wasWidth = Math.round(Number(params.width) || 0)
    if (wasWidth === width && Math.round(Number(params.height) || 0) === height) return
    updateWidgetMultiple({
      uuid: String(params.uuid),
      data: [
        // Deepening the curve draws the ends of the line in, so the box loses
        // width. Give half of that back to the left edge and the text bends
        // where it stands, rather than creeping across the page as it goes.
        { key: 'left', value: Math.round(Number(params.left) + (wasWidth ? (wasWidth - width) / 2 : 0)) },
        { key: 'width', value: width },
        { key: 'height', value: height },
      ],
    })
    // Next frame, not this one: the selection box is measured off the element,
    // and the element is still the size it was until the new box has rendered.
    requestAnimationFrame(() => setUpdateRect())
  }, [curved, params])

  const lastEditable = useRef(editable)
  useEffect(() => {
    if (lastEditable.current === editable) return
    lastEditable.current = editable
    updateWidgetData({ uuid: String(params.uuid), key: 'editable', value: editable })
  }, [editable, params.uuid])

  function updateRecord() {
    const el = widgetRef.current
    if (!el) return
    const active = widgetState.dActiveElement
    if (active && active.uuid === String(params.uuid)) {
      const record = active.record
      if (!record) return
      record.width = el.offsetWidth
      record.height = el.offsetHeight
      record.minWidth = params.fontSize as number
      record.minHeight = (params.fontSize as number) * (params as any).lineHeight
      writingText()
    }
  }

  function updateText(e?: { target: HTMLElement }) {
    const value = e && e.target ? e.target.innerHTML : params.text
    if (value !== params.text) {
      updateWidgetData({ uuid: String(params.uuid), key: 'text', value: value as string })
    }
  }

  function writingText() {
    // A curved run's box comes from the arc, not from what the browser laid
    // out — see the effect that fits it.
    if (curved) return
    const el = editWrapRef.current || widgetRef.current
    if (!el) return
    updateWidgetData({ uuid: String(params.uuid), key: 'height', value: el.offsetHeight })
    setUpdateRect()
  }

  function writeDone(e: React.FocusEvent<HTMLDivElement>) {
    setEditable(false)
    updateText({ target: e.target })
  }

  function dblclickText() {
    if (editable) return
    setEditable(true)
    setTimeout(() => {
      // Read after the re-render, not before it: a curved run has no editable
      // element until the caret goes in, and this is what puts it there.
      const el = editWrapRef.current || widgetRef.current
      if (!el) return
      el.focus()
      const range = document.createRange()
      range.selectNodeContents(el)
      window.getSelection()?.removeAllRanges()
      window.getSelection()?.addRange(range)
    }, 100)
  }

  return (
    <div
      {...rest}
      id={id ?? `${params.uuid}`}
      ref={widgetRef}
      className={cx('w-text', { editing: editable, 'layer-lock': !!p.lock }, String(params.uuid), className || '')}
      style={{
        position: 'absolute',
        left: p.left - parent.left + 'px',
        top: p.top - parent.top + 'px',
        width: p.width + 'px',
        minWidth: p.fontSize + 'px',
        minHeight: p.fontSize * p.lineHeight + 'px',
        height: p.height + 'px',
        lineHeight: p.fontSize * p.lineHeight + 'px',
        letterSpacing: (p.fontSize * p.letterSpacing) / 100 + 'px',
        fontSize: p.fontSize + 'px',
        color: p.color,
        textAlign: p.textAlign,
        textAlignLast: p.textAlignLast,
        fontWeight: p.fontWeight,
        fontStyle: p.fontStyle,
        textDecoration: p.textDecoration,
        opacity: p.opacity,
        backgroundColor: p.backgroundColor,
        writingMode: p.writingMode,
        fontFamily,
      }}
      onDoubleClick={dblclickText}
    >
      {p.textEffects && !editable
        ? p.textEffects.map((ef: any, efi: number) =>
            curved ? (
              <CurvedText key={efi + 'effect'} layout={curved} className="effect-text" style={{ fontFamily, ...effectStyle(ef) }} />
            ) : (
              <div
                key={efi + 'effect'}
                style={{ fontFamily, ...effectStyle(ef) }}
                className="edit-text effect-text"
                spellCheck={false}
                dangerouslySetInnerHTML={{ __html: p.text ?? '' }}
              />
            ),
          )
        : null}
      {curved ? (
        <CurvedText layout={curved} style={{ fontFamily }} />
      ) : (
        <div
          ref={editWrapRef}
          style={{ fontFamily }}
          className="edit-text"
          spellCheck={spellcheck}
          contentEditable={editable ? 'plaintext-only' : false}
          suppressContentEditableWarning
          onInput={() => writingText()}
          onBlur={writeDone}
        />
      )}
      {loading ? <div className="w-text__loading" /> : null}
    </div>
  )
}

export default memo(WText)
