// src/components/modules/widgets/wText/wTextStatic.vue
<template>
  <div
    ref="widget"
    :style="{
      position: 'absolute',
      left: params.left - parent.left + 'px',
      top: params.top - parent.top + 'px',
      width: params.width + 'px',
      minWidth: params.fontSize + 'px',
      minHeight: params.fontSize * params.lineHeight + 'px',
      height: params.height + 'px',
      lineHeight: params.fontSize * params.lineHeight + 'px',
      letterSpacing: (params.fontSize * params.letterSpacing) / 100 + 'px',
      fontSize: params.fontSize + 'px',
      color: params.color,
      textAlign: params.textAlign,
      fontWeight: params.fontWeight,
      fontStyle: params.fontStyle,
      textDecoration: params.textDecoration,
      opacity: params.opacity,
      backgroundColor: params.backgroundColor,
      writingMode: params.writingMode,
      fontFamily: `'${params.fontClass.value}'`,
    }"
  >
    <template v-if="params.textEffects">
      <div
        v-for="(ef, efi) in params.textEffects"
        :key="efi + 'effect'"
        :style="{ fontFamily: `'${params.fontClass.value}'`, ...effectStyle(ef) }"
        class="edit-text effect-text"
        spellcheck="false"
        v-html="params.text"
      ></div>
    </template>
    <div
      :style="{ fontFamily: `'${params.fontClass.value}'` }"
      class="edit-text" spellcheck="false" 
      v-html="params.text"></div>
  </div>
</template>

<script lang="ts" setup>
import { reactive, onMounted, ref } from 'vue'
import effectStyle from './effectStyle'
import { wTextSetting } from './wTextSetting'

export type TwTextParams = {
  rotate?: number
  lock?: boolean
  width?: number
  height?: number
} & typeof wTextSetting

type TProps = {
  params: TwTextParams
  parent: {
    left: number
    top: number
  }
}

const props = defineProps<TProps>()
const widget = ref<HTMLElement | null>(null)

onMounted(() => {
  if (!widget.value) return
  props.params.transform && (widget.value.style.transform = props.params.transform)
  props.params.rotate && (widget.value.style.transform += `translate(0px, 0px) rotate(${props.params.rotate}) scale(1, 1)`)
})

defineExpose({
  effectStyle,
  widget,
})
</script>

<style lang="less" scoped>
.edit-text {
  outline: none;
  word-break: break-word;
  white-space: pre-wrap;
  margin: 0;
}
.effect-text {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>

// src/components/modules/widgets/wText/wTextStatic.tsx
import { memo, useEffect, useMemo, useRef } from 'react'
import CurvedText from './CurvedText'
import layoutCurvedText from './arcLayout'
import useFontTick from './useFontTick'
import effectStyle from './effectStyle'
import type { WidgetProps } from '../types'
import './wText.less'

function WTextStatic({ params, parent, className, ...rest }: WidgetProps) {
  const p = params as any
  const widgetRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    const el = widgetRef.current
    if (!el) return
    p.transform && (el.style.transform = p.transform)
    p.rotate && (el.style.transform += `translate(0px, 0px) rotate(${p.rotate}) scale(1, 1)`)
  }, [p.transform, p.rotate])

  const fontFamily = `'${p.fontClass.value}'`
  const fontTick = useFontTick(fontFamily)

  // The box this draws in was fitted to the arc by the editor, so the layout
  // only has to be rebuilt, not measured back into the widget.
  const curved = useMemo(
    () =>
      layoutCurvedText({
        text: p.text,
        curve: p.curve,
        fontSize: p.fontSize,
        lineHeight: p.lineHeight,
        letterSpacing: p.letterSpacing,
        fontFamily,
        fontWeight: p.fontWeight,
        fontStyle: p.fontStyle,
      }),
    [p.text, p.curve, p.fontSize, p.lineHeight, p.letterSpacing, fontFamily, p.fontWeight, p.fontStyle, fontTick],
  )

  return (
    <div
      {...rest}
      ref={widgetRef}
      className={className}
      style={{
        position: 'absolute',
        left: p.left - parent.left + 'px',
        top: p.top - parent.top + 'px',
        width: p.width + 'px',
        minWidth: p.fontSize + 'px',
        minHeight: p.fontSize * p.lineHeight + 'px',
        height: p.height + 'px',
        lineHeight: p.fontSize * p.lineHeight + 'px',
        letterSpacing: (p.fontSize * p.letterSpacing) / 100 + 'px',
        fontSize: p.fontSize + 'px',
        color: p.color,
        textAlign: p.textAlign,
        fontWeight: p.fontWeight,
        fontStyle: p.fontStyle,
        textDecoration: p.textDecoration,
        opacity: p.opacity,
        backgroundColor: p.backgroundColor,
        writingMode: p.writingMode,
        fontFamily,
      }}
    >
      {p.textEffects
        ? p.textEffects.map((ef: any, efi: number) =>
            curved ? (
              <CurvedText key={efi + 'effect'} layout={curved} className="effect-text" style={{ fontFamily, ...effectStyle(ef) }} />
            ) : (
              <div
                key={efi + 'effect'}
                style={{ fontFamily, ...effectStyle(ef) }}
                className="edit-text effect-text"
                spellCheck={false}
                dangerouslySetInnerHTML={{ __html: p.text ?? '' }}
              />
            ),
          )
        : null}
      {curved ? (
        <CurvedText layout={curved} style={{ fontFamily }} />
      ) : (
        <div style={{ fontFamily }} className="edit-text" spellCheck={false} dangerouslySetInnerHTML={{ __html: p.text ?? '' }} />
      )}
    </div>
  )
}

export default memo(WTextStatic)
