// src/components/modules/settings/EffectSelect/ContainerWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-09 14:00:23
 * @Description: 图片容器
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-08-12 09:48:42
-->
<template>
  <el-card class="box-card" shadow="hover" :body-style="{ padding: state.effectSelect ? '20px' : 0 }">
    <template #header>
      <div class="card-header">
        <template v-if="state.effectSelect">
          <component :is="state.effectSelect" class="demo" />
        </template>
        <!-- <div v-show="!state.effectSelect">None</div> -->
        <span class="title">Image mask</span>
        <el-popover :visible="state.visiable" placement="bottom-end" :width="260" trigger="click">
          <div class="box__header">
            <el-radio-group v-model="state.type" size="small">
              <el-radio-button label="Shape" value="tuxing"></el-radio-button>
            </el-radio-group>
          </div>
          <div class="select__box">
            <div class="select__box__select-item" @click="select()">None</div>
            <el-image v-for="(item, i) in state.list" :key="i + 'l'" class="select__box__select-item" :src="item.thumb" fit="contain" @click="select(item.url)"></el-image>
          </div>
          <template #reference>
            <el-button class="button" link @click="state.visiable = !state.visiable">{{ state.visiable ? 'Cancel' : 'Choose' }}</el-button>
          </template>
        </el-popover>
      </div>
    </template>
  </el-card>
</template>

<script lang="ts" setup>
import api from '@/api'
import { toRefs, reactive, watch, onMounted, nextTick } from 'vue'
import { ElRadioGroup, ElRadioButton } from 'element-plus'
// import wSvg from '@/components/modules/widgets/wSvg/wSvg.vue'
import {wSvgSetting} from '@/components/modules/widgets/wSvg/wSvgSetting'
import { TGetListResult } from '@/api/material';

type TProps = {
  modelValue?: string
  degree?: number
}

type TEmits = {
  (event: 'change', data: Record<string, any>): void
}

type TState = {
  effectSelect: string
  visiable: boolean
  type: string
  list: {thumb: string, url: string}[]
}

const props = defineProps<TProps>()

const emit = defineEmits<TEmits>()

const state = reactive<TState>({
  effectSelect: '', // Selected template
  visiable: false, // Layer picker popover
  type: '1', // Type
  list: [],
})

const select = (value: string = '') => {
  state.visiable = false
  const setting = JSON.parse(JSON.stringify(wSvgSetting))
  setting.svgUrl = value
  emit('change', setting)
}


onMounted(async () => {
  await nextTick()
  state.effectSelect = props?.modelValue || ''
  // state.strength = props?.degree || state.strength
  getList()
})

async function getList() {
  const res = await api.material.getList({
    cate: 'mask',
  })
  state.list = res.list.map(({ thumb, url }) => {
    return { thumb, url }
  })
}

watch(
  () => state.type,
  (value) => {
    getList()
  },
)
defineExpose({
  select,
})
</script>

<style lang="less" scoped>
.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.text {
  font-size: 14px;
}

.item {
  display: flex;
  align-items: center;
}

.box-card {
  margin-top: 24px;
  width: 100%;
}

.demo {
  margin: -1.5rem 0 0 1rem;
}
.title {
  font-size: 14px;
  font-weight: 600;
  color: #33383e;
}
.strength {
  width: 80px;
}
.select__box {
  display: flex;
  flex-wrap: wrap;
  max-height: 220px;
  overflow-y: auto;
  &__select-item {
    cursor: pointer;
    position: relative;
    height: 80px;
    width: 50%;
    margin: 4px 0;
    align-items: center;
    justify-content: center;
    display: flex;
  }
  &__select-item:hover {
    background: rgba(0, 0, 0, 0.07);
  }
}
.select__box ::-webkit-scrollbar {
  display: none; /* Chrome Safari */
}
.box__header {
  width: 100%;
  text-align: center;
  padding-bottom: 12px;
}
</style>

// src/components/modules/settings/EffectSelect/ContainerWrap.tsx
import { useEffect, useState } from 'react'
import api from '@/api'
import Button from '@/components/ui/Button'
import Image from '@/components/ui/Image'
import Popover from '@/components/ui/Popover'
import { wSvgSetting } from '@/components/modules/widgets/wSvg/wSvgSetting'
import './containerWrap.less'

type Props = {
  value?: string
  onChange?: (setting: Record<string, any>) => void
}

export default function ContainerWrap({ value, onChange }: Props) {
  const [visible, setVisible] = useState(false)
  const [type, setType] = useState('tuxing')
  const [list, setList] = useState<{ thumb: string; url: string }[]>([])

  useEffect(() => {
    let cancelled = false
    api.material.getList({ cate: 'mask' }).then((res) => {
      if (cancelled) return
      setList(res.list.map(({ thumb, url }) => ({ thumb, url })))
    })
    return () => {
      cancelled = true
    }
  }, [type])

  const select = (url: string = '') => {
    setVisible(false)
    const setting = JSON.parse(JSON.stringify(wSvgSetting))
    setting.svgUrl = url
    onChange?.(setting)
  }

  return (
    <div className="el-card is-hover-shadow box-card">
      <div className="el-card__header">
        <div className="card-header">
          <span className="title">Image mask</span>
          <Popover
            placement="bottom-end"
            popperClass="ds-mask-picker"
            width={260}
            open={visible}
            onOpenChange={setVisible}
            content={
              <>
                <div className="box__header">
                  <div className="el-radio-group">
                    <label className="el-radio-button is-active el-radio-button--small">
                      <input type="radio" className="el-radio-button__original-radio" checked readOnly onChange={() => setType('tuxing')} />
                      <span className="el-radio-button__inner">Shape</span>
                    </label>
                  </div>
                </div>
                <div className="select__box">
                  <div className="select__box__select-item" onClick={() => select()}>
                    None
                  </div>
                  {list.map((item, i) => (
                    <Image key={i + 'l'} className="select__box__select-item" src={item.thumb} fit="contain" onClick={() => select(item.url)} />
                  ))}
                </div>
              </>
            }
          >
            <Button className="button" link onClick={() => setVisible(!visible)}>
              {visible ? 'Cancel' : 'Choose'}
            </Button>
          </Popover>
        </div>
      </div>
      <div className="el-card__body" style={{ padding: 0 }} />
    </div>
  )
}
