// react/src/components/modules/settings/EffectSelect/TextWrap.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import api from '@/api'
import type { TGetCompListResult } from '@/api/home'
import Button from '@/components/ui/Button'
import Checkbox from '@/components/ui/Checkbox'
import Popover from '@/components/ui/Popover'
import { CollapseItem } from '@/components/ui/Collapse'
import SortableList from '@/components/ui/SortableList'
import getGradientOrImg from '../../widgets/wText/getGradientOrImg'
import ColorSelect, { type colorChangeData } from '../ColorSelect'
import NumberInput from '../NumberInput'
import NumberSlider from '../NumberSlider'
import { cx } from '@/utils/dom'
import './textWrap.less'

let frozeFontEffectList: TGetCompListResult[] = []

type Props = {
  value?: Record<string, any>[]
  data: Record<string, any>
  degree?: string | number
  onValueChange?: (value: Record<string, any>[]) => void
}

const coefficient = Math.round(160 / 27)

export default function TextWrap({ value, data = {}, onValueChange }: Props) {
  const [strength, setStrength] = useState(50)
  const [visible, setVisible] = useState(false)
  const [list, setList] = useState<TGetCompListResult[]>([])
  const [layers, setLayers] = useState<Record<string, any>[]>([])
  const [unfold, setUnfold] = useState(true)
  const [advancedOpen, setAdvancedOpen] = useState<string[]>([])
  const rawData = useRef<Record<string, any>[]>([])
  const emitting = useRef(false)
  const uuidRef = useRef(data.uuid)

  useEffect(() => {
    if (uuidRef.current === data.uuid && layers.length) return
    uuidRef.current = data.uuid
    if (!data.textEffects) {
      setLayers([])
      rawData.current = []
      return
    }
    const clone = (JSON.parse(JSON.stringify(data.textEffects)) || [])
      .map((x: any) => {
        x.uuid = String(Math.random())
        return x
      })
      .reverse()
    setLayers(clone)
    rawData.current = JSON.parse(JSON.stringify(clone))
  }, [data.uuid, data.textEffects])

  function pushLayers(next: Record<string, any>[]) {
    setLayers(next)
    emitting.current = true
    const newEffect = next.map((x) => {
      const copy = { ...x }
      delete copy.uuid
      return copy
    })
    onValueChange?.(newEffect.slice().reverse())
  }

  function strengthChange(x: number) {
    setStrength(x)
    const effectScale = 1 + (x - 50) / 50
    const next = layers.map((item, index) => {
      const copy = { ...item }
      if (copy.stroke && rawData.current[index]?.stroke) {
        copy.stroke = { ...copy.stroke, width: rawData.current[index].stroke.width * effectScale }
      }
      if (copy.shadow && rawData.current[index]?.shadow) {
        copy.shadow = { ...copy.shadow, blur: rawData.current[index].shadow.blur * effectScale }
      }
      return copy
    })
    pushLayers(next)
  }

  const selectEffect = async (id?: number) => {
    setVisible(false)
    if (id) {
      const { data: detail } = await api.home.getTempDetail({ id, type: 1 })
      const next = JSON.parse(detail)
        .textEffects.map((x: Record<string, any>) => {
          x.uuid = String(Math.random())
          return x
        })
        .reverse()
      rawData.current = JSON.parse(JSON.stringify(next))
      pushLayers(next)
    } else {
      rawData.current = []
      pushLayers([])
    }
  }

  const removeLayer = (i: number) => {
    const next = layers.slice()
    next.splice(i, 1)
    rawData.current = JSON.parse(JSON.stringify(next))
    pushLayers(next)
  }

  const addLayer = () => {
    const filling = { enable: false, type: 0, color: '#000000ff' }
    const stroke = { enable: false, width: 0, color: '#000000ff', type: 'outer' }
    const offset = { enable: false, x: 0, y: 0 }
    const shadow = { enable: false, color: '#000000ff', offsetX: 0, offsetY: 0, blur: 0, opacity: 0 }
    const next = [{ filling, stroke, shadow, offset, uuid: String(Math.random()) }, ...layers]
    rawData.current = JSON.parse(JSON.stringify(next))
    pushLayers(next)
  }

  const openSet = async () => {
    const next = !visible
    setVisible(next)
    if (!next) return
    if (frozeFontEffectList.length <= 0) {
      const { list: fetched } = await api.home.getCompList({ cate: 12, type: 1, pageSize: 30 })
      setList(fetched)
      frozeFontEffectList = fetched
    } else setList(frozeFontEffectList)
  }

  function patchLayer(index: number, patch: Record<string, any>) {
    const next = layers.slice()
    next[index] = { ...next[index], ...patch }
    pushLayers(next)
  }

  function colorChange(e: colorChangeData, index: number, key: string) {
    const modeStr: Record<string, number> = { Gradient: 2, Solid: 0 }
    const layer = layers[index]
    const feature = { ...layer[key], gradient: { angle: e.angle, stops: e.stops } }
    patchLayer(index, { [key]: feature })
    setTimeout(() => {
      setLayers((prev) => {
        const next = prev.slice()
        if (!next[index]) return prev
        next[index] = { ...next[index], [key]: { ...next[index][key], type: modeStr[e.mode] || 0 } }
        return next
      })
    }, 100)
  }

  const previewEffects = useMemo(() => value ?? [], [value])

  return (
    <div className="effects">
      <div className="effects__head">
        <span className="effects__title">Text effects</span>
        <div className="effects__head-right">
          <div
            className="effect-preview"
            style={{
              position: 'relative',
              width: '22px',
              fontSize: '22px',
              color: data.color,
              fontWeight: data.fontWeight,
              fontStyle: data.fontStyle,
              textDecoration: data.textDecoration,
              opacity: data.opacity,
              backgroundColor: data.backgroundColor,
            }}
          >
            {previewEffects.map((ef: any, efi: number) => (
              <div
                key={efi + 'effect'}
                style={{
                  color: ef.filling && ef.filling.enable && ef.filling.type === 0 ? ef.filling.color : 'transparent',
                  WebkitTextStroke: ef.stroke && ef.stroke.enable ? `${ef.stroke.width / coefficient}px ${ef.stroke.color}` : '',
                  textShadow:
                    ef.shadow && ef.shadow.enable
                      ? `${ef.shadow.offsetX / coefficient}px ${ef.shadow.offsetY / coefficient}px ${ef.shadow.blur / coefficient}px ${ef.shadow.color}`
                      : undefined,
                  backgroundImage: ef.filling && ef.filling.enable ? (ef.filling.type === 0 ? undefined : getGradientOrImg(ef)) : undefined,
                  WebkitBackgroundClip: ef.filling && ef.filling.enable ? (ef.filling.type === 0 ? undefined : 'text') : undefined,
                }}
                className="demo"
              >
                A
              </div>
            ))}
            A
          </div>
          <Popover
            placement="left"
            width={220}
            open={visible}
            onOpenChange={setVisible}
            content={
              <div className="select__box">
                <div className="select__box__select-item" onClick={() => selectEffect()}>
                  None
                </div>
                {list.map((l, li) => (
                  <div key={'list' + li} className="select__box__select-item" onClick={() => selectEffect(l.id)}>
                    <img src={l.cover} />
                  </div>
                ))}
              </div>
            }
          >
            <Button className="effects__choose" link onClick={openSet}>
              {visible ? 'Cancel' : 'Choose'}
            </Button>
          </Popover>
        </div>
      </div>

      <div style={{ display: layers.length > 0 ? undefined : 'none' }}>
        <NumberSlider
          value={strength}
          className="effects__intensity"
          style={{ marginTop: 10 }}
          label="Intensity"
          minValue={0}
          maxValue={100}
          onChange={strengthChange}
        />
      </div>

      <div className="advanced">
        <CollapseItem
          name="advanced"
          title="Advanced"
          active={advancedOpen.includes('advanced')}
          onToggle={() => setAdvancedOpen((prev) => (prev.includes('advanced') ? [] : ['advanced']))}
        >
          <div className="advanced__actions">
            <Button className="advanced__action" size="small" type="primary" link onClick={addLayer}>
              + Add effect
            </Button>
            {layers.length > 0 ? (
              <Button className="advanced__action" size="small" type="primary" link onClick={() => setUnfold(!unfold)}>
                {unfold ? 'Collapse all' : 'Expand all'}
              </Button>
            ) : null}
          </div>
          <SortableList
            className="layers"
            handle=".sd-yidong"
            items={layers}
            getKey={(item) => item.uuid}
            onReorder={pushLayers}
            renderItem={(element, index) => (
              <div className="layer">
                <div className="layer__title">
                  <i className="icon sd-yidong" />
                  <span className="layer__name">Effect {index + 1}</span>
                  <i className="icon sd-delete" onClick={() => removeLayer(index)} />
                </div>
                <div className="layer__body" style={{ display: unfold ? undefined : 'none' }}>
                  {element.filling && [0, 2, '0', '2'].includes(element.filling.type) ? (
                    <div className={cx('feature', { 'feature--off': !element.filling.enable })}>
                      <div className="feature__row">
                        <Checkbox
                          value={!!element.filling.enable}
                          label="Fill"
                          onChange={(next) => patchLayer(index, { filling: { ...element.filling, enable: next } })}
                        />
                        <ColorSelect
                          value={element.filling.color}
                          width="32px"
                          modes={['Solid', 'Gradient']}
                          label=""
                          onValueChange={(next) => patchLayer(index, { filling: { ...element.filling, color: next } })}
                          onChange={(e) => colorChange(e, index, 'filling')}
                        />
                      </div>
                    </div>
                  ) : null}
                  {element.stroke ? (
                    <div className={cx('feature', { 'feature--off': !element.stroke.enable })}>
                      <div className="feature__row">
                        <Checkbox
                          value={!!element.stroke.enable}
                          label="Outline"
                          onChange={(next) => patchLayer(index, { stroke: { ...element.stroke, enable: next } })}
                        />
                        <ColorSelect
                          value={element.stroke.color}
                          width="32px"
                          label=""
                          onValueChange={(next) => patchLayer(index, { stroke: { ...element.stroke, color: next } })}
                        />
                      </div>
                      <div className="feature__fields">
                        <label className="field">
                          <span className="field__label">Width</span>
                          <NumberInput
                            value={element.stroke.width}
                            minValue={0}
                            type="simple"
                            onChange={(next) => patchLayer(index, { stroke: { ...element.stroke, width: Number(next) } })}
                          />
                        </label>
                      </div>
                    </div>
                  ) : null}
                  {element.offset ? (
                    <div className={cx('feature', { 'feature--off': !element.offset.enable })}>
                      <div className="feature__row">
                        <Checkbox
                          value={!!element.offset.enable}
                          label="Offset"
                          onChange={(next) => patchLayer(index, { offset: { ...element.offset, enable: next } })}
                        />
                      </div>
                      <div className="feature__fields">
                        <label className="field">
                          <span className="field__label">X</span>
                          <NumberInput
                            value={element.offset.x}
                            type="simple"
                            onChange={(next) => patchLayer(index, { offset: { ...element.offset, x: Number(next) } })}
                          />
                        </label>
                        <label className="field">
                          <span className="field__label">Y</span>
                          <NumberInput
                            value={element.offset.y}
                            type="simple"
                            onChange={(next) => patchLayer(index, { offset: { ...element.offset, y: Number(next) } })}
                          />
                        </label>
                      </div>
                    </div>
                  ) : null}
                  {element.shadow ? (
                    <div className={cx('feature', { 'feature--off': !element.shadow.enable })}>
                      <div className="feature__row">
                        <Checkbox
                          value={!!element.shadow.enable}
                          label="Shadow"
                          onChange={(next) => patchLayer(index, { shadow: { ...element.shadow, enable: next } })}
                        />
                        <ColorSelect
                          value={element.shadow.color}
                          width="32px"
                          label=""
                          onValueChange={(next) => patchLayer(index, { shadow: { ...element.shadow, color: next } })}
                        />
                      </div>
                      <div className="feature__fields">
                        <label className="field field--full">
                          <span className="field__label">Blur</span>
                          <NumberInput
                            value={element.shadow.blur}
                            minValue={0}
                            type="simple"
                            onChange={(next) => patchLayer(index, { shadow: { ...element.shadow, blur: Number(next) } })}
                          />
                        </label>
                        <label className="field">
                          <span className="field__label">X</span>
                          <NumberInput
                            value={element.shadow.offsetX}
                            type="simple"
                            onChange={(next) => patchLayer(index, { shadow: { ...element.shadow, offsetX: Number(next) } })}
                          />
                        </label>
                        <label className="field">
                          <span className="field__label">Y</span>
                          <NumberInput
                            value={element.shadow.offsetY}
                            type="simple"
                            onChange={(next) => patchLayer(index, { shadow: { ...element.shadow, offsetY: Number(next) } })}
                          />
                        </label>
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            )}
          />
        </CollapseItem>
      </div>
    </div>
  )
}

// src/components/modules/settings/EffectSelect/TextWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-09 14:00:23
 * @Description: Text effects选择框组件
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-03-11 01:43:21
-->
<template>
  <el-card class="box-card" shadow="hover" :body-style="{ padding: '20px' }">
    <template #header>
      <div class="card-header">
        <div
          :style="{
            position: 'relative',
            width: '27px',
            fontSize: '27px',
            color: data.color,
            fontWeight: data.fontWeight,
            fontStyle: data.fontStyle,
            textDecoration: data.textDecoration,
            opacity: data.opacity,
            backgroundColor: data.backgroundColor,
          }"
        >
          <div
            v-for="(ef, efi) in modelValue"
            :key="efi + 'effect'"
            :style="{
              color: ef.filling && ef.filling.enable && ef.filling.type === 0 ? ef.filling.color : 'transparent',
              WebkitTextStroke: ef.stroke && ef.stroke.enable ? `${ef.stroke.width / coefficient}px ${ef.stroke.color}` : '',
              textShadow: ef.shadow && ef.shadow.enable ? `${ef.shadow.offsetX / coefficient}px ${ef.shadow.offsetY / coefficient}px ${ef.shadow.blur / coefficient}px ${ef.shadow.color}` : undefined,
              backgroundImage: ef.filling && ef.filling.enable ? (ef.filling.type === 0 ? undefined : getGradientOrImg(ef)) : undefined,
              WebkitBackgroundClip: ef.filling && ef.filling.enable ? (ef.filling.type === 0 ? undefined : 'text') : undefined,
            }"
            class="demo"
          >
            A
          </div>
          A
        </div>
        <span class="title">Text effects</span>
        <el-popover :visible="state.visiable" placement="left" :width="220" trigger="click">
          <div class="select__box">
            <div class="select__box__select-item" @click="selectEffect()">None</div>
            <div v-for="(l, li) in state.list" :key="'list' + li" class="select__box__select-item" @click="selectEffect(l.id)">
              <img :src="l.cover" />
            </div>
          </div>
          <template #reference>
            <el-button class="button" link @click="openSet">{{ state.visiable ? 'Cancel' : 'Choose' }}</el-button>
          </template>
        </el-popover>
      </div>
    </template>
    <!-- filling 描边 stroke 阴影 shadow -->
    <div v-show="state.layers && state.layers.length > 0" class="text item"><span style="width: 65px">Intensity</span> <el-slider v-model="state.strength" show-input :maxValue="100" input-size="small" :show-input-controls="false" @input="strengthChange"> </el-slider></div>
    <el-collapse-item>
      <template #title>
        <b>Advanced</b>
      </template>
      <div class="line"></div>
      <div style="display: flex; justify-content: space-between">
        <el-button
          class="add-layer" size="small" type="primary" link
          @click="addLayer">
           + Add effect
        </el-button>
        <el-button
          v-show="state.layers && state.layers.length > 0" class="add-layer" size="small"
          type="primary" link @click="state.unfold = !state.unfold">
          {{ state.unfold ? 'Collapse all' : 'Expand all' }}
        </el-button>
      </div>
      <div class="line"></div>
      <draggable v-model="state.layers" handle=".sd-yidong" item-key="uuid" v-bind="dragOptions">
        <template #item="{ element, index }">
          <div class="feature__grab-wrap">
            <div class="layer__title">
              <i class="icon sd-yidong" /><span style="font-size: 12px"><b>Effect</b> {{ index + 1 }}</span>
              <i class="icon sd-delete" @click="removeLayer(index)" />
            </div>
            <div v-if="element.filling && [0, 2, '0', '2'].includes(element.filling.type)" v-show="state.unfold" class="feature__item">
              <el-checkbox v-model="element.filling.enable" label="Fill" class="feature__header" />
              <color-select v-model="element.filling.color" width="28px" :modes="['Solid', 'Gradient']" label="" @change="colorChange($event, element.filling)" />
            </div>
            <div v-if="element.stroke" v-show="state.unfold" class="feature__item">
              <el-checkbox v-model="element.stroke.enable" label="Outline" class="feature__header" />
              <el-input-number v-model="element.stroke.width" style="width: 65px; margin-right: 0.5rem" :min="0" size="small" controls-position="right" />
              <color-select v-model="element.stroke.color" width="28px" label="" @finish="(value) => finish('color', value)" />
            </div>
            <div v-if="element.offset" v-show="state.unfold" class="feature__item">
              <el-checkbox v-model="element.offset.enable" label="Offset" class="feature__header" />
              <numberInput v-model="element.offset.x" style="width: 49.5px; margin-right: 2px" prepend="x" type="simple" />
              <numberInput v-model="element.offset.y" style="width: 49.5px" prepend="y" type="simple" />
            </div>
            <div v-if="element.shadow" v-show="state.unfold" class="feature__item">
              <el-checkbox v-model="element.shadow.enable" label="Shadow" class="feature__header" />
              <numberInput v-model="element.shadow.blur" prepend="blur" :minValue="0" style="width: 30px; margin-right: 2px" type="simple" />
              <numberInput v-model="element.shadow.offsetX" prepend="x" style="width: 30px; margin-right: 2px" type="simple" />
              <numberInput v-model="element.shadow.offsetY" prepend="y" style="width: 30px; margin-right: 0.5rem" type="simple" />
              <color-select v-model="element.shadow.color" width="28px" label="" @finish="(value) => finish('color', value)" />
            </div>
          </div>
        </template>
      </draggable>
    </el-collapse-item>
  </el-card>
</template>

<script lang="ts" setup>
import { 
  reactive, watch, onMounted, nextTick, computed
} from 'vue'
import colorSelect from '../colorSelect.vue'
import { ElInputNumber, ElCheckbox } from 'element-plus'
import numberInput from '../numberInput.vue'
import draggable from 'vuedraggable'
import api from '@/api'
import getGradientOrImg from '../../widgets/wText/getGradientOrImg'
import { TGetCompListResult } from '@/api/home'

let froze_font_effect_list: TGetCompListResult[] = []

type TProps = {
  modelValue?: Record<string, any>
  degree?: string | number
  data: Record<string, any>
}

type TEmits = {
  (event: 'update:modelValue', data: Record<string, any>[]): void
}

type TState = {
  strength: number
  visiable: boolean
  list: TGetCompListResult[]
  layers: Record<string, any>[]
  draging: boolean
  unfold: boolean
}

const props = withDefaults(defineProps<TProps>(), {
  modelValue: () => ({}),
  data: () => ({})
})

const emit = defineEmits<TEmits>()

const state = reactive<TState>({
  strength: 50, // Intensity
  visiable: false, // Layer picker popover
  list: [],
  layers: [],
  draging: false,
  unfold: true,
})

const dragOptions = {
  animation: 300,
  ghostClass: 'ghost',
  chosenClass: 'choose',
}
const coefficient = computed(() => Math.round(160 / 27))
let rawData: Record<string, any>[] = [] // Initial values, used when changing intensity

onMounted(async () => {
  await nextTick()
  // console.log(props.data)
  if (!props.data.textEffects) {
    return
  }
  const clone = JSON.parse(JSON.stringify(props.data.textEffects)) || []
  state.layers = clone
    .map((x: any) => {
      x.uuid = String(Math.random())
      return x
    })
    .reverse()
  rawData = JSON.parse(JSON.stringify(state.layers))
})

watch(
  () => state.layers,
  (v) => {
    const newEffect = v.map((x) => {
      delete x.uuid
      return x
    })
    emit('update:modelValue', newEffect.reverse())
  },
  { deep: true },
)

// 选中加载特效预设
const selectEffect = async (id?: number) => {
  state.visiable = false
  if (id) {
    const { data } = await api.home.getTempDetail({ id, type: 1 })
    state.layers = JSON.parse(data)
      .textEffects.map((x: Record<string, any>) => {
        x.uuid = String(Math.random())
        return x
      })
      .reverse()
  } else state.layers = []
}

// 删除效果层
const removeLayer = (i: number) => {
  state.layers.splice(i, 1)
  rawData = JSON.parse(JSON.stringify(state.layers))
}

// 添加效果层
const addLayer = () => {
  const filling = { enable: false, type: 0, color: '#000000ff' }
  const stroke = { enable: false, width: 0, color: '#000000ff', type: 'outer' }
  const offset = { enable: false, x: 0, y: 0 }
  const shadow = { enable: false, color: '#000000ff', offsetX: 0, offsetY: 0, blur: 0, opacity: 0 }
  state.layers.unshift({ filling, stroke, shadow, offset, uuid: String(Math.random()) })
  rawData = JSON.parse(JSON.stringify(state.layers))
}

const finish = (type?: string, value?: string) => {}

const colorChange = (e: Record<string, any>, item: Record<string, any>) => {
  const modeStr: Record<string, number> = {
    Gradient: 2,
    Solid: 0,
  }
  item.gradient = {
    angle: e.angle,
    stops: e.stops,
  }
  setTimeout(() => {
    item.type = modeStr[e.mode] || 0
  }, 100)
}

    // const onMove = ({ relatedContext, draggedContext }: any) => {
    //   const relatedElement = relatedContext.element
    //   const draggedElement = draggedContext.element
    //   return (!relatedElement || relatedElement.parent == -1) && draggedElement.parent == -1
    // }
    const onDone = () => {
      state.draging = false
    }

    const strengthChange = (x: any) => {
      const effectScale = 1 + (x - 50) / 50
      state.layers.forEach((item: any, index) => {
        if (item.stroke) {
          item.stroke.width = rawData[index].stroke.width * effectScale
        }
        if (item.shadow) {
          item.shadow.blur = rawData[index].shadow.blur * effectScale
        }
      })
    }

// 打开特效字体集
const openSet = async () => {
  state.visiable = !state.visiable
  if (froze_font_effect_list.length <= 0) {
    const { list } = await api.home.getCompList({
      cate: 12,
      type: 1,
      pageSize: 30,
    })
    state.list = list
    froze_font_effect_list = list
  } else state.list = froze_font_effect_list
}

defineExpose({
  selectEffect,
  finish,
  coefficient,
  removeLayer,
  addLayer,
  dragOptions,
  onDone,
  strengthChange,
  openSet,
  colorChange,
  getGradientOrImg,
})
</script>

<style lang="less" scoped>
:deep(.el-input-group__prepend) {
  padding: 0 8px;
}
:deep(.el-input-number__decrease) {
  width: 18px;
}
:deep(.el-input-number__increase) {
  width: 18px;
}
:deep(.el-input-number.is-controls-right .el-input__wrapper) {
  padding-right: 32px;
}
:deep(.el-input-group__prepend) {
  background: #ffffff;
}
:deep(.el-checkbox__input.is-checked + .el-checkbox__label) {
  color: #333333;
}
:deep(.el-collapse-item__header) {
  border-bottom: none;
}
:deep(.el-collapse-item__wrap) {
  border-bottom: none;
}
.feature {
  &__item {
    display: flex;
    align-items: center;
    margin-top: 6px;
  }
  &__header {
    font-size: 14px;
    flex: 1;
    padding: 12px 0 2px 0;
    color: #333333;
  }
  &__header:first-of-type {
    padding: 0 0 2px 0;
  }
  &__grab-wrap {
    position: relative;
    padding: 10px 0;
  }
  &__grab-wrap:first-of-type {
    padding-top: 0;
  }
  &__grab-wrap:last-of-type {
    padding-bottom: 0;
  }
  &__wrap {
    position: relative;
    padding-top: 32px;
  }
  &__wrap::after {
    position: absolute;
    content: '';
    height: 1px;
    width: 100%;
    background: #e9e9e9;
    top: 16px;
  }
  &__wrap:first-of-type {
    padding: 0;
  }
  &__wrap:first-of-type::after {
    height: 0;
  }
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.text {
  font-size: 14px;
}

.item {
  margin: 0 0 12px 0;
  display: flex;
  align-items: center;
}

.box-card {
  width: 100%;
}

.demo {
  font-size: 27px;
  color: #ffffff;
  outline: none;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
.title {
  font-size: 14px;
  font-weight: 600;
  color: #33383e;
}
.select__box {
  display: flex;
  flex-wrap: wrap;
  // height: 60px;
  &__select-item {
    cursor: pointer;
    position: relative;
    height: 40px;
    width: 33%;
    align-items: center;
    justify-content: center;
    display: flex;
  }
  &__select-item:hover {
    background: rgba(0, 0, 0, 0.07);
  }
}

.layer {
  &__title {
    display: flex;
    align-items: center;
    span {
      flex: 1;
    }
    .sd-yidong {
      cursor: grab !important;
      margin-right: 6px;
    }
    .icon {
      // display: none;
      cursor: pointer;
    }
    .icon:hover {
      transform: scale(1.1);
      color: @active-text-color;
    }
  }
  // &__title:hover > .icon {
  //   display: block;
  // }
}

.add-layer {
  // margin-top: 12px;
  margin-bottom: 10px;
  // width: 100%;
}

// dragable
.choose {
  border: 1px dashed #999999 !important;
}

.flip-list-move {
  transition: transform 0.5s;
}

.no-move {
  transition: transform 0s;
}
.disable {
  opacity: 0.3;
}
.ghost {
  opacity: 0.3;
  background: @main-color;
}
.line {
  margin-top: 8px;
  height: 18px;
  border-top: 1px solid #e9e9e9;
}
</style>
