// src/components/modules/panel/wrap/BgImgListWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-27 15:16:07
 * @Description: 背景图
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-08-12 09:49:35
-->
<template>
  <div class="wrap">
    <div class="color__box" :style="modelStyle.color">
      <div v-for="c in state.colors" :key="c" :style="{ background: c }" class="color__item" @click="setBGcolor(c)"></div>
    </div>
    <ul v-if="state.showList" v-infinite-scroll="loadData" class="infinite-list" :infinite-scroll-distance="150" style="overflow: auto">
      <div class="list" :style="modelStyle.list">
        <imageTip v-for="(item, i) in state.bgList" :key="i + 'i'" :detail="item">
          <el-image class="list__img" :src="item.thumb" fit="cover" lazy loading="lazy" @click.stop="selectItem(item)" @dragstart="dragStart($event, item)"></el-image>
        </imageTip>
      </div>
      <div v-show="state.loading" class="loading"><i class="el-icon-loading"></i> Loading</div>
      <div v-show="state.loadDone" class="loading">That is everything</div>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { reactive, computed } from 'vue'
import api from '@/api'

import { ElImage } from 'element-plus'
import { TGetImageListResult } from '@/api/material';
import { useCanvasStore, useWidgetStore } from '@/store';

type TCommonPanelData = {
  color: string
  list: string
}

type TTmpModalData = {
  widgetPanel: TCommonPanelData
  stylePanel: TCommonPanelData
}

type TProps = {
  model: 'widgetPanel'
}

type TState = {
  loading: boolean
  loadDone: boolean
  bgList: TGetImageListResult[]
  showList: boolean
  colors: string[]
}

const { model } = defineProps<TProps>()

const pageStore = useCanvasStore()
const widgetStore = useWidgetStore()

const state = reactive<TState>({
  loading: false,
  loadDone: false,
  bgList: [],
  showList: true,
  colors: ['#000000ff', '#999999ff', '#CCCCCCff', '#FFFFFFff', '#E65353ff', '#FFD835ff', '#70BC59ff', '#607AF4ff', '#976BEEff'],
})

// 临时用于改变样式
const models: TTmpModalData = {
  widgetPanel: {
    color: 'padding: 1.2rem 1rem',
    list: 'grid-template-columns: auto auto auto;padding: 0 1rem;',
  },
  stylePanel: {
    color: 'padding: 1.2rem 0;',
    list: 'grid-template-columns: repeat(3, 76px);',
  }
}

const modelStyle = computed(() => models[model])

const pageOptions = { page: 0, pageSize: 20 }

const loadData = () => {
  if (state.loading) {
    return
  }
  load()
}

const load = async (init: boolean = false) => {
  if (state.loadDone) {
    return
  }
  state.loading = true
  pageOptions.page += 1

  if (init) {
    state.bgList = []
    pageOptions.page = 1
  }

  await api.material.getImagesList({ cate: 3, page: pageOptions.page }).then(({ list }) => {
    if (list.length > 0) {
      state.bgList.push(...list)
    } else {
      state.loadDone = true
    }
  })

  setTimeout(() => {
    state.loading = false
  }, 100)
}

function setBGcolor(color: string) {
  pageStore.updatePageData({
    key: "backgroundImage",
    value: ''
  })
  pageStore.updatePageData({
    key: 'backgroundColor',
    value: color
  })
  widgetStore.selectWidget({
    uuid: '-1'
  })
  // store.dispatch('selectWidget', {
  //   uuid: '-1',
  // })
}

async function selectItem(item: TGetImageListResult) {
  // this.$store.commit('setShowMoveable', false) // Clear the previous selection
  pageStore.updatePageData({
    key: 'backgroundTransform',
    value: {},
  })
  pageStore.updatePageData({
    key: 'backgroundImage',
    value: item.url
  })
  widgetStore.selectWidget({
    uuid: '-1'
  })
  // store.dispatch('selectWidget', {
  //   uuid: '-1',
  // })
}

function dragStart(_: MouseEvent, _item: TGetImageListResult) {
  widgetStore.setSelectItem({ data: {}, type: 'bg' })
  // store.commit('selectItem', { data: {}, type: 'bg' })
}


defineExpose({
  load,
  setBGcolor,
  loadData,
  modelStyle
})

</script>

<style lang="less" scoped>
.wrap {
  width: 100%;
  height: 100%;
}

.infinite-list {
  // margin-right: 0.4rem;
  height: 100%;
  padding-bottom: 150px;
  // scrollbar-width: none; /* Firefox */
  // -ms-overflow-style: none; /* IE 10+ */
}
// .infinite-list::-webkit-scrollbar {
//   display: none; /* Chrome Safari */
// }
.list {
  width: 100%;
  display: grid;
  grid-gap: 5px;
  &__img {
    cursor: pointer;
    width: 100%;
    height: 92px;
    border-radius: 4px;
  }
  &__img:hover::before {
    content: ' ';
    background: rgba(0, 0, 0, 0.1);
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
    pointer-events: none;
  }
}

.loading {
  padding-top: 1rem;
  text-align: center;
  font-size: 14px;
  color: #999;
}

.color {
  &__box {
    display: flex;
    flex-wrap: wrap;
  }
  &__item {
    border: 1px solid rgba(0, 0, 0, 0.08);
    margin: 2.8px;
    width: 43px;
    height: 36px;
    border-radius: 2px;
    cursor: pointer;
  }
}
</style>

// src/components/modules/panel/wrap/BgImgListWrap.tsx
import { useCallback, useRef, useState } from 'react'
import api from '@/api'
import type { TGetImageListResult } from '@/api/material'
import useInfiniteScroll from '@/common/hooks/useInfiniteScroll'
import Image from '@/components/ui/Image'
import { updatePageData } from '@/store/canvas'
import { selectWidget, setSelectItem } from '@/store/widget'
import ImageTip from './components/ImageTip'
import { PHOTO_NOTICES } from './components/photoNotices'
import SearchHeader from './components/SearchHeader'
import './bgImgListWrap.less'

type TProps = {
  model: 'widgetPanel' | 'stylePanel'
  style?: React.CSSProperties
}

const models = {
  widgetPanel: {
    color: { padding: '1.2rem 1rem' },
    list: { gridTemplateColumns: 'auto auto auto', padding: '0 1rem' },
  },
  stylePanel: {
    color: { padding: '1.2rem 0' },
    list: { gridTemplateColumns: 'repeat(3, 76px)' },
  },
} as const

const COLORS = ['#000000ff', '#999999ff', '#CCCCCCff', '#FFFFFFff', '#E65353ff', '#FFD835ff', '#70BC59ff', '#607AF4ff', '#976BEEff']

/** The stored search behind the browse list: textures and abstract backgrounds. */
const BACKGROUND_CATE = 2
const PAGE_SIZE = 20

export default function BgImgListWrap({ model, style }: TProps) {
  const [loading, setLoading] = useState(false)
  const [loadDone, setLoadDone] = useState(false)
  const [notice, setNotice] = useState('')
  const [keyword, setKeyword] = useState('')
  const [bgList, setBgList] = useState<TGetImageListResult[]>([])
  const listRef = useRef<HTMLUListElement | null>(null)
  const loadingRef = useRef(false)
  const doneRef = useRef(false)
  const keywordRef = useRef('')
  const page = useRef(0)
  // Bumped whenever the list starts over, so a page that arrives late for a
  // search the user has already moved on from is dropped instead of appended.
  const runId = useRef(0)

  const modelStyle = models[model]

  const load = useCallback(async () => {
    if (doneRef.current || loadingRef.current) {
      return
    }
    loadingRef.current = true
    setLoading(true)
    page.current += 1
    const run = runId.current
    const asked = keywordRef.current

    const { list = [], error } = await api.material.getImagesList({
      cate: BACKGROUND_CATE,
      keyword: asked || undefined,
      page: page.current,
      pageSize: PAGE_SIZE,
    })

    if (run !== runId.current) {
      return
    }

    if (error) {
      setNotice(PHOTO_NOTICES[error])
      doneRef.current = true
      setLoadDone(true)
    } else if (list.length > 0) {
      setBgList((prev) => prev.concat(list))
    } else {
      doneRef.current = true
      setLoadDone(true)
      if (page.current === 1) {
        setNotice(asked ? `No backgrounds match “${asked}”. Try a broader word.` : 'No backgrounds here yet.')
      }
    }

    setLoading(false)
    // Held briefly so the scroll that triggered this load cannot immediately
    // ask for the next page before the one just added has been laid out.
    setTimeout(() => {
      if (run === runId.current) loadingRef.current = false
    }, 100)
  }, [])

  const loadData = useCallback(() => {
    if (loadingRef.current) {
      return
    }
    load()
  }, [load])

  useInfiniteScroll(listRef, loadData)

  const search = useCallback(
    (next: string) => {
      const trimmed = next.trim()
      if (trimmed === keywordRef.current) {
        return
      }
      runId.current += 1
      keywordRef.current = trimmed
      page.current = 0
      doneRef.current = false
      loadingRef.current = false
      setKeyword(trimmed)
      setBgList([])
      setLoadDone(false)
      setNotice('')
      setLoading(false)
      listRef.current?.scrollTo({ top: 0 })
      load()
    },
    [load],
  )

  // Effects run twice in development, and this one spends a request, so it is
  // started from the first render instead and guarded by a ref that survives.
  const started = useRef(false)
  if (!started.current) {
    started.current = true
    load()
  }

  function setBGcolor(color: string) {
    updatePageData({ key: 'backgroundImage', value: '' })
    updatePageData({ key: 'backgroundColor', value: color })
    selectWidget({ uuid: '-1' })
  }

  async function selectItem(item: TGetImageListResult) {
    // A new picture starts centred, uncropped-as-far-as-it-can-be. Its shape is
    // kept so the position control can zoom past the size that covers the page.
    updatePageData({ key: 'backgroundTransform', value: item.width && item.height ? { ratio: item.width / item.height } : {} })
    updatePageData({ key: 'backgroundImage', value: item.url })
    selectWidget({ uuid: '-1' })
    api.material.trackImageUse(item.downloadLocation)
  }

  function dragStart() {
    setSelectItem({ data: {}, type: 'bg' })
  }

  return (
    <div className="wrap bg-img-list-wrap" style={style}>
      <SearchHeader type="none" placeholder="Search backgrounds" onSearch={search} />
      {!keyword ? (
        <div className="color__box" style={modelStyle.color}>
          {COLORS.map((c) => (
            <div key={c} style={{ background: c }} className="color__item" onClick={() => setBGcolor(c)} />
          ))}
        </div>
      ) : (
        <div className="search__summary">Backgrounds for “{keyword}”</div>
      )}
      <ul ref={listRef} className="infinite-list" style={{ overflow: 'auto' }}>
        {notice ? <p className="notice">{notice}</p> : null}
        <div className="list" style={modelStyle.list}>
          {bgList.map((item, i) => (
            <ImageTip key={i + 'i'} detail={item as any}>
              <Image
                className="list__img"
                src={item.thumb}
                fit="cover"
                lazy
                onClick={(e) => {
                  e.stopPropagation()
                  selectItem(item)
                }}
              />
            </ImageTip>
          ))}
        </div>
        {loading ? (
          <div className="loading">
            <i className="el-icon-loading" /> Loading
          </div>
        ) : null}
        {loadDone && bgList.length > 0 ? <div className="loading">That is everything</div> : null}
      </ul>
    </div>
  )
}
