// src/components/modules/panel/wrap/CompListWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-27 15:16:07
 * @Description: 素材列表，主要用于文字组合列表
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-08-14 18:49:06
-->
<template>
  <div class="wrap">
    <!-- <div class="search__wrap">
      <el-input v-model="searchValue" placeholder="Search" class="input-with-select">
        <template #append>
          <el-button><i class="iconfont icon-search"></i></el-button>
        </template>
      </el-input>
    </div>
    <el-divider content-position="left">Suggested elements</el-divider> -->
    <classHeader v-show="!state.currentCategory" :types="state.types" @select="selectTypes">
      <template v-slot="{ index }">
        <div class="list-wrap">
          <div v-for="(item, i) in state.showList[index]" :key="i + 'sl'" draggable="false" @mousedown="dragStart($event, item)" @mousemove="mousemove" @mouseup="mouseup" @click.stop="selectItem(item)" @dragstart.prevent>
            <el-image class="list__img-thumb" :src="item.cover" fit="contain" lazy loading="lazy"></el-image>
          </div>
        </div>
      </template>
    </classHeader>

    <ul v-if="state.currentCategory" v-infinite-scroll="load" class="infinite-list" :infinite-scroll-distance="150" style="overflow: auto">
      <classHeader :is-back="true" @back="back">{{ state.currentCategory.name }}</classHeader>
      <el-space fill wrap :fillRatio="30" direction="horizontal" class="list">
        <div v-for="(item, i) in state.list" :key="i + 'i'" class="list__item" draggable="false" @mousedown="dragStart($event, item)" @mousemove="mousemove" @mouseup="mouseup" @click.stop="selectItem(item)" @dragstart.prevent>
          <!-- <edit-model :isComp="true" @action="action($event, item, i)"> -->
          <el-image class="list__img" :src="item.cover" fit="contain" lazy loading="lazy" />
          <!-- </edit-model> -->
        </div>
      </el-space>
      <div v-show="state.loading" class="loading"><i class="el-icon-loading"></i> Loading</div>
      <div v-show="state.loadDone" class="loading">That is everything</div>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { reactive, onMounted } from 'vue'
import api from '@/api'
import getComponentsData from '@/common/methods/DesignFeatures/setComponents'
import DragHelper from '@/common/hooks/dragHelper'
import setItem2Data from '@/common/methods/DesignFeatures/setImage'
import { TGetCompListResult, TGetTempDetail, TTempDetail } from '@/api/home'
import { useControlStore, useCanvasStore, useWidgetStore } from '@/store'

type TState = {
  loading: boolean
  loadDone: boolean
  list: TGetCompListResult[]
  searchValue: string
  currentCategory: TGetCompListResult | null
  types: { cate: string; name: string }[]
  showList: TGetCompListResult[][]
}

// 拖拽效果相关
const dragHelper = new DragHelper()
let isDrag = false
let startPoint = { x: 99999, y: 99999 }
let tempDetail: TTempDetail | null = null
// 缓存组件用以减少接口请求的次数
const compsCache: any = {}
const state = reactive<TState>({
  loading: false,
  loadDone: false,
  list: [],
  searchValue: '',
  currentCategory: null,
  types: [],
  showList: [],
})

const controlStore = useControlStore()
const widgetStore = useWidgetStore()
const dPage = useCanvasStore().dPage
const pageOptions = { type: 1, page: 0, pageSize: 20 }

onMounted(async () => {
  if (state.types.length <= 0) {
    // const types = await api.material.getKinds({ type: 3 })
    state.types = [
      { cate: 'text', name: 'Text with effects' },
      { cate: 'comp', name: 'Sample element groups' },
    ]
    for (const iterator of state.types) {
      const { list } = await api.home.getCompList({
        type: 1,
        cate: iterator.cate,
      })
      state.showList.push(list)
    }
  }
})
const mouseup = (e: MouseEvent) => {
  e.preventDefault()
  // setTimeout(() => {
  isDrag = false
  tempDetail = null
  startPoint = { x: 99999, y: 99999 }
  // }, 10)
}

const mousemove = (e: MouseEvent) => {
  e.preventDefault()
  // startPoint only holds a real position between mousedown and mouseup. Without
  // this the move that carries the pointer onto a thumbnail is measured against
  // the sentinel, reads as a drag of ninety-nine thousand pixels, and the click
  // that follows is thrown away as the end of one.
  if (startPoint.x === 99999) return
  if (Math.abs(e.x - startPoint.x) > 2 || Math.abs(e.y - startPoint.y) > 2) {
    isDrag = true
  }
}

const load = async (init: boolean = false) => {
  if (init) {
    state.list = []
    pageOptions.page = 0
    state.loadDone = false
  }

  if (state.loadDone || state.loading) {
    return
  }

  state.loading = true
  pageOptions.page += 1

  const res = await api.home.getCompList({
    ...pageOptions,
    cate: state.currentCategory?.id || state.currentCategory?.cate,
  })
  if (init) {
    state.list = res?.list
  } else {
    res?.list.length <= 0 && (state.loadDone = true)
    state.list = state.list.concat(res?.list)
  }
  setTimeout(() => {
    state.loading = false
  }, 100)
}

type TActionParam = {
  name: string
  value: string
}

function action({ name, value }: TActionParam, item: TGetCompListResult, index: number) {
  switch (name) {
    case 'del':
      delComp(item, index)
      break
  }
}

function delComp({ id }: TGetCompListResult, index: number) {
  api.home.removeComp({ id })
  state.list.splice(index, 1)
}

const selectTypes = (item: TGetCompListResult) => {
  state.currentCategory = item
  load(true)
}

const back = () => {
  state.currentCategory = null
}

const dragStart = async (e: MouseEvent, { id, width, height, cover }: TGetCompListResult) => {
  // Stop the browser starting its own image drag on the thumbnail: while a
  // native drag is running it swallows mousemove and mouseup, so the piece
  // being dragged sits frozen until the button is released.
  e.preventDefault()
  startPoint = { x: e.x, y: e.y }
  // tempDetail = await api.home.getTempDetail({ id, type: 1 })
  // let finalWidth = tempDetail.width
  // 计算出拖拽到画布数值
  const img = await setItem2Data({ width, height, url: cover })
  dragHelper.start(e, img.canvasWidth)
  tempDetail = await getCompDetail({ id, type: 1 })
  if (Array.isArray(JSON.parse(tempDetail.data))) {
    widgetStore.setSelectItem({ data: JSON.parse(tempDetail.data), type: 'group' })
    // store.commit('selectItem', { data: JSON.parse(tempDetail.data), type: 'group' })
  } else {
    widgetStore.setSelectItem({ data: JSON.parse(tempDetail.data), type: 'text' })
    // store.commit('selectItem', { data: JSON.parse(tempDetail.data), type: 'text' })
  }
}

const selectItem = async (item: TGetCompListResult) => {
  if (isDrag) {
    return
  }
  // store.commit('setShowMoveable', false) // Clear the previous selection
  controlStore.setShowMoveable(false) // Clear the previous selection

  tempDetail = tempDetail || (await getCompDetail({ id: item.id, type: 1 }))
  // let group = JSON.parse(tempDetail.data)
  const group: any = await getComponentsData(tempDetail.data)
  let parent: Record<string, any> = { x: 0, y: 0 }
  const { width: pW, height: pH } = dPage

  Array.isArray(group) &&
    group.forEach((element) => {
      element.type === 'w-group' && (parent = element)
    })
  if (parent.isContainer) {
    group.forEach((element: any) => {
      element.left += (pW - parent.width) / 2
      element.top += (pH - parent.height) / 2
    })
    widgetStore.addGroup(group)
    // store.dispatch('addGroup', group)
  } else {
    group.text && (group.text = decodeURIComponent(group.text))
    group.left = pW / 2 - group.fontSize * (group.text.length / 2)
    group.top = pH / 2 - group.fontSize / 2
    widgetStore.addWidget(group)
    // store.dispatch('addWidget', group)
  }
}

function getCompDetail(params: TGetTempDetail): Promise<TTempDetail> {
  // 有缓存则直接返回组件数据，否则请求获取数据
  return new Promise((resolve) => {
    if (compsCache[params.id]) {
      resolve(compsCache[params.id])
    } else
      api.home.getTempDetail(params).then((res: any) => {
        resolve(res)
        compsCache[params.id] = res // Cache the fetched element data
      })
  })
}

defineExpose({
  load,
  action,
  back,
  selectTypes,
  mouseup,
  mousemove,
  dragStart,
  selectItem,
})
</script>

<style lang="less" scoped>
// The backing tile for panel artwork. Themed, but locally: a column of white
// cards is a slab of glare on a dark panel, and it drowns out the samples it
// is meant to present. The covers are transparent PNGs (see
// tools/make-sample-covers.mjs), so whichever tile is in force shows through
// them. Held as a custom property rather than a Less literal because Less
// resolves at build time and this has to follow the runtime theme switch.
// Mirrors GraphListWrap.
@art-tile: var(--art-tile);
@art-tile-hover: var(--art-tile-hover);
.wrap {
  --art-tile: #f3f8fa;
  --art-tile-hover: #e6eef2;
  width: 100%;
  height: 100%;
}

html.dark .wrap {
  --art-tile: hsl(0 0% 15%);
  --art-tile-hover: hsl(0 0% 21%);
}

.search__wrap {
  padding: 1.4rem 1rem 0.8rem 1rem;
}

.infinite-list {
  height: 100%;
  padding-bottom: 150px;
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* IE 10+ */
}
.infinite-list::-webkit-scrollbar {
  display: none; /* Chrome Safari */
}
.list {
  width: 100%;
  // padding: 20px 0 0 10px;
  padding: 3.1rem 0 0 1rem;
  gap: 0 !important;
  &__item {
    overflow: hidden;
    background: @art-tile;
    margin-bottom: 8px;
    margin-right: 8px;
  }
  &__img {
    cursor: grab;
    width: 142px;
    height: 142px;
    padding: 4px;
    border-radius: 4px;
  }
  &__img-thumb {
    cursor: grab;
    width: 90px;
    height: 90px;
    background: @art-tile;
    padding: 4px;
    border-radius: 4px;
  }
  // A solid step darker, not a translucent black wash. A wash only reads as
  // "slightly darker" while the light tile is underneath it; on a dark panel
  // it replaces the tile and the sample loses its backing mid-hover.
  &__img:hover,
  &__img-thumb:hover {
    background: @art-tile-hover;
  }
}

.loading {
  padding-top: 1rem;
  text-align: center;
  font-size: 14px;
  color: @ink-3;
}
.list-wrap {
  display: flex;
  justify-content: space-between;
  margin-bottom: 1.8rem;
}
</style>

// src/components/modules/panel/wrap/CompListWrap.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import api from '@/api'
import type { TGetCompListResult, TGetTempDetail, TTempDetail } from '@/api/home'
import getComponentsData from '@/common/methods/DesignFeatures/setComponents'
import setItem2Data from '@/common/methods/DesignFeatures/setImage'
import DragHelper from '@/common/hooks/dragHelper'
import useInfiniteScroll from '@/common/hooks/useInfiniteScroll'
import Image from '@/components/ui/Image'
import Space from '@/components/ui/Space'
import { canvasState } from '@/store/state'
import { setShowMoveable } from '@/store/control'
import { addGroup, addWidget, setSelectItem } from '@/store/widget'
import { decodeText } from '@/store/widget/template'
import { brandResolver } from '@/common/methods/brandKit'
import { fillWidget } from '@/utils/mergeFields'
import ClassHeader from './components/ClassHeader'
import './compListWrap.less'

const dragHelper = new DragHelper()
const compsCache: any = {}

export default function CompListWrap() {
  const [loading, setLoading] = useState(false)
  const [loadDone, setLoadDone] = useState(false)
  const [list, setList] = useState<TGetCompListResult[]>([])
  const [currentCategory, setCurrentCategory] = useState<any>(null)
  const [types, setTypes] = useState<{ cate: string; name: string }[]>([])
  const [showList, setShowList] = useState<TGetCompListResult[][]>([])
  const listRef = useRef<HTMLUListElement | null>(null)

  const isDrag = useRef(false)
  const startPoint = useRef({ x: 99999, y: 99999 })
  const tempDetail = useRef<TTempDetail | null>(null)
  const loadingRef = useRef(false)
  const doneRef = useRef(false)
  const categoryRef = useRef<any>(null)
  const pageOptions = useRef({ type: 1, page: 0, pageSize: 20 })

  useEffect(() => {
    let cancelled = false
    const nextTypes = [
      { cate: 'text', name: 'Text with effects' },
      { cate: 'comp', name: 'Sample element groups' },
    ]
    setTypes(nextTypes)
    ;(async () => {
      const collected: TGetCompListResult[][] = []
      for (const iterator of nextTypes) {
        const { list: items } = await api.home.getCompList({ type: 1, cate: iterator.cate })
        collected.push(items)
      }
      if (!cancelled) setShowList(collected)
    })()
    return () => {
      cancelled = true
    }
  }, [])

  const mouseup = (e: React.MouseEvent) => {
    e.preventDefault()
    isDrag.current = false
    tempDetail.current = null
    startPoint.current = { x: 99999, y: 99999 }
  }

  const mousemove = (e: React.MouseEvent) => {
    e.preventDefault()
    // startPoint only holds a real position between mousedown and mouseup. Without
    // this the move that carries the pointer onto a thumbnail is measured against
    // the sentinel, reads as a drag of ninety-nine thousand pixels, and the click
    // that follows is thrown away as the end of one.
    if (startPoint.current.x === 99999) return
    if (Math.abs(e.clientX - startPoint.current.x) > 2 || Math.abs(e.clientY - startPoint.current.y) > 2) {
      isDrag.current = true
    }
  }

  const load = useCallback(async (init: boolean = false) => {
    if (init) {
      setList([])
      pageOptions.current.page = 0
      doneRef.current = false
      setLoadDone(false)
    }

    if (doneRef.current || loadingRef.current) {
      return
    }

    loadingRef.current = true
    setLoading(true)
    pageOptions.current.page += 1

    const res = await api.home.getCompList({
      ...pageOptions.current,
      cate: categoryRef.current?.id || categoryRef.current?.cate,
    })
    if (init) {
      setList(res?.list)
    } else {
      if (res?.list.length <= 0) {
        doneRef.current = true
        setLoadDone(true)
      }
      setList((prev) => prev.concat(res?.list))
    }
    setTimeout(() => {
      loadingRef.current = false
      setLoading(false)
    }, 100)
  }, [])

  useInfiniteScroll(listRef, load, 150, !!currentCategory)

  const selectTypes = (item: any) => {
    categoryRef.current = item
    setCurrentCategory(item)
    load(true)
  }

  const back = () => {
    categoryRef.current = null
    setCurrentCategory(null)
  }

  const dragStart = async (e: React.MouseEvent, { id, width, height, cover }: TGetCompListResult) => {
    // Stop the browser starting its own image drag on the thumbnail: while a
    // native drag is running it swallows mousemove and mouseup, so the piece
    // being dragged sits frozen until the button is released.
    e.preventDefault()
    startPoint.current = { x: e.clientX, y: e.clientY }
    const img = await setItem2Data({ width, height, url: cover })
    dragHelper.start(e.nativeEvent, img.canvasWidth)
    tempDetail.current = await getCompDetail({ id, type: 1 })
    if (Array.isArray(JSON.parse(tempDetail.current.data))) {
      setSelectItem({ data: JSON.parse(tempDetail.current.data), type: 'group' })
    } else {
      setSelectItem({ data: JSON.parse(tempDetail.current.data), type: 'text' })
    }
  }

  const selectItem = async (item: TGetCompListResult) => {
    if (isDrag.current) {
      return
    }
    setShowMoveable(false)

    tempDetail.current = tempDetail.current || (await getCompDetail({ id: item.id, type: 1 }))
    const group: any = await getComponentsData(tempDetail.current.data)
    let parent: Record<string, any> = { x: 0, y: 0 }
    const { width: pW, height: pH } = canvasState.dPage

    Array.isArray(group) &&
      group.forEach((element: any) => {
        element.type === 'w-group' && (parent = element)
      })
    if (parent.isContainer) {
      group.forEach((element: any) => {
        element.left += (pW - parent.width) / 2
        element.top += (pH - parent.height) / 2
      })
      addGroup(group)
    } else {
      // A group is filled on its way through addGroup; a lone text preset is
      // filled here, after the decode that turns its %7B%7B back into braces.
      group.text && (group.text = decodeText(group.text))
      const widget: any = fillWidget(group, brandResolver())
      widget.left = pW / 2 - widget.fontSize * (widget.text.length / 2)
      widget.top = pH / 2 - widget.fontSize / 2
      addWidget(widget)
    }
  }

  function getCompDetail(params: TGetTempDetail): Promise<TTempDetail> {
    return new Promise((resolve) => {
      if (compsCache[params.id]) {
        resolve(compsCache[params.id])
      } else
        api.home.getTempDetail(params).then((res: any) => {
          resolve(res)
          compsCache[params.id] = res
        })
    })
  }

  return (
    <div className="wrap comp-list-wrap">
      {!currentCategory ? (
        <ClassHeader
          types={types}
          onSelect={selectTypes}
          renderSection={(index) => (
            <div className="list-wrap">
              {(showList[index] || []).map((item, i) => (
                <div
                  key={i + 'sl'}
                  draggable={false}
                  onMouseDown={(e) => dragStart(e, item)}
                  onMouseMove={mousemove}
                  onMouseUp={mouseup}
                  onClick={(e) => {
                    e.stopPropagation()
                    selectItem(item)
                  }}
                  onDragStart={(e) => e.preventDefault()}
                >
                  <Image className="list__img-thumb" src={item.cover} fit="contain" lazy />
                </div>
              ))}
            </div>
          )}
        />
      ) : null}

      {currentCategory ? (
        <ul ref={listRef} className="infinite-list" style={{ overflow: 'auto' }}>
          <ClassHeader isBack onBack={back}>
            {currentCategory.name}
          </ClassHeader>
          <Space fill wrap fillRatio={30} direction="horizontal" className="list">
            {list.map((item, i) => (
              <div
                key={i + 'i'}
                className="list__item"
                draggable={false}
                onMouseDown={(e) => dragStart(e, item)}
                onMouseMove={mousemove}
                onMouseUp={mouseup}
                onClick={(e) => {
                  e.stopPropagation()
                  selectItem(item)
                }}
                  onDragStart={(e) => e.preventDefault()}
              >
                <Image className="list__img" src={item.cover} fit="contain" lazy />
              </div>
            ))}
          </Space>
          {loading ? (
            <div className="loading">
              <i className="el-icon-loading" /> Loading
            </div>
          ) : null}
          {loadDone ? <div className="loading">That is everything</div> : null}
        </ul>
      ) : null}
    </div>
  )
}
