// src/components/modules/panel/wrap/PhotoListWrap.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import api from '@/api'
import type { TGetImageListResult } from '@/api/material'
import setImageData from '@/common/methods/DesignFeatures/setImage'
import { canvasState } from '@/store/state'
import { setShowMoveable } from '@/store/control'
import { addWidget, setSelectItem } from '@/store/widget'
import wImageSetting from '../../widgets/wImage/wImageSetting'
import { PHOTO_NOTICES } from './components/photoNotices'
import SearchHeader from './components/SearchHeader'
import ClassHeader from './components/ClassHeader'
import PhotoList from './components/PhotoList'
import './photoListWrap.less'

type TCurrentCategory = {
  name: string
  id?: number
}

const BROWSE_CATEGORIES: TCurrentCategory[] = [
  { id: 1, name: 'School life' },
  { id: 2, name: 'Backgrounds' },
  { id: 3, name: 'Sports' },
]

export default function PhotoListWrap() {
  const [recommendImgList, setRecommendImgList] = useState<TGetImageListResult[]>([])
  const [loadDone, setLoadDone] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [currentCategory, setCurrentCategory] = useState<TCurrentCategory | null>(null)
  const [types, setTypes] = useState<TCurrentCategory[]>([])
  const [showList, setShowList] = useState<TGetImageListResult[][]>([])
  const [notice, setNotice] = useState('')

  const loading = useRef(false)
  const page = useRef(0)
  const doneRef = useRef(false)
  const keywordRef = useRef('')
  const categoryRef = useRef<TCurrentCategory | null>(null)
  const recommendRef = useRef<TGetImageListResult[]>([])
  recommendRef.current = recommendImgList

  const isViewingList = Boolean(keyword) || Boolean(currentCategory)
  const listTitle = useMemo(() => (keyword ? `“${keyword}”` : currentCategory?.name ?? ''), [keyword, currentCategory])

  useEffect(() => {
    let cancelled = false
    setTypes(BROWSE_CATEGORIES)
    ;(async () => {
      const collected: TGetImageListResult[][] = []
      let firstNotice = ''
      for (const iterator of BROWSE_CATEGORIES) {
        const { list = [], error } = await api.material.getImagesList({ cate: iterator.id, pageSize: 2 })
        if (error && !firstNotice) firstNotice = PHOTO_NOTICES[error]
        collected.push(list)
      }
      if (cancelled) return
      firstNotice && setNotice(firstNotice)
      setShowList(collected)
    })()
    return () => {
      cancelled = true
    }
  }, [])

  const selectImg = async (index: number, list?: TGetImageListResult[]) => {
    const item = list ? list[index] : recommendRef.current[index]
    setShowMoveable(false)

    const setting = JSON.parse(JSON.stringify(wImageSetting))
    const img = await setImageData(item as any)
    setting.width = img.width
    setting.height = img.height
    setting.imgUrl = item.url
    const { width: pW, height: pH } = canvasState.dPage
    setting.left = pW / 2 - img.width / 2
    setting.top = pH / 2 - img.height / 2

    addWidget(setting)
    api.material.trackImageUse(item.downloadLocation)
  }

  const getDataList = useCallback(async () => {
    if (!(Boolean(keywordRef.current) || Boolean(categoryRef.current)) || doneRef.current || loading.current) {
      return
    }
    loading.current = true
    page.current += 1
    const { list = [], error } = await api.material.getImagesList({
      cate: categoryRef.current?.id,
      keyword: keywordRef.current || undefined,
      page: page.current,
      pageSize: 30,
    })
    if (error) {
      setNotice(PHOTO_NOTICES[error])
      doneRef.current = true
      setLoadDone(true)
    } else if (list.length <= 0) {
      doneRef.current = true
      setLoadDone(true)
      if (recommendRef.current.length <= 0) {
        setNotice(keywordRef.current ? `No photos match “${keywordRef.current}”. Try a broader word.` : 'No photos here yet.')
      }
    } else {
      setRecommendImgList((prev) => prev.concat(list))
    }
    setTimeout(() => {
      loading.current = false
    }, 100)
  }, [])

  const dragStart = (index: number, list?: TGetImageListResult[]) => {
    const item = list ? list[index] : recommendRef.current[index]
    setSelectItem({ data: { value: item }, type: 'image' })
    api.material.trackImageUse(item.downloadLocation)
  }

  const resetList = () => {
    page.current = 0
    doneRef.current = false
    setLoadDone(false)
    setRecommendImgList([])
    recommendRef.current = []
    setNotice('')
  }

  const searchChange = (next: string) => {
    const trimmed = next.trim()
    if (trimmed === keywordRef.current) {
      return
    }
    keywordRef.current = trimmed
    setKeyword(trimmed)
    categoryRef.current = null
    setCurrentCategory(null)
    resetList()
    trimmed && getDataList()
  }

  const selectTypes = (item: TCurrentCategory) => {
    keywordRef.current = ''
    setKeyword('')
    categoryRef.current = item
    setCurrentCategory(item)
    resetList()
    getDataList()
  }

  const back = () => {
    keywordRef.current = ''
    setKeyword('')
    categoryRef.current = null
    setCurrentCategory(null)
    resetList()
  }

  return (
    <div className="wrap photo-list-wrap">
      <SearchHeader placeholder="Search photos" onSearch={searchChange} />
      <div style={{ height: '0.5rem' }} />

      {!isViewingList ? (
        <>
          {notice ? <p className="notice notice--inset">{notice}</p> : null}
          <ClassHeader
            types={types}
            onSelect={selectTypes}
            renderSection={(index) => (
              <PhotoList
                isShort
                listData={(showList[index] || []) as any}
                onLoad={getDataList}
                onDrag={(i) => dragStart(i, showList[index])}
                onSelect={(i) => selectImg(i, showList[index])}
              />
            )}
          />
        </>
      ) : (
        <div>
          <ClassHeader isBack onBack={back}>
            {listTitle}
          </ClassHeader>
          <br />
          <br />
          <br />
          <div style={{ margin: '0 1rem', height: '100vh' }}>
            {notice ? (
              <p className="notice">{notice}</p>
            ) : (
              <PhotoList isDone={loadDone} listData={recommendImgList as any} onLoad={getDataList} onDrag={(i) => dragStart(i)} onSelect={(i) => selectImg(i)} />
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// src/components/modules/panel/wrap/PhotoListWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-02-11 18:48:23
 * @Description: Photo library Form:Unsplash无版权图片
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-08-14 18:50:09
-->
<template>
  <div class="wrap">
    <search-header type="none" @change="searchChange" />
    <div style="height: 0.5rem" />
    <classHeader v-show="!state.currentCategory" :types="state.types" @select="selectTypes">
      <template v-slot="{ index }">
        <photo-list :isShort="true" :listData="state.showList[index]" @load="getDataList" @drag="dragStart($event, state.showList[index])" @select="selectImg($event, state.showList[index])" />
      </template>
    </classHeader>
    <div v-if="state.currentCategory">
      <classHeader :is-back="true" @back="back">{{ state.currentCategory.name }}</classHeader>
      <br /><br /><br />
      <div style="margin: 0 1rem; height: 100vh">
        <photo-list :isDone="state.loadDone" :listData="state.recommendImgList" @load="getDataList" @drag="dragStart" @select="selectImg" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// 图片列表
// const NAME = 'img-list-wrap'
import { toRefs, reactive, computed, onMounted } from 'vue'
// import wImage from '../../widgets/wImage/wImage.vue'
import wImageSetting from '../../widgets/wImage/wImageSetting'
import api from '@/api'

import setImageData from '@/common/methods/DesignFeatures/setImage'
import { storeToRefs } from 'pinia'
import { useControlStore, useCanvasStore, useWidgetStore } from '@/store'
import { TGetImageListResult } from '@/api/material'

type TProps = {
  active?: boolean
}

type TState = {
  recommendImgList: TGetImageListResult[]
  loadDone: boolean
  page: number
  currentCategory: TCurrentCategory | null
  types: []
  showList: TGetImageListResult[][]
}

type TCurrentCategory = {
  name: string
  id?: number
}

const props = defineProps<TProps>()

const controlStore = useControlStore()
const widgetStore = useWidgetStore()

const { dPage } = storeToRefs(useCanvasStore())
const state = reactive<TState>({
  recommendImgList: [],
  loadDone: false,
  page: 0,
  currentCategory: null,
  types: [],
  showList: [],
})
let loading = false

onMounted(async () => {
  if (state.types.length <= 0) {
    // const types = await api.material.getKinds({ type: 4 })
    state.types = [
      { id: 1, name: 'Photo list with a responsive layout' },
      { id: 2, name: 'Photo list with a responsive layout' },
    ]
    for (const iterator of state.types) {
      const { list } = await api.material.getImagesList({ cate: iterator.id, pageSize: 2 })
      state.showList.push(list)
    }
  }
})

const selectImg = async (index: number, list: TGetImageListResult[]) => {
  const item = list ? list[index] : state.recommendImgList[index]

  // store.commit('setShowMoveable', false) // Clear the previous selection
  controlStore.setShowMoveable(false) // Clear the previous selection

  let setting = JSON.parse(JSON.stringify(wImageSetting))
  const img = await setImageData(item) // await getImage(item.url)
  setting.width = img.width
  setting.height = img.height // parseInt(100 / item.value.ratio, 10)
  setting.imgUrl = item.url
  const { width: pW, height: pH } = dPage.value
  setting.left = pW / 2 - img.width / 2
  setting.top = pH / 2 - img.height / 2

  widgetStore.addWidget(setting)
  // store.dispatch('addWidget', setting)
}

const getDataList = async () => {
  if (state.loadDone || loading) {
    return
  }
  loading = true
  state.page += 1
  let { list = [], total } = await api.material.getImagesList({ cate: state.currentCategory?.id, page: state.page, pageSize: 30 })
  list.length <= 0 ? (state.loadDone = true) : (state.recommendImgList = state.recommendImgList.concat(list))
  setTimeout(() => {
    loading = false
  }, 100)
}

const dragStart = (index: number, list: TGetImageListResult[]) => {
  const item = list ? list[index] : state.recommendImgList[index]

  widgetStore.setSelectItem({ data: { value: item }, type: 'image' })
  // store.commit('selectItem', { data: { value: item }, type: 'image' })
}

const searchChange = (e: Event) => {
  console.log(e)
}

const selectTypes = (item: TCurrentCategory) => {
  state.currentCategory = item
  getDataList()
}

const back = () => {
  state.currentCategory = null
  state.page = 0
  state.loadDone = false
  state.recommendImgList = []
}

defineExpose({
  selectImg,
  getDataList,
  dragStart,
  searchChange,
  selectTypes,
  back,
})
</script>

<style lang="less" scoped>
.wrap {
  width: 100%;
  height: 100%;
}
</style>
