// react/src/components/modules/panel/wrap/ToolsListWrap.tsx
import { useEffect, useRef } from 'react'
import { canvasState } from '@/store/state'
import { setShowMoveable } from '@/store/control'
import { addWidget } from '@/store/widget'
import wImageSetting from '../../widgets/wImage/wImageSetting'
import type { LocalUpload } from '@/common/methods/localUploads'
import { readQuery } from '@/common/hooks/useRouteQuery'
import ImageCutout, { type ImageCutoutHandle } from '@/components/business/image-cutout/ImageCutout'
import { wQrcodeSetting } from '../../widgets/wQrcode/wQrcodeSetting'
import './toolsListWrap.less'

export default function ToolsListWrap() {
  const imageCutoutRef = useRef<ImageCutoutHandle | null>(null)

  useEffect(() => {
    const timer = setTimeout(() => {
      const { koutu } = readQuery()
      koutu && openImageCutout()
    }, 300)
    return () => clearTimeout(timer)
  }, [])

  function addQrcode() {
    setShowMoveable(false)
    const setting = JSON.parse(JSON.stringify(wQrcodeSetting))
    const { width: pW, height: pH } = canvasState.dPage
    setting.left = pW / 2 - setting.width / 2
    setting.top = pH / 2 - setting.height / 2
    addWidget(setting)
  }

  function openImageCutout() {
    imageCutoutRef.current?.open()
  }

  /**
   * Puts the finished cut-out on the page.
   *
   * Opened from a picture already on the page, the dialog replaces that picture
   * and this never runs. Opened from here there is nothing to replace, and
   * downloading a file only to upload it again is not what anyone wants.
   */
  function cutOutDone(saved: LocalUpload) {
    setShowMoveable(false)
    const setting = JSON.parse(JSON.stringify(wImageSetting))
    const { width: pW, height: pH } = canvasState.dPage
    // Fit it inside the page rather than dropping a 2400px photo on an A4 poster.
    const scale = Math.min(1, (pW * 0.6) / saved.width, (pH * 0.6) / saved.height)
    setting.width = Math.round(saved.width * scale)
    setting.height = Math.round(saved.height * scale)
    setting.imgUrl = saved.url
    setting.left = pW / 2 - setting.width / 2
    setting.top = pH / 2 - setting.height / 2
    addWidget(setting)
  }

  return (
    <div className="wrap tools-list-wrap">
      <div className="header">Element</div>
      <div className="item" onClick={addQrcode}>
        <i className="icon sd-w-qrcode" />
        <div className="text">
          <span>QR code</span>
          <span className="desc">Add a styled QR code to your design</span>
        </div>
      </div>
      <div className="header">Other</div>
      <div className="item" onClick={openImageCutout}>
        <i className="icon sd-AI_zhineng" />
        <div className="text">
          <span>Remove background</span> <span className="desc">Upload a picture and remove its background</span>
        </div>
      </div>
      <ImageCutout ref={imageCutoutRef} onDone={cutOutDone} />
    </div>
  )
}

// src/components/modules/panel/wrap/ToolsListWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-02-11 18:48:23
 * @Description: 组件列表
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2023-10-13 18:48:25
-->
<template>
  <div class="wrap">
    <div class="header">Element</div>
    <div class="item" @click="addQrcode">
      <i class="icon sd-w-qrcode" />
      <div class="text"><span>QR code</span><span class="desc">Add a styled QR code to your design</span></div>
    </div>
    <div class="header">Other</div>
    <div class="item" @click="openImageCutout">
      <i class="icon sd-AI_zhineng" />
      <div class="text"><span>Remove background</span> <span class="desc">Upload a picture and remove its background</span></div>
    </div>
    <imageCutout ref="imageCutoutRef" @done="cutOutDone" />
  </div>
</template>

<script lang="ts" setup>
// 图片列表
// const NAME = 'tool-list-wrap'
// import api from '@/api'
import { ref, onMounted } from 'vue'

import { useRoute } from 'vue-router'
// import wQrcode from '../../widgets/wQrcode/wQrcode.vue'
import imageCutout from '@/components/business/image-cutout'
// import { useSetupMapGetters } from '@/common/hooks/mapGetters'
import { wQrcodeSetting } from '../../widgets/wQrcode/wQrcodeSetting'
import wImageSetting from '../../widgets/wImage/wImageSetting'
import type { LocalUpload } from '@/common/methods/localUploads'
import { storeToRefs } from 'pinia'
import { useControlStore, useCanvasStore, useWidgetStore } from '@/store'


const controlStore = useControlStore()

const route = useRoute()

const loadDone = ref(false)
const imageCutoutRef = ref<typeof imageCutout | null>(null)
const widgetStore = useWidgetStore()
const { dPage } = storeToRefs(useCanvasStore())

onMounted(() => {
  // this.getDataList()
  setTimeout(() => {
    const { koutu } = route.query
    koutu && openImageCutout()
  }, 300)
})

// ...mapActions(['addWidget'])

// async function getDataList() {
//   if (loadDone || loading) {
//     return
//   }
//   loading = true
//   page += 1
// }

function addQrcode() {
  // store.commit('setShowMoveable', false) // Clear the previous selection
  controlStore.setShowMoveable(false) // Clear the previous selection

  let setting = JSON.parse(JSON.stringify(wQrcodeSetting))
  const { width: pW, height: pH } = dPage.value
  setting.left = pW / 2 - setting.width / 2
  setting.top = pH / 2 - setting.height / 2

  widgetStore.addWidget(setting)
  // store.dispatch('addWidget', setting)
  // addWidget(setting)
}

function openImageCutout() {
  if (!imageCutoutRef.value) return
  imageCutoutRef.value.open()
}

/**
 * Puts the finished cut-out on the page.
 *
 * Opened from a picture already on the page, the dialog replaces that picture
 * and this never runs. Opened from here there is nothing to replace, and
 * downloading a file only to upload it again is not what anyone wants.
 */
function cutOutDone(saved: LocalUpload) {
  controlStore.setShowMoveable(false)
  const setting = JSON.parse(JSON.stringify(wImageSetting))
  const { width: pW, height: pH } = dPage.value
  // Fit it inside the page rather than dropping a 2400px photo on an A4 poster.
  const scale = Math.min(1, (pW * 0.6) / saved.width, (pH * 0.6) / saved.height)
  setting.width = Math.round(saved.width * scale)
  setting.height = Math.round(saved.height * scale)
  setting.imgUrl = saved.url
  setting.left = pW / 2 - setting.width / 2
  setting.top = pH / 2 - setting.height / 2
  widgetStore.addWidget(setting)
}
</script>

<style lang="less" scoped>
.wrap {
  width: 100%;
  height: 100%;
}
.header {
  padding: 17px 1rem;
  height: 56px;
  display: flex;
  position: relative;
  font-size: 16px;
  color: @ink;
  font-weight: bold;
  display: flex;
  align-items: center;
  user-select: none;
}
.item {
  opacity: 0.85;
  position: relative;
  border-radius: 4px;
  font-size: 15px;
  height: 72px;
  color: @ink;
  display: flex;
  align-items: center;
  cursor: pointer;
  margin: 0 1rem 16px;
  user-select: none;
  background-color: @surface-2;
}
.item:hover {
  opacity: 1;
}
.icon {
  margin: 0 1rem;
  font-size: 32px;
}
.text {
  display: flex;
  flex-direction: column;
}
.desc {
  padding-top: 0.5rem;
  color: @ink-3;
  font-size: 12px;
}
</style>
