// src/components/modules/panel/wrap/UserWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-02-13 22:18:35
 * @Description: 我的
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-08-12 09:32:00
-->
<template>
  <div class="wrap">
    <el-tabs v-model="state.tabActiveName" :stretch="true" class="tabs" @tab-change="tabChange">
      <el-tab-pane label="Manage files" name="pics"> </el-tab-pane>
      <el-tab-pane label="My designs" name="design"> </el-tab-pane>
    </el-tabs>
    <div v-show="state.tabActiveName === 'pics'">
      <uploader v-model="state.percent" class="upload" @done="uploadDone">
        <el-button class="upload-btn" plain><i class="iconfont icon-upload" /> Upload image</el-button>
      </uploader>
      <el-button disabled class="upload-btn upload-psd" plain type="primary" @click="openPSD">Import PSD</el-button>
      <div style="margin: 1rem; height: 100vh">
        <photo-list ref="imgListRef" :edit="state.editOptions.photo" :isDone="state.isDone" :listData="state.imgList" @load="load" @drag="dragStart" @select="selectImg" />
      </div>
    </div>
    <div v-show="state.tabActiveName === 'design'" class="wrap">
      <ul ref="listRef" v-infinite-scroll="loadDesign" class="infinite-list" :infinite-scroll-distance="150" style="overflow: auto">
        <img-water-fall :edit="state.editOptions.works" :listData="state.designList" @select="selectDesign" />
        <!-- <div v-show="loading" class="loading"><i class="el-icon-loading"></i>Loading..</div> -->
        <div v-show="state.isDone" class="loading">That is everything</div>
      </ul>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { reactive, toRefs, watch, nextTick, ref, onMounted } from 'vue'
import { ElTabPane, ElTabs, TabPaneName } from 'element-plus'
import { useRouter } from 'vue-router'

import uploader from '@/components/common/Uploader'
import api from '@/api'
// import wImage from '../../widgets/wImage/wImage.vue'
import wImageSetting from '../../widgets/wImage/wImageSetting'
import setImageData, { TItem2DataParam } from '@/common/methods/DesignFeatures/setImage'
import useConfirm from '@/common/methods/confirm'
import { TGetImageListResult, TMyPhotoResult } from '@/api/material'
import photoList from './components/photoList.vue'
import imgWaterFall from './components/imgWaterFall.vue'
import { TUploadDoneData } from '@/components/common/Uploader/index.vue'
import { IGetTempListData } from '@/api/home'
import eventBus from '@/utils/plugins/eventBus'
import { storeToRefs } from 'pinia'
import { useControlStore, useCanvasStore, useWidgetStore } from '@/store'

type TProps = {
  active?: number
}

type TState = {
  prePath: string
  percent: { num: number } // Upload progress
  imgList: IGetTempListData[]
  designList: IGetTempListData[]
  isDone: boolean
  editOptions: Record<string, any>
  tabActiveName: string
}

const props = defineProps<TProps>()

const router = useRouter()

const controlStore = useControlStore()
const widgetStore = useWidgetStore()

const { dPage } = storeToRefs(useCanvasStore())
const listRef = ref<HTMLElement | null>(null)
const imgListRef = ref<typeof photoList | null>(null)

const state = reactive<TState>({
  prePath: 'user',
  percent: { num: 0 }, // Upload progress
  imgList: [],
  designList: [],
  isDone: false,
  editOptions: [],
  tabActiveName: '',
})

let loading = false
let page = 0
let listPage = 0

const load = (init?: boolean) => {
  if (init) {
    state.imgList = []
    page = 0
    state.isDone = false
  }
  if (state.isDone || loading) {
    return
  }
  loading = true
  page += 1
  api.material.getMyPhoto({ page }).then(({ list }) => {
    if (list.length <= 0) {
      state.isDone = true
    } else {
      state.imgList = state.imgList.concat(list)
    }
    setTimeout(() => {
      loading = false
      if (!imgListRef.value) return
      checkHeight(imgListRef.value.getRef(), load)
    }, 100)
  })
}

const loadDesign = (init: boolean = false) => {
  if (init) {
    state.designList = []
    listPage = 0
    state.isDone = false
  }
  if (state.isDone || loading) {
    return
  }
  loading = true
  listPage += 1
  api.home.getMyDesign({ page: listPage, pageSize: 10 }).then(({ list }) => {
    list.length <= 0
      ? (state.isDone = true)
      : (state.designList = state.designList.concat(
          list.map((x) => {
            x.cover = x.cover + '?r=' + Math.random()
            return x
          }),
        ))
    setTimeout(() => {
      loading = false
      if (!listRef.value) return
      checkHeight(listRef.value, loadDesign)
    }, 100)
  })
}

function checkHeight(el: HTMLElement, loadFn: Function) {
  // 检查高度是否占满，否则继续请求下一页
  if (el.offsetHeight && el.firstElementChild) {
    const isLess = el.offsetHeight > (el.firstElementChild as HTMLElement).offsetHeight
    isLess && loadFn()
  }
}

onMounted(() => {
  load(true)
  nextTick(() => {
    state.tabActiveName = 'pics'
  })
})

const selectImg = async (index: number) => {
  const item = state.imgList[index]

  // store.commit('setShowMoveable', false) // Clear the previous selection
  controlStore.setShowMoveable(false) // Clear the previous selection

  let setting = JSON.parse(JSON.stringify(wImageSetting))
  const img = await setImageData(item)
  setting.width = img.width
  setting.height = img.height // parseInt(100 / item.value.ratio, 10)
  setting.imgUrl = item.url
  const { width: pW, height: pH } = dPage.value
  setting.left = pW / 2 - img.width / 2
  setting.top = pH / 2 - img.height / 2

  widgetStore.addWidget(setting)
  // store.dispatch('addWidget', setting)
}

type controlImgParam = {
  i: number
  item: Required<TItem2DataParam>
}

const deleteImg = async ({ i, item }: controlImgParam) => {
  // store.commit('setShowMoveable', false) // Clear the previous selection box
  controlStore.setShowMoveable(false) // Clear the previous selection box

  const isPass = await useConfirm('Warning', 'This cannot be undone, and anything already using this file will break.', 'warning')
  if (!isPass) {
    return false
  }
  const arr = item.url.split('/')
  let key = arr.splice(3, arr.length - 1).join('/')
  api.material.deleteMyPhoto({ id: item.id, key })
  if (!imgListRef.value) return
  imgListRef.value.delItem(i) // Notification flag
}
const deleteWorks = async ({ i, item }: controlImgParam) => {
  const isPass = await useConfirm('Warning', 'This cannot be undone. Are you sure?', 'warning')
  if (isPass) {
    await api.material.deleteMyWorks({ id: item.id })
    setTimeout(() => {
      router.push({ path: '/home', query: {}, replace: true })
      loadDesign(true)
    }, 300)
  }
}

state.editOptions = {
  photo: [
    {
      name: 'Delete',
      fn: deleteImg,
    },
  ],
  works: [
    {
      name: 'Delete',
      fn: deleteWorks,
    },
  ],
}

const dragStart = (index: number) => {
  const item = state.imgList[index]
  widgetStore.setSelectItem({ data: { value: item }, type: 'image' })
  // store.commit('selectItem', { data: { value: item }, type: 'image' })
}
const uploadDone = async (res: any) => {
  // await api.material.addMyPhoto(res)
  // state.imgList = []
  // load(true)
  const newList = [res, ...state.imgList]
  state.imgList = []
  setTimeout(() => {
    state.imgList = newList // Simulated loading
  }, 300)
}

const tabChange = (tabName: TabPaneName) => {
  if (tabName === 'design') {
    loadDesign(true)
  }
}

const selectDesign = async (item: IGetTempListData) => {
  // const { id }: any = state.designList[index]
  const { id } = item
  window.open(`${window.location.protocol + '//' + window.location.host}/home?id=${id}`)
}

const openPSD = () => {
  window.open(router.resolve('/psd').href, '_blank')
}

eventBus.on('refreshUserImages', () => {
  state.imgList = []
  load(true)
})

defineExpose({
  selectDesign,
  loadDesign,
  load,
  uploadDone,
  selectImg,
  deleteImg,
  dragStart,
  tabChange,
  openPSD,
})
</script>

<style lang="less" scoped>
.infinite-list {
  height: 100%;
  padding-bottom: 150px;
}
.loading {
  padding-top: 1rem;
  text-align: center;
  font-size: 14px;
  color: #999;
}

.tabs {
  padding: 0.2rem 0;
}
.upload {
  width: auto;
  margin: 0 0 0 1rem;
  display: inline-block;
  &-btn {
    width: 170px;
    font-size: 14px;
  }
  &-psd {
    width: 114px;
    margin-left: 10px;
  }
}
.wrap {
  width: 100%;
  height: 100%;
}
</style>

// src/components/modules/panel/wrap/UserWrap.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import api from '@/api'
import type { IGetTempListData } from '@/api/home'
import setImageData, { type TItem2DataParam } from '@/common/methods/DesignFeatures/setImage'
import useConfirm from '@/common/methods/confirm'
import { deleteUpload, listUploads } from '@/common/methods/localUploads'
import eventBus from '@/utils/plugins/eventBus'
import useInfiniteScroll from '@/common/hooks/useInfiniteScroll'
import { replaceQuery } from '@/common/hooks/useRouteQuery'
import Button from '@/components/ui/Button'
import Tabs from '@/components/ui/Tabs'
import Uploader, { type TModelData, type TUploadDoneData } from '@/components/common/Uploader/Uploader'
import { canvasState } from '@/store/state'
import { setShowMoveable } from '@/store/control'
import { addWidget, setSelectItem } from '@/store/widget'
import wImageSetting from '../../widgets/wImage/wImageSetting'
import PhotoList from './components/PhotoList'
import ImgWaterFall from './components/ImgWaterFall'
import './userWrap.less'

export default function UserWrap() {
  const [percent, setPercent] = useState<TModelData>({ num: 0 })
  const [imgList, setImgList] = useState<IGetTempListData[]>([])
  const [designList, setDesignList] = useState<IGetTempListData[]>([])
  const [isDone, setIsDone] = useState(false)
  const [tabActiveName, setTabActiveName] = useState('')
  const [deleted, setDeleted] = useState<Record<number, boolean>>({})

  const listRef = useRef<HTMLUListElement | null>(null)
  const loading = useRef(false)
  const listPage = useRef(0)
  const doneRef = useRef(false)
  const imgListRef = useRef<IGetTempListData[]>([])
  imgListRef.current = imgList

  const load = useCallback(async (init?: boolean) => {
    if (init) {
      setImgList([])
      doneRef.current = false
      setIsDone(false)
    }
    if (doneRef.current || loading.current) {
      return
    }
    loading.current = true
    const list = (await listUploads().catch(() => [])) as unknown as IGetTempListData[]
    setImgList(list)
    doneRef.current = true
    setIsDone(true)
    loading.current = false
  }, [])

  const loadDesign = useCallback((init: boolean = false) => {
    if (init) {
      setDesignList([])
      listPage.current = 0
      doneRef.current = false
      setIsDone(false)
    }
    if (doneRef.current || loading.current) {
      return
    }
    loading.current = true
    listPage.current += 1
    api.home.getMyDesign({ page: listPage.current, pageSize: 10 }).then(({ list }) => {
      if (list.length <= 0) {
        doneRef.current = true
        setIsDone(true)
      } else {
        setDesignList((prev) =>
          prev.concat(
            list.map((x) => {
              x.cover = x.cover + '?r=' + Math.random()
              return x
            }),
          ),
        )
      }
      setTimeout(() => {
        loading.current = false
        if (!listRef.current) return
        checkHeight(listRef.current, loadDesign)
      }, 100)
    })
  }, [])

  function checkHeight(el: HTMLElement, loadFn: Function) {
    if (el.offsetHeight && el.firstElementChild) {
      const isLess = el.offsetHeight > (el.firstElementChild as HTMLElement).offsetHeight
      isLess && loadFn()
    }
  }

  useInfiniteScroll(listRef, loadDesign, 150, tabActiveName === 'design')

  useEffect(() => {
    load(true)
    setTabActiveName('pics')
    const refresh = () => {
      setImgList([])
      doneRef.current = false
      load(true)
    }
    eventBus.on('refreshUserImages', refresh)
    return () => {
      eventBus.off('refreshUserImages', refresh)
    }
  }, [load])

  const selectImg = async (index: number) => {
    const item = imgListRef.current[index]
    setShowMoveable(false)

    const setting = JSON.parse(JSON.stringify(wImageSetting))
    const img = await setImageData(item as any)
    setting.width = img.width
    setting.height = img.height
    setting.imgUrl = item.url
    const { width: pW, height: pH } = canvasState.dPage
    setting.left = pW / 2 - img.width / 2
    setting.top = pH / 2 - img.height / 2

    addWidget(setting)
  }

  const deleteImg = async ({ i, item }: { i: number; item: Required<TItem2DataParam> }) => {
    setShowMoveable(false)
    const isPass = await useConfirm(
      'Remove this upload?',
      'It will disappear from anything on the page that uses it.',
      'warning',
    )
    if (!isPass) {
      return false
    }
    await deleteUpload(String(item.id))
    setDeleted((prev) => ({ ...prev, [i]: true }))
    setImgList((prev) => prev.map((entry, index) => (index === i ? { ...entry, isDelect: true } : entry)))
  }

  const deleteWorks = async ({ item }: { i: number; item: Required<TItem2DataParam> }) => {
    const isPass = await useConfirm('Warning', 'This cannot be undone. Are you sure?', 'warning')
    if (isPass) {
      await api.material.deleteMyWorks({ id: item.id })
      setTimeout(() => {
        replaceQuery({})
        loadDesign(true)
      }, 300)
    }
  }

  const editOptions = {
    photo: [{ name: 'Delete', fn: deleteImg }],
    works: [{ name: 'Delete', fn: deleteWorks }],
  }

  const dragStart = (index: number) => {
    const item = imgListRef.current[index]
    setSelectItem({ data: { value: item }, type: 'image' })
  }

  const uploadDone = (res: TUploadDoneData) => {
    const newList = [res as unknown as IGetTempListData, ...imgListRef.current]
    setImgList([])
    setTimeout(() => {
      setImgList(newList)
    }, 300)
  }

  const tabChange = (tabName: string) => {
    setTabActiveName(tabName)
    if (tabName === 'design') {
      loadDesign(true)
    }
  }

  const selectDesign = async (item: IGetTempListData) => {
    const { id } = item
    window.open(`${window.location.protocol + '//' + window.location.host}/home?id=${id}`)
  }

  const openPSD = () => {
    window.open('/psd', '_blank')
  }

  return (
    <div className="wrap user-wrap">
      <Tabs
        className="tabs"
        value={tabActiveName}
        onChange={tabChange}
        items={[
          { name: 'pics', label: 'Manage files' },
          { name: 'design', label: 'My designs' },
        ]}
      />
      <div style={{ display: tabActiveName === 'pics' ? undefined : 'none' }}>
        <div className="upload-actions">
          <Uploader value={percent} className="upload" onChange={setPercent} onDone={uploadDone}>
            <Button className="upload-btn" plain>
              <i className="iconfont icon-upload" /> Upload image
            </Button>
          </Uploader>
          <Button className="upload-btn" plain onClick={openPSD}>
            Import a PSD file
          </Button>
        </div>
        <div style={{ margin: '1rem', height: '100vh' }}>
          <PhotoList edit={editOptions.photo as any} isDone={isDone} listData={imgList} onLoad={() => load()} onDrag={dragStart} onSelect={selectImg} />
        </div>
      </div>
      <div className="wrap" style={{ display: tabActiveName === 'design' ? undefined : 'none' }}>
        <ul ref={listRef} className="infinite-list" style={{ overflow: 'auto' }}>
          <ImgWaterFall edit={editOptions.works as any} listData={designList} onSelect={selectDesign} />
          {isDone ? <div className="loading">That is everything</div> : null}
        </ul>
      </div>
    </div>
  )
}
