// src/components/business/picture-selector/index.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-10-08 10:07:19
 * @Description:  
 * @LastEditors: ShawnPhang <https://m.palxp.cn>, Jeremy Yu <https://github.com/JeremyYu-cn>
 * @Date: 2024-03-04 18:10:00
-->
<template>
  <el-dialog v-model="state.dialogVisible" title="Choose an image" @close="close">
    <el-tabs tab-position="left" style="height: 60vh" class="demo-tabs" @tab-change="tabChange">
      <el-tab-pane label="My uploads">
        <div class="pic__box">
          <photo-list :canDrag="false" :isDone="state.isDone" :listData="state.imgList" @load="load" @select="selectImg" />
        </div>
      </el-tab-pane>
      <el-tab-pane label="Photo library">
        <div class="pic__box">
          <photo-list :canDrag="false" :isDone="state.isPicsDone" :listData="state.recommendImgList" @load="loadPic" @select="selectImg($event, state.recommendImgList)" />
        </div>
      </el-tab-pane>
    </el-tabs>
    <!-- <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogVisible = false">Cancel</el-button>
        <el-button plain type="primary" @click="dialogVisible = false"
          >Confirm</el-button
        >
      </span>
    </template> -->
  </el-dialog>
</template>

<script lang="ts" setup>
import { reactive } from 'vue'
import { listUploads } from '@/common/methods/localUploads'
import { ElTabPane, ElTabs, TabPaneName } from 'element-plus'
import api from '@/api'
import { TGetImageListResult } from '@/api/material'
import { useControlStore } from '@/store'

type TEmits = (event: 'select', data: TGetImageListResult) => void

type TState = {
  dialogVisible: boolean;
  imgList: TGetImageListResult[];
  recommendImgList: TGetImageListResult[];
  isDone: boolean;
  isPicsDone: boolean;
}

const emits = defineEmits<TEmits>()

const controlStore = useControlStore()

const state = reactive<TState>({
  dialogVisible: false,
  imgList: [],
  recommendImgList: [],
  isDone: false,
  isPicsDone: false,
})

let loading = false
let picPage = 0

// Uploads are held in this browser, so there is nothing to page through.
const load = async (init?: boolean) => {
  if (init) {
    state.imgList = []
    state.isDone = false
  }
  if (state.isDone || loading) {
    return
  }
  loading = true
  state.imgList = (await listUploads().catch(() => [])) as unknown as TGetImageListResult[]
  state.isDone = true
  loading = false
}

const loadPic = (init?: boolean) => {
  if (state.isPicsDone || loading) {
    return
  }
  if (init && state.recommendImgList.length > 0) {
    return
  }
  loading = true
  picPage += 1
  api.material.getImagesList({ page: picPage }).then(({ list }) => {
    list.length <= 0 ? (state.isPicsDone = true) : (state.recommendImgList = state.recommendImgList.concat(list))
    setTimeout(() => {
      loading = false
    }, 100)
  })
}

const open = () => {
  state.dialogVisible = true
  load()
  // store.commit('setShowMoveable', false)
  controlStore.setShowMoveable(false)
}

const close = () => {
  // store.commit('setShowMoveable', true)
  controlStore.setShowMoveable(true)
}

const selectImg = (index: number, list: TGetImageListResult[]) => {
  const item: TGetImageListResult = list ? list[index] : state.imgList[index]
  // context.emit('select', item)
  emits('select', item)
  state.dialogVisible = false
}

const tabChange = (index: TabPaneName) => {
  if (index == 1) {
    loadPic(true)
  }
}

defineExpose({
  open
})

</script>

<style lang="less" scoped>
.pic__box {
  width: 100%;
  height: 70vh;
}
</style>

// src/components/business/picture-selector/PictureSelector.tsx
import { forwardRef, useCallback, useImperativeHandle, useRef, useState } from 'react'
import api from '@/api'
import type { TGetImageListResult } from '@/api/material'
import { listUploads } from '@/common/methods/localUploads'
import Dialog from '@/components/ui/Dialog'
import Tabs from '@/components/ui/Tabs'
import { setShowMoveable } from '@/store/control'
import PhotoList from '@/components/modules/panel/wrap/components/PhotoList'
import './pictureSelector.less'

export type PictureSelectorHandle = {
  open: () => void
}

type Props = {
  onSelect?: (item: TGetImageListResult) => void
}

const PictureSelector = forwardRef<PictureSelectorHandle, Props>(function PictureSelector({ onSelect }, ref) {
  const [visible, setVisible] = useState(false)
  const [tab, setTab] = useState('uploads')
  const [imgList, setImgList] = useState<TGetImageListResult[]>([])
  const [recommendImgList, setRecommendImgList] = useState<TGetImageListResult[]>([])
  const [isDone, setIsDone] = useState(false)
  const [isPicsDone, setIsPicsDone] = useState(false)

  const loading = useRef(false)
  const picPage = useRef(0)
  const doneRef = useRef(false)
  const picsDoneRef = useRef(false)
  const listRef = useRef<TGetImageListResult[]>([])
  listRef.current = imgList
  const recommendRef = useRef<TGetImageListResult[]>([])
  recommendRef.current = recommendImgList

  const load = useCallback(async (init?: boolean) => {
    if (init) {
      setImgList([])
      doneRef.current = false
      setIsDone(false)
    }
    if (doneRef.current || loading.current) {
      return
    }
    loading.current = true
    const list = (await listUploads().catch(() => [])) as unknown as TGetImageListResult[]
    setImgList(list)
    doneRef.current = true
    setIsDone(true)
    loading.current = false
  }, [])

  const loadPic = useCallback((init?: boolean) => {
    if (picsDoneRef.current || loading.current) {
      return
    }
    if (init && recommendRef.current.length > 0) {
      return
    }
    loading.current = true
    picPage.current += 1
    api.material.getImagesList({ page: picPage.current }).then(({ list }) => {
      if (list.length <= 0) {
        picsDoneRef.current = true
        setIsPicsDone(true)
      } else {
        setRecommendImgList((prev) => prev.concat(list))
      }
      setTimeout(() => {
        loading.current = false
      }, 100)
    })
  }, [])

  useImperativeHandle(
    ref,
    () => ({
      open: () => {
        setVisible(true)
        load()
        setShowMoveable(false)
      },
    }),
    [load],
  )

  function onOpenChange(next: boolean) {
    setVisible(next)
    if (!next) setShowMoveable(true)
  }

  const selectImg = (index: number, list?: TGetImageListResult[]) => {
    const item = list ? list[index] : listRef.current[index]
    onSelect?.(item)
    setVisible(false)
  }

  function tabChange(name: string) {
    setTab(name)
    if (name === 'library') loadPic(true)
  }

  return (
    <Dialog open={visible} onOpenChange={onOpenChange} title="Choose an image" className="picture-selector">
      <Tabs
        className="demo-tabs"
        stretch={false}
        value={tab}
        onChange={tabChange}
        items={[
          { name: 'uploads', label: 'My uploads' },
          { name: 'library', label: 'Photo library' },
        ]}
      >
        <div style={{ display: tab === 'uploads' ? undefined : 'none' }}>
          <div className="pic__box">
            <PhotoList canDrag={false} isDone={isDone} listData={imgList as any} onLoad={() => load()} onSelect={(i) => selectImg(i)} />
          </div>
        </div>
        <div style={{ display: tab === 'library' ? undefined : 'none' }}>
          <div className="pic__box">
            <PhotoList canDrag={false} isDone={isPicsDone} listData={recommendImgList as any} onLoad={() => loadPic()} onSelect={(i) => selectImg(i, recommendRef.current)} />
          </div>
        </div>
      </Tabs>
    </Dialog>
  )
})

export default PictureSelector
