// src/components/modules/layout/designBoard/PageStyle.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import { useSnapshot } from 'valtio'
import _dl from '@/common/methods/download'
import { widgetState } from '@/store/state'
import { updatePageData } from '@/store/canvas'
import { selectWidget } from '@/store/widget/select'
import Button from '@/components/ui/Button'
import Collapse, { CollapseItem } from '@/components/ui/Collapse'
import Tooltip from '@/components/ui/Tooltip'
import { DeleteIcon, DownloadIcon } from '@/components/ui/icons'
import Uploader, { type TUploadDoneData } from '@/components/common/Uploader/Uploader'
import Tabs from '@/packages/color-picker/comps/Tabs'
import ColorSelect, { type colorChangeData } from '@/components/modules/settings/ColorSelect'
import ResizeDesign, { type ResizeDesignHandle } from '@/components/business/resize-design/ResizeDesign'
import BgImgListWrap from '@/components/modules/panel/wrap/BgImgListWrap'
import wImageSetting from '@/components/modules/widgets/wImage/wImageSetting'
import type { TBackgroundTransform } from '@/common/methods/pageBackground'
import type { TPageState } from '@/store/types'
import BackgroundCrop from './comps/BackgroundCrop'
import './pageStyle.less'

const MODES = ['Colour', 'Image']

export default function PageStyle() {
  const snap = useSnapshot(widgetState)
  const active = snap.dActiveElement as TPageState | null

  const [activeNames, setActiveNames] = useState<string[]>(['1', '2', '3', '4'])
  const [mode, setMode] = useState('Colour')
  const [showBgLib, setShowBgLib] = useState(false)
  const sizeEditRef = useRef<ResizeDesignHandle | null>(null)
  const localTempBG = useRef<string | null>(null)

  useEffect(() => {
    setMode(active?.backgroundImage ? MODES[1] : MODES[0])
  }, [active?.uuid])

  // The Vue original watched the active element deeply, so the tab followed the
  // background however it was set. Keying only on the page missed the library,
  // which sets the background from its own panel: you came back to the Colour
  // tab, with nothing to show that the picture you had just chosen had been
  // applied — and no way to reach the buttons that work on it.
  useEffect(() => {
    if (active?.backgroundImage) setMode(MODES[1])
  }, [active?.backgroundImage])

  const changeTransform = useCallback((transform: TBackgroundTransform) => {
    updatePageData({ key: 'backgroundTransform', value: transform })
  }, [])

  if (!active) return null

  function colorChange(e: colorChangeData) {
    if (e.mode === 'Gradient') {
      finish('backgroundGradient', e.color)
    } else finish('backgroundGradient', '')
  }

  function onChangeMode(value: string) {
    setMode(value)
    if (value === 'Colour') {
      localTempBG.current = (active as TPageState).backgroundImage
      finish('backgroundImage', '')
    } else {
      localTempBG.current && finish('backgroundImage', localTempBG.current)
    }
  }

  function finish(key: keyof TPageState, value: string | number | Record<string, any>) {
    updatePageData({ key, value })
  }

  async function uploadImgDone(img: TUploadDoneData) {
    // The picture's shape is what lets the crop control zoom past the size that
    // just covers the page, and an upload is the one place it arrives for free.
    updatePageData({ key: 'backgroundTransform', value: img.width && img.height ? { ratio: img.width / img.height } : {} })
    finish('backgroundImage', img.url)
  }

  async function deleteBg() {
    localTempBG.current = null
    updatePageData({ key: 'backgroundImage', value: '' })
    updatePageData({ key: 'backgroundTransform', value: {} })
    setMode(MODES[1])
  }

  async function downloadBG() {
    await _dl.downloadImg((active as TPageState).backgroundImage, () => {})
  }

  async function shiftOut() {
    const setting = JSON.parse(JSON.stringify(wImageSetting))
    setting.width = (active as TPageState).width
    setting.height = (active as TPageState).height
    setting.imgUrl = (active as TPageState).backgroundImage
    setting.uuid = `bg-${new Date().getTime()}`
    widgetState.dWidgets.unshift(setting)
    selectWidget({ uuid: widgetState.dWidgets[0].uuid })
    deleteBg()
  }

  function openSizeEdit() {
    sizeEditRef.current?.open()
  }

  const backgroundImage = active.backgroundImage

  return (
    <div id="page-style">
      {showBgLib ? (
        <div className="bg-library">
          <span className="header-back" onClick={() => setShowBgLib(false)}>
            <i className="iconfont icon-right" /> Choose a background
          </span>
          <BgImgListWrap model="stylePanel" />
        </div>
      ) : (
        <Collapse value={activeNames} onChange={setActiveNames}>
          <CollapseItem name="1" title="Page size">
            <div className="page-size">
              <span className="page-size__value">
                {Math.round(active.width)} × {Math.round(active.height)} px
              </span>
              <Button plain size="small" onClick={openSizeEdit}>
                Resize…
              </Button>
            </div>
          </CollapseItem>
          <CollapseItem name="2" title="Background">
            <Button className="bg-library-open" plain onClick={() => setShowBgLib(true)}>
              <i className="iconfont icon-gallery" />
              Browse the background library
            </Button>
            <Tabs value={mode} labels={MODES} onChange={onChangeMode} />
            <div style={{ display: mode === 'Colour' ? undefined : 'none' }}>
              <ColorSelect
                value={active.backgroundColor}
                modes={['Solid', 'Gradient']}
                onValueChange={(value) => finish('backgroundColor', value)}
                onChange={colorChange}
              />
            </div>
            {mode === 'Image' && backgroundImage ? (
              <>
                <div className="backgroud-wrap">
                  <BackgroundCrop page={active} onChange={changeTransform} />
                  <div className="bg-options">
                    <Tooltip content="Download image" placement="top" showAfter={300}>
                      <div onClick={downloadBG} className="btn-item">
                        <DownloadIcon width={16} height={16} />
                      </div>
                    </Tooltip>
                    <Tooltip content="Remove" placement="top" showAfter={300}>
                      <div onClick={deleteBg} className="btn-item">
                        <DeleteIcon width={16} height={16} />
                      </div>
                    </Tooltip>
                  </div>
                </div>
                <div className="bg-actions">
                  <Uploader onDone={uploadImgDone}>
                    <Button plain>Replace image</Button>
                  </Uploader>
                  <Button plain onClick={() => setShowBgLib(true)}>
                    Backgrounds
                  </Button>
                </div>
              </>
            ) : null}
            <Uploader
              className="btn-wrap"
              style={{ display: mode === 'Image' && !backgroundImage ? undefined : 'none' }}
              onDone={uploadImgDone}
            >
              <Button style={{ width: '100%' }} plain>
                Upload background
              </Button>
            </Uploader>
            <Button
              className="btn-wrap"
              style={{ display: mode === 'Image' && backgroundImage ? undefined : 'none' }}
              onClick={shiftOut}
            >
              Move background to a layer
            </Button>
          </CollapseItem>
        </Collapse>
      )}
      <ResizeDesign ref={sizeEditRef} />
    </div>
  )
}

// src/components/modules/layout/designBoard/pageStyle.vue
<template>
  <div id="page-style">
    <div v-if="state.showBgLib" style="width: 256px; height: 100%">
      <span class="header-back" @click="state.showBgLib = false"> <i class="iconfont icon-right"></i> Choose a background </span>
      <bg-img-list-wrap style="padding-top: 2rem" model="stylePanel" />
    </div>
    <el-collapse v-else v-model="state.activeNames">
      <el-collapse-item title="Page size" name="1">
        <div class="page-size">
          <span class="page-size__value">{{ Math.round(state.innerElement.width) }} × {{ Math.round(state.innerElement.height) }} px</span>
          <el-button plain size="small" @click="openSizeEdit">Resize…</el-button>
        </div>
      </el-collapse-item>
      <el-collapse-item title="Background" name="2">
        <el-button style="width: 100%; margin: 0 0 1rem 0" type="primary" link @click="state.showBgLib = true">Choose from the background library</el-button>
        <Tabs :value="state.mode" @update:value="onChangeMode">
          <TabPanel v-for="label in state.modes" :key="label" :label="label"></TabPanel>
        </Tabs>
        <color-select v-show="state.mode === 'Colour'" v-model="state.innerElement.backgroundColor" :modes="['Solid', 'Gradient']" @change="colorChange" />
        <div v-if="state.mode === 'Image' && state.innerElement.backgroundImage" style="margin-top: 1.2rem">
          <div class="backgroud-wrap">
            <el-image style="height: 100%" :src="state.innerElement.backgroundImage" fit="contain"></el-image>
            <div class="bg-control">
              <div class="btns">
                <uploader style="width: 47%" @done="uploadImgDone">
                  <el-button style="width: 100%" plain>Upload image</el-button>
                </uploader>
                <el-button style="width: 47%" @click="state.showBgLib = true" plain>Backgrounds</el-button>
              </div>
            </div>
            <div class="bg-options">
              <el-tooltip :show-after="300" :hide-after="0" effect="dark" content="Download image" placement="top">
                <div @click="downloadBG" class="btn-item"><icon-download width="16" /></div>
              </el-tooltip>
              <el-tooltip :show-after="300" :hide-after="0" effect="dark" content="Delete" placement="top">
                <div @click="deleteBg" class="btn-item"><icon-delete width="16" /></div>
              </el-tooltip>
            </div>
          </div>
          <!-- <el-image style="max-height: 428px" :src="state.innerElement.backgroundImage" fit="contain"></el-image> -->
          <!-- <el-button class="btn-wrap" size="small" @click="deleteBg">Delete</el-button> -->
        </div>
        <uploader v-show="state.mode === 'Image' && !state.innerElement.backgroundImage" class="btn-wrap" @done="uploadImgDone">
          <el-button style="width: 100%" plain>Upload background</el-button>
        </uploader>
        <!-- <el-button v-show="state.mode === 'Image' && state.innerElement.backgroundImage" class="btn-wrap" size="small" @click="downloadBG">{{ state.downP ? state.downP + ' %' : '下载背景图' }}</el-button> -->
        <el-button v-show="state.mode === 'Image' && state.innerElement.backgroundImage" class="btn-wrap" @click="shiftOut">Move background to a layer</el-button>
      </el-collapse-item>
    </el-collapse>
    <resizeDesign ref="sizeEditRef" />
  </div>
</template>

<script lang="ts" setup>
// 画布组件样式
// const NAME = 'page-style'
import { nextTick, onMounted, reactive, watch, ref, Ref } from 'vue'
import colorSelect, { colorChangeData } from '@/components/modules/settings/colorSelect.vue'
import uploader, { TUploadDoneData } from '@/components/common/Uploader/index.vue'
import api from '@/api'
import _dl from '@/common/methods/download'
import Tabs from '@palxp/color-picker/comps/Tabs.vue'
import TabPanel from '@palxp/color-picker/comps/TabPanel.vue'
import { useCanvasStore, useWidgetStore } from '@/store'
import { TPageState } from '@/store/design/canvas/d'
import { storeToRefs } from 'pinia'
import { Delete as iconDelete, Download as iconDownload } from '@element-plus/icons-vue'
import wImageSetting from '@/components/modules/widgets/wImage/wImageSetting'
import resizeDesign from '@/components/business/resize-design'

type TState = {
  activeNames: string[]
  innerElement: Record<string, any>
  tag: boolean
  ingoreKeys: string[]
  downP: number
  mode: string
  modes: string[]
  showBgLib: boolean
}

const pageStore = useCanvasStore()
const widgetStore = useWidgetStore()
const state = reactive<TState>({
  activeNames: ['1', '2', '3', '4'],
  innerElement: {},
  tag: false,
  ingoreKeys: ['backgroundColor', 'name', 'width', 'height'],
  downP: 0,
  mode: 'Colour',
  modes: ['Colour', 'Image'],
  showBgLib: false,
})
const sizeEditRef: Ref<typeof resizeDesign | null> = ref(null)
// const { dActiveElement } = useSetupMapGetters(['dActiveElement'])
const { dActiveElement } = storeToRefs(widgetStore)
let _localTempBG: string | null = null

watch(
  () => dActiveElement.value,
  () => {
    change()
  },
  { deep: true },
)

watch(
  () => state.innerElement,
  () => {
    changeValue()
  },
  { deep: true },
)

onMounted(() => {
  change()
})

function colorChange(e: colorChangeData) {
  if (e.mode === 'Gradient') {
    state.innerElement.backgroundGradient = e.color
  } else state.innerElement.backgroundGradient = ''
}
function onChangeMode(value: string) {
  state.mode = value
  if (value === 'Colour') {
    _localTempBG = state.innerElement.backgroundImage
    finish('backgroundImage', '')
  } else {
    _localTempBG && finish('backgroundImage', _localTempBG)
  }
}
function change() {
  state.mode = state.modes[0]
  state.tag = true
  state.innerElement = dActiveElement.value || {}
  state.innerElement.backgroundImage && (state.mode = state.modes[1])
}
function changeValue() {
  if (state.tag) {
    state.tag = false
    return
  }
  for (let key in state.innerElement) {
    if (state.innerElement[key] !== (dActiveElement.value as Record<string, any>)[key]) {
      if (state.ingoreKeys.indexOf(key) !== -1) {
        ;(dActiveElement.value as Record<string, any>)[key] = state.innerElement[key]
      } else {
        pageStore.updatePageData({
          key: key as keyof TPageState,
          value: state.innerElement[key],
        })
      }
    }
  }
}

function finish(key: keyof TPageState, value: string | number) {
  pageStore.updatePageData({
    key: key,
    value: value
  })
}
async function uploadImgDone(img: TUploadDoneData) {
  pageStore.updatePageData({
    key: 'backgroundTransform',
    value: {},
  })
  finish('backgroundImage', img.url)
}
async function deleteBg() {
  _localTempBG = null
  pageStore.updatePageData({
    key: 'backgroundImage',
    value: ''
  })
  await nextTick()
  state.mode = state.modes[1]
}
async function downloadBG() {
  await _dl.downloadImg(state.innerElement.backgroundImage, (p) => {
    state.downP = p < 99 ? p / 100 : 0
  })
}

// 分离背景图，添加到画布中
async function shiftOut() {
  let setting = JSON.parse(JSON.stringify(wImageSetting))
  setting.width = state.innerElement.width
  setting.height = state.innerElement.height
  setting.imgUrl = state.innerElement.backgroundImage
  setting.uuid = `bg-${new Date().getTime()}`
  widgetStore.dWidgets.unshift(setting)
  widgetStore.selectWidget({
    uuid: widgetStore.dWidgets[0].uuid,
  })
  deleteBg()
}

// 打开
function openSizeEdit() {
  sizeEditRef.value?.open()
}
</script>

<style lang="less" scoped>
.page-size {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  &__value {
    color: @ink-2;
    font-size: @text-base;
  }
}

#page-style {
  height: 100%;
  width: 100%;
  .sd-edit {
    cursor: pointer;
    color: @ink-2;
    font-size: 22px;
  }
  .sd-edit:hover {
    color: @ink;
    transform: scale(1.2);
  }
}
.select {
  margin-bottom: 10px;
}
.btn-wrap {
  width: 100%;
  margin-top: 1.2rem;
}
.header {
  &-back {
    cursor: pointer;
    display: flex;
    align-items: center;
    color: @ink;
    font-size: 14px;
    font-weight: 600;
    height: 2.9rem;
    position: absolute;
    z-index: 2;
    background: @surface;
    width: 259px;
    .icon-right {
      transform: rotate(180deg);
    }
  }
}

.backgroud-wrap {
  overflow: hidden;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 160px;
  padding: 16px;
  background-color: @surface-3;
  border-radius: 8px;
  .bg-options {
    position: absolute;
    top: 8px;
    right: 8px;
    display: flex;
  }
  .btn-item {
    margin-left: 5px;
    cursor: pointer;
    background-color: @popover;
    width: 24px;
    height: 24px;
    padding: 0;
    font-size: 14px;
    border-radius: 4px;
    display: flex;
    justify-content: center;
    align-items: center;
    border: none;
    box-shadow: @shadow-pop;
  }
  // Fades in over the background image with the buttons that change it, so it
  // shades rather than covers — you keep seeing what you are replacing.
  .bg-control {
    transition: all 0.3s;
    opacity: 0;
    position: absolute;
    width: 100%;
    height: 100%;
    background: @scrim-strong;
    .btns {
      padding: 0 2%;
      position: absolute;
      width: 100%;
      display: flex;
      justify-content: space-around;
      bottom: 12px;
    }
  }
  .bg-control:hover {
    opacity: 1;
  }
}
</style>
