// src/components/business/right-click-menu/RcMenu.vue
<template>
  <div v-show="showMenuBg" id="menu-bg" class="menu-bg" @click="closeMenu">
    <ul ref="menuList" class="menu-list" :style="styleObj">
      <li
        v-for="(item, index) in menuListData.list"
        :key="index"
        :class="{ 'menu-item': true, 'disable-menu': dCopyElement.length === 0 && item.type === 'paste' }"
        @click.stop="selectMenu(item.type)"
      >
        {{ item.text }}
      </li>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref, toRaw } from 'vue'
import { 
  widgetMenu as widget, 
  pageMenu as page,
  menuList as menu, 
  TMenuItemData, TWidgetItemData, 
} from './rcMenuData'
import { getTarget } from '@/common/methods/target'
import { storeToRefs } from 'pinia';
import { useControlStore, useWidgetStore } from '@/store';

const menuListData = ref<TMenuItemData>({...menu})
const showMenuBg = ref<boolean>(false)
const widgetMenu = ref<TWidgetItemData[]>([...widget])
const pageMenu = ref<TWidgetItemData[]>([...page])

const widgetStore = useWidgetStore()

const {dActiveElement, dWidgets, dCopyElement} = storeToRefs(widgetStore)
const { dAltDown } = storeToRefs(useControlStore())

const styleObj = computed(() => {
  return {
    left: menuListData.value.left + 'px',
    top: menuListData.value.top + 'px',
  }
})

onMounted(() => {
  document.oncontextmenu = mouseRightClick
})
async function mouseRightClick(e: MouseEvent) {
  e.stopPropagation()
  e.preventDefault()
  if (showMenuBg.value) {
    showMenuBg.value = false
    return
  }
  if (!e.target) return
  let target = await getTarget(e.target as HTMLElement)
  if (!target) return
  let type = target.getAttribute('data-type')
  if (type) {
    let uuid = target.getAttribute('data-uuid') // Set the selected element

    if (uuid !== '-1' && !dAltDown.value) {
      let widget = dWidgets.value.find((item: any) => item.uuid === uuid)
      if (
        widget?.parent !== '-1' && 
        widget?.parent !== dActiveElement.value?.uuid &&
        widget?.parent !== dActiveElement.value?.parent
      ) {
        uuid = widget?.parent || ""
      }
    }
    widgetStore.selectWidget({
      uuid: uuid ?? '-1',
    })
    showMenu(e)
  }
}

function showMenu(e: MouseEvent) {
  let isPage = dActiveElement.value?.uuid === '-1'
  menuListData.value.list = isPage ? pageMenu.value : widgetMenu.value
  if (dActiveElement.value?.isContainer) {
    let ungroup: TWidgetItemData[] = [
      {
        type: 'ungroup',
        text: 'Ungroup',
      },
    ]
    menuListData.value.list = ungroup.concat(menuListData.value.list)
  }
  showMenuBg.value = true
  // document.getElementById('menu-bg').addEventListener('click', this.closeMenu, false)
  let mx = e.pageX
  let my = e.pageY
  let listWidth = 120
  if (mx + listWidth > window.innerWidth) {
    mx -= listWidth
  }
  let listHeight = (14 + 10) * menuListData.value.list.length + 10
  if (my + listHeight > window.innerHeight) {
    my -= listHeight
  }
  menuListData.value.left = mx
  menuListData.value.top = my
}

function closeMenu() {
  showMenuBg.value = false
}

/** 点击菜单触发事件 */
function selectMenu(type: TWidgetItemData['type']) {
  switch (type) {
    case 'copy':
      widgetStore.copyWidget()
      break
    case 'paste':
      if (dCopyElement.value.length === 0) {
        return
      }
      widgetStore.pasteWidget()
      break
    case 'index-up':
      widgetStore.updateLayerIndex({
        uuid: dActiveElement.value?.uuid || "",
        value: 1,
        isGroup: dActiveElement.value?.isContainer,
      })
      break
    case 'index-down':
      widgetStore.updateLayerIndex({
        uuid: dActiveElement.value?.uuid || "",
        value: -1,
        isGroup: dActiveElement.value?.isContainer,
      })
      break
    case 'del':
      widgetStore.deleteWidget()
      break
    case 'ungroup':
      widgetStore.ungroup(dActiveElement.value?.uuid || "")
      break
  }
  closeMenu()
}

</script>

<style lang="less" scoped>
.menu-bg {
  height: 100%;
  position: absolute;
  width: 100%;
  z-index: 99999;
  .menu-list {
    background-color: @popover;
    box-shadow: @shadow-pop;
    padding: 5px;
    position: absolute;
    width: 120px;
    .menu-item {
      cursor: pointer;
      font-size: 14px;
      line-height: 1;
      padding: 5px 15px;
      width: 100%;
      &:hover {
        background-color: @surface-2;
      }
    }
    .menu-item.disable-menu {
      background-color: @popover;
      color: @ink-4;
      cursor: not-allowed;
    }
  }
}
</style>

// src/components/business/right-click-menu/RcMenu.tsx
import { useEffect, useState } from 'react'
import { useSnapshot } from 'valtio'
import { getTarget } from '@/common/methods/target'
import { controlState, widgetState } from '@/store/state'
import { copyWidget, deleteWidget, pasteWidget, selectWidget, ungroup, updateLayerIndex } from '@/store/widget'
import { menuList as menu, pageMenu, widgetMenu, type TMenuItemData, type TWidgetItemData } from './rcMenuData'
import { cx } from '@/utils/dom'
import './rcMenu.less'

export default function RcMenu() {
  const [menuListData, setMenuListData] = useState<TMenuItemData>({ ...menu })
  const [showMenuBg, setShowMenuBg] = useState(false)
  const { dCopyElement } = useSnapshot(widgetState)

  useEffect(() => {
    document.oncontextmenu = mouseRightClick
    return () => {
      document.oncontextmenu = null
    }
  })

  async function mouseRightClick(e: MouseEvent) {
    e.stopPropagation()
    e.preventDefault()
    if (showMenuBg) {
      setShowMenuBg(false)
      return
    }
    if (!e.target) return
    const target = await getTarget(e.target as HTMLElement)
    if (!target) return
    const type = target.getAttribute('data-type')
    if (type) {
      let uuid = target.getAttribute('data-uuid')

      if (uuid !== '-1' && !controlState.dAltDown) {
        const widget = widgetState.dWidgets.find((item) => item.uuid === uuid)
        const active = widgetState.dActiveElement
        if (widget?.parent !== '-1' && widget?.parent !== active?.uuid && widget?.parent !== active?.parent) {
          uuid = widget?.parent || ''
        }
      }
      selectWidget({ uuid: uuid ?? '-1' })
      showMenu(e)
    }
    return false
  }

  function showMenu(e: MouseEvent) {
    const active = widgetState.dActiveElement
    const isPage = active?.uuid === '-1'
    let list: TWidgetItemData[] = isPage ? pageMenu : widgetMenu
    if (active?.isContainer) {
      list = ([{ type: 'ungroup', text: 'Ungroup' }] as TWidgetItemData[]).concat(list)
    }
    let mx = e.pageX
    let my = e.pageY
    const listWidth = 120
    if (mx + listWidth > window.innerWidth) {
      mx -= listWidth
    }
    const listHeight = (14 + 10) * list.length + 10
    if (my + listHeight > window.innerHeight) {
      my -= listHeight
    }
    setMenuListData({ list, left: mx, top: my })
    setShowMenuBg(true)
  }

  function closeMenu() {
    setShowMenuBg(false)
  }

  function selectMenu(type: TWidgetItemData['type']) {
    const active = widgetState.dActiveElement
    switch (type) {
      case 'copy':
        copyWidget()
        break
      case 'paste':
        if (widgetState.dCopyElement.length === 0) {
          return
        }
        pasteWidget()
        break
      case 'index-up':
        updateLayerIndex({ uuid: active?.uuid || '', value: 1, isGroup: active?.isContainer })
        break
      case 'index-down':
        updateLayerIndex({ uuid: active?.uuid || '', value: -1, isGroup: active?.isContainer })
        break
      case 'del':
        deleteWidget()
        break
      case 'ungroup':
        ungroup(active?.uuid || '')
        break
    }
    closeMenu()
  }

  return (
    <div id="menu-bg" className="menu-bg" style={{ display: showMenuBg ? undefined : 'none' }} onClick={closeMenu}>
      <ul className="menu-list" style={{ left: menuListData.left + 'px', top: menuListData.top + 'px' }}>
        {menuListData.list.map((item, index) => (
          <li
            key={index}
            className={cx('menu-item', { 'disable-menu': dCopyElement.length === 0 && item.type === 'paste' })}
            onClick={(e) => {
              e.stopPropagation()
              selectMenu(item.type)
            }}
          >
            {item.text}
          </li>
        ))}
      </ul>
    </div>
  )
}
