// src/components/modules/widgets/wText/wTextStyle.vue
<template>
  <div id="w-text-style">
    <el-collapse v-model="state.activeNames">
      <el-collapse-item title="Size and position" name="1">
        <div class="line-layout">
          <number-input v-model="state.innerElement.left" label="X" @finish="(value) => finish('left', value)" />
          <number-input v-model="state.innerElement.top" label="Y" @finish="(value) => finish('top', value)" />
          <number-input v-model="state.innerElement.width" style="margin-top: 0.5rem" label="W" :editable="true" @finish="(value) => finish('width', value)" />
          <number-input v-model="state.innerElement.height" style="margin-top: 0.5rem" label="H" :editable="true" @finish="(value) => finish('height', value)" />
        </div>
      </el-collapse-item>
      <!-- <el-collapse-item title="Style" name="2"> -->
      <div class="line-layout style-item">
        <value-select v-model="state.innerElement.fontClass" label="Text" :data="state.fontClassList" inputWidth="152px" :readonly="true" @finish="(font) => finish('fontClass', font)" />
        <value-select v-model="state.innerElement.fontSize" label="Size" suffix="px" :data="state.fontSizeList" @finish="(value) => finish('fontSize', value)" />
      </div>

      <icon-item-select class="style-item" :data="state.styleIconList1" @finish="textStyleAction" />
      <icon-item-select class="style-item" :data="state.styleIconList2" @finish="textStyleAction" />

      <!-- <div style="flex-wrap: nowrap" class="line-layout style-item">
        <value-select v-model="innerElement.lineHeight" label="Line height" suffix="x" :data="lineHeightList" @finish="(value) => finish('lineHeight', value)" />
        <value-select v-model="innerElement.letterSpacing" label="Letter spacing" suffix="%" :data="letterSpacingList" @finish="(value) => finish('letterSpacing', value)" />
      </div> -->
      <!-- <el-collapse-item title="Size and position" name="1"> -->
      <div class="style-item slide-wrap">
        <number-slider v-model="state.innerElement.letterSpacing" style="font-size: 14px" label="Letter spacing" :step="0.05" :minValue="-state.innerElement.fontSize" :maxValue="state.innerElement.fontSize * 2" @finish="(value) => finish('letterSpacing', value)" />
        <number-slider v-model="state.innerElement.lineHeight" style="font-size: 14px" label="Line height" :step="0.05" :minValue="0" :maxValue="2.5" @finish="(value) => finish('lineHeight', value)" />
      </div>
      <!-- </el-collapse-item> -->

      <div style="flex-wrap: nowrap" class="line-layout style-item">
        <color-select v-model="state.innerElement.color" label="Colour" @finish="(value) => finish('color', value)" />
        <!-- <color-select v-model="innerElement.backgroundColor" label="背景颜色" @finish="(value) => finish('backgroundColor', value)" /> -->
      </div>
      <div class="line-layout style-item">
        <effect-wrap v-model="state.innerElement.textEffects" :data="state.innerElement" :degree="state.innerElement.degree" @select="selectTextEffect" />
      </div>
      <icon-item-select class="style-item" :data="layerIconList" @finish="layerAction" />
      <icon-item-select class="style-item" :data="alignIconList" @finish="alignAction" />

      <!-- v-show="!innerElement.editable"  -->
      <div style="margin-top: 10px" class="line-layout style-item">
        <text-input-area v-model="state.innerElement.text" @finish="(value) => finish('text', value)" />
      </div>
      <!-- </el-collapse-item> -->
    </el-collapse>
  </div>
</template>

<script lang="ts" setup>
// 文本组件样式
const NAME = 'w-text-style'
import { defineComponent, reactive, toRefs, computed, watch, nextTick, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { styleIconList1, styleIconList2, alignIconList, TStyleIconData, TStyleIconData2 } from '@/assets/data/TextIconsData'
import layerIconList from '@/assets/data/LayerIconList'
import numberInput from '../../settings/numberInput.vue'
import numberSlider from '../../settings/numberSlider.vue'
import colorSelect from '../../settings/colorSelect.vue'
import iconItemSelect, { TIconItemSelectData } from '../../settings/iconItemSelect.vue'
import textInputArea from '../../settings/textInputArea.vue'
import valueSelect from '../../settings/valueSelect.vue'
import effectWrap from '../../settings/EffectSelect/TextWrap.vue'
import { useFontStore } from '@/common/methods/fonts'
import { FONT_GROUPS } from '@/assets/data/FontsData'
import { wTextSetting, TwTextData } from './wTextSetting'
import recolorEffects from './recolorEffects'
import { storeToRefs } from 'pinia'
import { useControlStore, useForceStore, useWidgetStore } from '@/store'
import { TUpdateWidgetPayload } from '@/store/design/widget/actions/widget'
import { TUpdateAlignData } from '@/store/design/widget/actions/align'

type TState = {
  activeNames: string[]
  innerElement: TwTextData
  tag: boolean
  ingoreKeys: string[]
  fontSizeList: number[]
  fontClassList: Record<string, any> // Never fall back to the system font: the export service cannot guarantee a match
  lineHeightList: number[]
  letterSpacingList: number[]
  layerIconList: TIconItemSelectData[]
  styleIconList1: TStyleIconData[]
  styleIconList2: TStyleIconData2[]
  alignIconList: TIconItemSelectData[]
}

const widgetStore = useWidgetStore()
const forceStore = useForceStore()
const route = useRoute()
const state = reactive<TState>({
  activeNames: [],
  innerElement: JSON.parse(JSON.stringify(wTextSetting)),
  tag: false,
  ingoreKeys: ['left', 'top', 'name', 'width', 'height', 'text', 'color', 'backgroundColor'],
  fontSizeList: [12, 14, 24, 26, 28, 30, 36, 48, 60, 72, 96, 108, 120, 140, 180, 200, 250, 300, 400, 500],
  fontClassList: {}, // Never fall back to the system font: the export service cannot guarantee a match
  lineHeightList: [1, 1.5, 2],
  letterSpacingList: [0, 10, 25, 50, 75, 100, 200],
  layerIconList,
  styleIconList1,
  styleIconList2,
  alignIconList,
})
const dActiveElement = computed(() => widgetStore.dActiveElement)
// const dMoving = computed(() => store.getters.dMoving)
const { dMoving } = storeToRefs(useControlStore())

// const isDraw = computed(() => route.name === 'Draw')

watch(
  () => dActiveElement.value,
  () => {
    change()
  },
  { deep: true },
)

watch(
  () => state.innerElement,
  () => {
    changeValue()
  },
  { deep: true },
)

let timer: boolean | null = null

onMounted(() => {
  change()
  setTimeout(() => {
    loadFonts()
  }, 100)
})

function change() {
  if (timer) {
    return
  }
  timer = true
  setTimeout(() => {
    timer = null
  }, 300)
  state.tag = true
  state.innerElement = JSON.parse(JSON.stringify(dActiveElement.value))
  changeStyleIconList()
}

function changeValue() {
  if (state.tag) {
    state.tag = false
    return
  }
  if (dMoving.value) {
    return
  }
  followTextColor()
  // TODO 修改数值
  for (let key in state.innerElement) {
    const itemKey = key as keyof TwTextData
    if (state.ingoreKeys.indexOf(itemKey) !== -1) {
      ;(dActiveElement.value as Record<string, any>)[itemKey] = state.innerElement[itemKey]
    } else if (key !== 'setting' && key !== 'record' && state.innerElement[itemKey] !== (dActiveElement.value as Record<string, any>)[itemKey]) {
      widgetStore.updateWidgetData({
        uuid: dActiveElement.value?.uuid || '',
        key: key as TUpdateWidgetPayload['key'],
        value: state.innerElement[itemKey],
      })
    }
  }
}

/**
 * A text effect is painted in the text's own colour, so the colour swatch has
 * to carry the stack with it — the fill layer sits on top of the plain text
 * and would otherwise go on showing the old colour, which reads as the swatch
 * doing nothing at all. See recolorEffects.ts for which parts follow.
 *
 * The widget still holds the colour being replaced, which is why changeValue
 * calls this before writing the new one through.
 */
function followTextColor() {
  const active = dActiveElement.value as Record<string, any> | undefined
  const effects = state.innerElement.textEffects
  if (!effects?.length) return
  // change() is throttled, so the panel can still be holding the widget that
  // was selected a moment ago. Recolouring then would write one widget's stack
  // onto another.
  if (!active || active.uuid !== state.innerElement.uuid) return
  state.innerElement.textEffects = recolorEffects(effects, active.color, state.innerElement.color)
}

function selectTextEffect({ key, value, style }: any) {
  const uuid = dActiveElement.value?.uuid || ''
  widgetStore.setWidgetStyle({ uuid, key, value })
  // store.commit('setWidgetStyle', { uuid, key, value })
  if (style) {
    finish('color', style.color || '')
  }
}

function loadFonts() {
  const localFonts = useFontStore.list
  // Four plain categories. With twenty fonts an "on this page" tab was one tab
  // too many for the picker's width and told people nothing they could not see.
  const fontLists: Record<string, any> = {}
  for (const group of Object.values(FONT_GROUPS)) fontLists[group] = []
  for (const font of localFonts) {
    const { id, oid, value, url, alias, preview, kind } = font
    fontLists[FONT_GROUPS[kind]].push({ id, oid, value, url, alias, preview })
  }
  state.fontClassList = fontLists
}

function finish(key: string, value: number | Record<string, any> | string) {
  widgetStore.updateWidgetData({
    uuid: dActiveElement.value?.uuid || '',
    key: key as TUpdateWidgetPayload['key'],
    value,
  })
  setTimeout(() => {
  }, 300)
}

function layerAction(item: TIconItemSelectData) {
  widgetStore.updateLayerIndex({
    uuid: dActiveElement.value?.uuid || '',
    value: Number(item.value),
  })
  // store.dispatch('updateLayerIndex', {
  //   uuid: dActiveElement.value.uuid,
  //   value: item.value,
  // })
}

async function textStyleAction(item: TIconItemSelectData) {
  const innerText = state.innerElement as Record<string, any>
  let value = ['textAlign', 'textAlignLast'].includes(item.key || '') ? item.value : (item.value as number[])[item.select ? 1 : 0]
  // Justify all判断是否选中，选中时则为抹去属性
  item.key === 'textAlignLast' && innerText[item.key] === value && (value = undefined)
  // 设置属性
  item.key && (innerText[item.key] = value)
  // 对Vertical text特殊处理
  item.key === 'writingMode' && relationChange()
  await nextTick()
  forceStore.setUpdateRect()
}

async function alignAction(item: TIconItemSelectData) {
  widgetStore.updateAlign({
    align: item.value as TUpdateAlignData['align'],
    uuid: dActiveElement.value?.uuid || '',
  })
  // store.dispatch('updateAlign', {
  //   align: item.value,
  //   uuid: dActiveElement.value.uuid,
  // })
  await nextTick()
  forceStore.setUpdateRect()
  // store.commit('updateRect')
}

function changeStyleIconList() {
  for (let i = 0; i < state.styleIconList1.length; ++i) {
    let key = state.styleIconList1[i].key
    state.styleIconList1[i].select = false
    const [unchecked, checked] = state.styleIconList1[i].value
    switch (key) {
      case 'fontWeight':
      case 'textDecoration':
      case 'fontStyle':
        if (state.innerElement[key] !== unchecked && state.innerElement[key] == checked) {
          state.styleIconList1[i].select = !state.styleIconList1[i].select
        }
        break
      case 'writingMode':
        if (state.innerElement[key] !== unchecked) {
          state.styleIconList1[i].select = true
        }
        break
    }
  }
  for (let i = 0; i < state.styleIconList2.length; i++) {
    let key = state.styleIconList2[i].key
    state.styleIconList2[i].select = false
    if (['textAlign', 'textAlignLast'].includes(key || '') && (state.innerElement as Record<string, any>)[key || ''] === state.styleIconList2[i].value) {
      state.styleIconList2[i].select = true
      continue
    }
  }
}

function relationChange() {
  setTimeout(() => {
    if (dActiveElement.value && dActiveElement.value.writingMode) {
      const w_record = dActiveElement.value.width
      state.innerElement.width = dActiveElement.value.height
      state.innerElement.height = w_record
    }
  }, 10)
}

defineExpose({
  selectTextEffect,
  textStyleAction,
  finish,
  layerAction,
  alignAction,
})
</script>

<style lang="less" scoped>
#w-text-style {
  height: 100%;
  width: 100%;
}
.line-layout {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-between;
  width: 100%;
}
.style-item {
  margin-bottom: 14px;
}
.setting-list {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-between;
  width: 100%;
}

// Sliders are grouped by spacing alone rather than a tinted panel.
.slide-wrap {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 4px 0 0;
}
</style>

// react/src/components/modules/widgets/wText/WTextStyle.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { useSnapshot } from 'valtio'
import { alignIconList, styleIconList1, styleIconList2 } from '@/assets/data/TextIconsData'
import layerIconList from '@/assets/data/LayerIconList'
import { FONT_GROUPS } from '@/assets/data/FontsData'
import { useFontStore } from '@/common/methods/fonts'
import Collapse, { CollapseItem } from '@/components/ui/Collapse'
import { controlState, widgetState } from '@/store/state'
import { setUpdateRect } from '@/store/force'
import { setWidgetStyle, updateAlign, updateLayerIndex, updateWidgetData } from '@/store/widget'
import NumberInput from '../../settings/NumberInput'
import NumberSlider from '../../settings/NumberSlider'
import ColorSelect from '../../settings/ColorSelect'
import IconItemSelect, { type TIconItemSelectData } from '../../settings/IconItemSelect'
import TextInputArea from '../../settings/TextInputArea'
import ValueSelect from '../../settings/ValueSelect'
import TextWrap from '../../settings/EffectSelect/TextWrap'
import recolorEffects from './recolorEffects'
import './wTextStyle.less'

const FONT_SIZE_LIST = [12, 14, 24, 26, 28, 30, 36, 48, 60, 72, 96, 108, 120, 140, 180, 200, 250, 300, 400, 500]

function buildFontLists() {
  const localFonts = useFontStore.list
  const fontLists: Record<string, any> = {}
  for (const group of Object.values(FONT_GROUPS)) fontLists[group] = []
  for (const font of localFonts) {
    const { id, oid, value, url, alias, preview, kind } = font
    fontLists[FONT_GROUPS[kind]].push({ id, oid, value, url, alias, preview })
  }
  return fontLists
}

export default function WTextStyle() {
  const snap = useSnapshot(widgetState)
  const active = snap.dActiveElement as any
  const [activeNames, setActiveNames] = useState<string[]>([])
  const [fontClassList, setFontClassList] = useState<Record<string, any>>({})

  useEffect(() => {
    const timer = setTimeout(() => setFontClassList(buildFontLists()), 100)
    return () => clearTimeout(timer)
  }, [])

  const styleIcons1 = useMemo(() => {
    if (!active) return styleIconList1
    return styleIconList1.map((item) => {
      const next = { ...item, select: false }
      const [unchecked, checked] = item.value
      switch (item.key) {
        case 'fontWeight':
        case 'textDecoration':
        case 'fontStyle':
          if (active[item.key] !== unchecked && active[item.key] == checked) next.select = true
          break
        case 'writingMode':
          if (active[item.key] !== unchecked) next.select = true
          break
      }
      return next
    })
  }, [active?.fontWeight, active?.textDecoration, active?.fontStyle, active?.writingMode, active])

  const styleIcons2 = useMemo(() => {
    if (!active) return styleIconList2
    return styleIconList2.map((item) => ({
      ...item,
      select: ['textAlign', 'textAlignLast'].includes(item.key) && active[item.key] === item.value,
    }))
  }, [active?.textAlign, active?.textAlignLast, active])

  if (!active) return null

  const uuid = active.uuid as string

  function finish(key: string, value: number | Record<string, any> | string) {
    updateWidgetData({ uuid, key: key as any, value })
  }

  /**
   * A text effect is painted in the text's own colour, so the colour swatch has
   * to carry the stack with it — the fill layer sits on top of the plain text
   * and would otherwise go on showing the old colour, which reads as the swatch
   * doing nothing at all. See recolorEffects.ts for which parts follow.
   *
   * The widget still holds the colour being replaced, which is why the stack is
   * rewritten before the new colour is written through.
   */
  function changeColor(value: string) {
    const target = widgetState.dActiveElement as any
    const effects = target?.textEffects
    // The panel can still be holding the widget that was selected a moment ago.
    // Recolouring then would write one widget's stack onto another.
    if (effects?.length && target.uuid === uuid) {
      finish('textEffects', recolorEffects(JSON.parse(JSON.stringify(effects)), target.color, value) as any)
    }
    finish('color', value)
  }

  function selectTextEffect({ key, value, style }: any) {
    setWidgetStyle({ uuid, key, value })
    if (style) {
      finish('color', style.color || '')
    }
  }

  function layerAction(item: TIconItemSelectData) {
    updateLayerIndex({ uuid, value: Number(item.value) })
  }

  function textStyleAction(item: TIconItemSelectData) {
    const target = widgetState.dActiveElement as any
    if (!target) return
    let value: any = ['textAlign', 'textAlignLast'].includes(item.key || '')
      ? item.value
      : (item.value as any[])[item.select ? 1 : 0]
    if (item.key === 'textAlignLast' && target[item.key] === value) value = undefined
    item.key && (target[item.key] = value)
    if (item.key === 'writingMode') relationChange()
    requestAnimationFrame(() => setUpdateRect())
  }

  function relationChange() {
    setTimeout(() => {
      const target = widgetState.dActiveElement as any
      if (target && target.writingMode) {
        const wRecord = target.width
        target.width = target.height
        target.height = wRecord
      }
    }, 10)
  }

  function alignAction(item: TIconItemSelectData) {
    updateAlign({ align: item.value as any, uuid })
    requestAnimationFrame(() => setUpdateRect())
  }

  return (
    <div id="w-text-style">
      <Collapse value={activeNames} onChange={setActiveNames}>
        <CollapseItem name="1" title="Size and position">
          <div className="line-layout">
            <NumberInput value={active.left} label="X" onChange={(v) => finish('left', Number(v))} />
            <NumberInput value={active.top} label="Y" onChange={(v) => finish('top', Number(v))} />
            <NumberInput value={active.width} label="W" editable onChange={(v) => finish('width', Number(v))} />
            <NumberInput value={active.height} label="H" editable onChange={(v) => finish('height', Number(v))} />
          </div>
        </CollapseItem>
      </Collapse>

      <div className="line-layout style-item">
        <ValueSelect
          value={active.fontClass}
          label="Text"
          data={fontClassList}
          inputWidth="152px"
          readonly
          onFinish={(font) => finish('fontClass', font as any)}
        />
        <ValueSelect
          value={active.fontSize}
          label="Size"
          suffix="px"
          data={FONT_SIZE_LIST}
          onFinish={(value) => finish('fontSize', Number(value))}
        />
      </div>

      <IconItemSelect className="style-item" data={styleIcons1} onFinish={textStyleAction} />
      <IconItemSelect className="style-item" data={styleIcons2} onFinish={textStyleAction} />

      <div className="style-item slide-wrap">
        <NumberSlider
          value={active.letterSpacing}
          style={{ fontSize: 14 }}
          label="Letter spacing"
          step={0.05}
          minValue={-active.fontSize}
          maxValue={active.fontSize * 2}
          onChange={(value) => finish('letterSpacing', value)}
        />
        <NumberSlider
          value={active.lineHeight}
          style={{ fontSize: 14 }}
          label="Line height"
          step={0.05}
          minValue={0}
          maxValue={2.5}
          onChange={(value) => finish('lineHeight', value)}
        />
      </div>

      <div style={{ flexWrap: 'nowrap' }} className="line-layout style-item">
        <ColorSelect value={active.color} label="Colour" onValueChange={changeColor} />
      </div>
      <div className="line-layout style-item">
        <TextWrap
          value={active.textEffects}
          data={active}
          degree={active.degree}
          onValueChange={(value) => finish('textEffects', value as any)}
          onSelect={selectTextEffect}
        />
      </div>
      <IconItemSelect className="style-item" data={layerIconList} onFinish={layerAction} />
      <IconItemSelect className="style-item" data={alignIconList} onFinish={alignAction} />

      <div style={{ marginTop: 10 }} className="line-layout style-item">
        <TextInputArea value={active.text} onChange={(value) => finish('text', value)} />
      </div>
    </div>
  )
}
