// src/components/business/create-design/sizeEditor.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2024-04-08 21:33:59
 * @Description: 尺寸编辑
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-04-09 15:55:33
-->
<template>
  <div class="position-size">
    <number-input v-model="params.width" label="W" :maxValue="5000" />
    <el-tooltip :show-after="300" :hide-after="0" effect="dark" :content="lockRatio ? 'Lock aspect ratio' : 'Change freely'" placement="top">
      <i @click="changeRatio" :class="['icon', lockRatio ? 'sd-db' : 'sd-fdb']" />
    </el-tooltip>
    <number-input v-model="params.height" label="H" :maxValue="5000" />
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import numberInput from '@/components/modules/settings/numberInput.vue'

type TProps = {
  params: any
}
const props = withDefaults(defineProps<TProps>(), {
  params: {},
})

const lockRatio = ref(false) // Lock the aspect ratio while resizing
let scale = 0,
  temp = { width: 0, height: 0 }

watch(
  () => props.params.width,
  (val, old) => {
    if (scale && isNumber(val) && isNumber(old)) {
      temp.width === 0 && (temp.width = props.params.width)
      setChange()
    }
  },
)
watch(
  () => props.params.height,
  (val, old) => {
    if (scale && isNumber(val) && isNumber(old)) {
      temp.height === 0 && (temp.height = props.params.height)
      setChange()
    }
  },
)

// Lock aspect ratio
function changeRatio() {
  lockRatio.value = !lockRatio.value
  if (lockRatio.value) {
    scale = props.params.width / props.params.height
  } else scale = 0
}

// 应用更改
let timer: any = null
function setChange() {
  clearTimeout(timer)
  timer = setTimeout(() => {
    temp.width > 0 && temp.height === 0 && (props.params.height = props.params.width / scale)
    temp.height > 0 && temp.width === 0 && (props.params.width = props.params.height * scale)
    if (temp.width > 0 && temp.height > 0) {
      temp = { width: 0, height: 0 }
    }
  }, 300)
}

function isNumber(val: any) {
  return typeof val === 'number'
}
</script>

<style lang="less" scoped>
.position-size {
  display: flex;
  align-items: center;
  // justify-content: space-between;
  width: 100%;
  .number-input {
    flex: 0.2;
  }
  .icon {
    cursor: pointer;
    font-size: 19px;
  }
  .sd-fdb,
  .sd-db {
    color: #999999;
    margin: 0 6px 0 -4px;
  }
  .sd-db {
    color: #333333;
  }
}
</style>

// src/components/business/create-design/SizeEditor.tsx
import { useEffect, useRef, useState, type ReactNode } from 'react'
import NumberInput from '@/components/modules/settings/NumberInput'
import Tooltip from '@/components/ui/Tooltip'
import { SIZE_UNITS, fromPx, toPx, type TSizeUnit } from '@/common/methods/pageSize'
import { cx } from '@/utils/dom'
import './sizeEditor.less'

type Props = {
  params: { width: number; height: number; [key: string]: any }
  onChange?: (next: { width: number; height: number }) => void
  className?: string
  children?: ReactNode
}

function isNumber(val: any) {
  return typeof val === 'number'
}

/** The widest page anyone can ask for, in pixels — shown in whatever unit is on. */
const MAX_PX = 5000

export default function SizeEditor({ params, onChange, className, children }: Props) {
  const [lockRatio, setLockRatio] = useState(false)
  const [unit, setUnit] = useState<TSizeUnit>('px')
  const scale = useRef(0)
  const temp = useRef({ width: 0, height: 0 })
  const timer = useRef<any>(null)
  const prev = useRef({ width: params.width, height: params.height })

  function setChange() {
    clearTimeout(timer.current)
    timer.current = setTimeout(() => {
      if (temp.current.width > 0 && temp.current.height === 0) {
        onChange?.({ width: params.width, height: params.width / scale.current })
      }
      if (temp.current.height > 0 && temp.current.width === 0) {
        onChange?.({ width: params.height * scale.current, height: params.height })
      }
      if (temp.current.width > 0 && temp.current.height > 0) {
        temp.current = { width: 0, height: 0 }
      }
    }, 300)
  }

  useEffect(() => {
    if (scale.current && isNumber(params.width) && isNumber(prev.current.width) && params.width !== prev.current.width) {
      temp.current.width === 0 && (temp.current.width = params.width)
      setChange()
    }
    prev.current.width = params.width
  }, [params.width])

  useEffect(() => {
    if (scale.current && isNumber(params.height) && isNumber(prev.current.height) && params.height !== prev.current.height) {
      temp.current.height === 0 && (temp.current.height = params.height)
      setChange()
    }
    prev.current.height = params.height
  }, [params.height])

  function changeRatio() {
    const next = !lockRatio
    setLockRatio(next)
    scale.current = next ? params.width / params.height : 0
  }

  return (
    <>
      <div className={cx('position-size', className || '')}>
        <NumberInput
          value={fromPx(params.width, unit)}
          label="W"
          maxValue={fromPx(MAX_PX, unit)}
          onChange={(v) => onChange?.({ width: toPx(Number(v), unit), height: params.height })}
        />
        <Tooltip content={lockRatio ? 'Lock aspect ratio' : 'Change freely'} placement="top" showAfter={300}>
          <i onClick={changeRatio} className={cx('icon', lockRatio ? 'sd-db' : 'sd-fdb')} />
        </Tooltip>
        <NumberInput
          value={fromPx(params.height, unit)}
          label="H"
          maxValue={fromPx(MAX_PX, unit)}
          onChange={(v) => onChange?.({ width: params.width, height: toPx(Number(v), unit) })}
        />
        {children}
      </div>
      {/*
        The unit is a way of reading the same page, not a property of it: the
        store keeps pixels whatever is chosen here, so switching between them
        cannot change the design, and a page typed in as 210 × 297mm is the same
        1240 × 1754 page the A4 preset gives you.
      */}
      <div className="size-units" role="group" aria-label="Units">
        {SIZE_UNITS.map((name) => (
          <button key={name} type="button" className={cx('size-unit', { 'is-on': unit === name })} onClick={() => setUnit(name)}>
            {name}
          </button>
        ))}
      </div>
    </>
  )
}
