// src/components/modules/panel/wrap/TempListWrap.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-27 15:16:07
 * @Description: 模板列表
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @Date: 2024-03-06 21:16:00
-->
<template>
  <div class="wrap">
    <search-header v-model="state.searchKeyword" @change="cateChange" />

    <el-divider v-show="state.title" style="margin-top: 1.7rem" content-position="left">
      <span style="font-weight: bold">{{ state.title }}</span>
    </el-divider>

    <el-button class="upload-psd" plain type="primary" @click="openPSD">Import a PSD file</el-button>

    <ul ref="listRef" v-infinite-scroll="load" class="infinite-list" :infinite-scroll-distance="150" style="overflow: auto">
      <img-water-fall :listData="state.list" @select="selectItem" />
      <div v-show="state.loading" class="loading"><i class="el-icon-loading"></i> Loading</div>
      <div v-show="state.loadDone" class="loading">That is everything</div>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import { reactive, ref } from 'vue'
import api from '@/api'

import { LocationQueryValue, useRoute, useRouter } from 'vue-router'
// import chooseType from './components/chooseType.vue'
// import editModel from './components/editModel.vue'
import searchHeader from './components/searchHeader.vue'
import useConfirm from '@/common/methods/confirm'
// import { useSetupMapGetters } from '@/common/hooks/mapGetters'
import imgWaterFall from './components/imgWaterFall.vue'
import { IGetTempListData } from '@/api/home'
import { useControlStore, useCanvasStore, useUserStore, useHistoryStore, useWidgetStore, useForceStore } from '@/store'
import { storeToRefs } from 'pinia'

type TState = {
  loading: boolean
  loadDone: boolean
  list: IGetTempListData[]
  title: string
  searchKeyword: string
}

type TPageOptions = {
  page: number
  pageSize: number
  cate: number | string
  state?: string
}

const listRef = ref<HTMLElement | null>(null)
const route = useRoute()
const router = useRouter()

const controlStore = useControlStore()

const userStore = useUserStore()
const pageStore = useCanvasStore()
const widgetStore = useWidgetStore()
const forceStore = useForceStore()
const state = reactive<TState>({
  loading: false,
  loadDone: false,
  list: [],
  title: 'Sample templates',
  searchKeyword: '',
})

// const { tempEditing } = useSetupMapGetters(['tempEditing'])
const { dHistoryParams } = storeToRefs(useHistoryStore())

const pageOptions: TPageOptions = { page: 0, pageSize: 20, cate: 1 }
const { cate, edit } = route.query
cate && (pageOptions.cate = (cate as LocationQueryValue) ?? 1)
// edit && store.commit('managerEdit', true)
edit && userStore.managerEdit(true)

// onMounted(async () => {})

const load = async (init: boolean = false, stat?: string) => {
  stat && (pageOptions.state = stat)

  if (init && listRef.value) {
    listRef.value.scrollTop = 0
    state.list = []
    pageOptions.page = 0
    state.loadDone = false
  }
  if (state.loadDone || state.loading) {
    return
  }

  state.loading = true
  pageOptions.page += 1

  const res = await api.home.getTempList({ search: state.searchKeyword, ...pageOptions })
  res.list.length <= 0 && (state.loadDone = true)
  state.list = state.list.concat(res.list)
  setTimeout(() => {
    state.loading = false
    checkHeight()
  }, 100)
}

function cateChange(type: any) {
  state.title = type.name
  const init = pageOptions.cate != type.id
  pageOptions.cate = type.id
  load(init, pageOptions.state)
}

function checkHeight() {
  if (!listRef.value) return
  // 检查高度是否占满，否则继续请求下一页
  const isLess = listRef.value.offsetHeight > (listRef.value.firstElementChild as HTMLElement)?.offsetHeight
  isLess && load()
}

let hideReplacePrompt: any = localStorage.getItem('hide_replace_prompt')
async function selectItem(item: IGetTempListData) {
  controlStore.setShowMoveable(false) // Clear the previous selection box
  if (!hideReplacePrompt && dHistoryParams.value.length > 0) {
    const doNotPrompt = await useConfirm('Add to my designs', 'This template will replace everything on the page.', 'warning', { confirmButtonText: 'Got it', cancelButtonText: 'Do not show again' })
    if (!doNotPrompt) {
      localStorage.setItem('hide_replace_prompt', '1')
      hideReplacePrompt = true
    }
  }
  userStore.managerEdit(false)
  widgetStore.setDWidgets([])
  setTempId(item.id)

  let result = null
  if (!item.data) {
    const res = await api.home.getTempDetail({ id: item.id })
    result = JSON.parse(res.data)
  } else {
    result = JSON.parse(item.data)
  }
  if (Array.isArray(result)) {
    const { global, layers } = result[0]
    pageStore.setDPage(global)
    widgetStore.setTemplate(layers)
  } else {
    const { page, widgets } = result
    pageStore.setDPage(page)
    widgetStore.setTemplate(widgets)
  }
  setTimeout(() => {
    forceStore.setZoomScreenChange()
  }, 300)
  widgetStore.selectWidget({
    uuid: '-1',
  })
}

function setTempId(tempId: number | string) {
  const { id } = route.query
  router.push({ path: '/home', query: { tempid: tempId, id }, replace: true })
}

const openPSD = () => {
  window.open(router.resolve('/psd').href, '_blank')
}

defineExpose({
  load,
  cateChange,
  listRef,
})
</script>

<style lang="less" scoped>
.wrap {
  width: 100%;
  height: 100%;
}

.infinite-list {
  height: 100%;
  margin-top: 1rem;
  padding-bottom: 150px;
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* IE 10+ */
}
.infinite-list::-webkit-scrollbar {
  display: none; /* Chrome Safari */
}
// .list {
//   width: 100%;
//   padding: 4px 0 0 10px;
//   &__img {
//     cursor: pointer;
//     width: 128px;
//     height: auto;
//     position: relative;
//     &-mask {
//       opacity: 0;
//       width: 100%;
//       height: 100%;
//       background: rgba(0, 0, 0, 0.12);
//       position: absolute;
//       z-index: 1;
//       top: 0;
//       left: 0;
//     }
//   }
//   &__img:hover {
//     background: rgba(0, 0, 0, 0.04);
//   }
//   &__img:hover > &__img-mask {
//     opacity: 1;
//   }
// }

.loading {
  padding-top: 1rem;
  text-align: center;
  font-size: 14px;
  color: #999;
}

.upload-psd {
  margin: 0 1rem;
  width: calc(100% - 2rem);
}
</style>

// react/src/components/modules/panel/wrap/TempListWrap.tsx
import { useCallback, useRef, useState } from 'react'
import api from '@/api'
import type { IGetTempListData } from '@/api/home'
import useConfirm from '@/common/methods/confirm'
import useInfiniteScroll from '@/common/hooks/useInfiniteScroll'
import { readQuery, replaceQuery } from '@/common/hooks/useRouteQuery'
import Button from '@/components/ui/Button'
import Divider from '@/components/ui/Divider'
import { setShowMoveable } from '@/store/control'
import { setZoomScreenChange } from '@/store/force'
import { managerEdit } from '@/store/base'
import { setDPage } from '@/store/canvas'
import { historyState } from '@/store/state'
import { selectWidget, setDWidgets, setTemplate } from '@/store/widget'
import SearchHeader from './components/SearchHeader'
import ImgWaterFall from './components/ImgWaterFall'
import './tempListWrap.less'

type TPageOptions = {
  page: number
  pageSize: number
  cate: number | string
  state?: string
}

export default function TempListWrap() {
  const listRef = useRef<HTMLUListElement | null>(null)
  const [loading, setLoading] = useState(false)
  const [loadDone, setLoadDone] = useState(false)
  const [list, setList] = useState<IGetTempListData[]>([])
  const [title, setTitle] = useState('Sample templates')
  const [searchKeyword, setSearchKeyword] = useState('')

  const keywordRef = useRef('')
  keywordRef.current = searchKeyword
  const loadingRef = useRef(false)
  const doneRef = useRef(false)
  const pageOptions = useRef<TPageOptions>({ page: 0, pageSize: 20, cate: 1 })
  const initialised = useRef(false)

  if (!initialised.current) {
    initialised.current = true
    const { cate, edit } = readQuery()
    cate && (pageOptions.current.cate = cate ?? 1)
    edit && managerEdit(true)
  }

  const load = useCallback(async (init: boolean = false, stat?: string) => {
    stat && (pageOptions.current.state = stat)

    if (init && listRef.current) {
      listRef.current.scrollTop = 0
      setList([])
      pageOptions.current.page = 0
      doneRef.current = false
      setLoadDone(false)
    }
    if (doneRef.current || loadingRef.current) {
      return
    }

    loadingRef.current = true
    setLoading(true)
    pageOptions.current.page += 1

    const res = await api.home.getTempList({ search: keywordRef.current, ...pageOptions.current })
    if (res.list.length <= 0) {
      doneRef.current = true
      setLoadDone(true)
    }
    setList((prev) => (init ? res.list : prev.concat(res.list)))
    setTimeout(() => {
      loadingRef.current = false
      setLoading(false)
      checkHeight()
    }, 100)
  }, [])

  useInfiniteScroll(listRef, load)

  const started = useRef(false)
  if (!started.current) {
    started.current = true
    load()
  }

  function checkHeight() {
    if (!listRef.current) return
    const isLess = listRef.current.offsetHeight > (listRef.current.firstElementChild as HTMLElement)?.offsetHeight
    isLess && load()
  }

  function searchChange() {
    load(true, pageOptions.current.state)
  }

  function cateChange(type: any) {
    setTitle(type.name)
    const init = pageOptions.current.cate != type.id
    pageOptions.current.cate = type.id
    load(init, pageOptions.current.state)
  }

  let hideReplacePrompt: any = localStorage.getItem('hide_replace_prompt')
  async function selectItem(item: IGetTempListData) {
    setShowMoveable(false)
    if (!hideReplacePrompt && historyState.dHistoryParams.length > 0) {
      const doNotPrompt = await useConfirm(
        'Add to my designs',
        'This template will replace everything on the page.',
        'warning',
        { confirmButtonText: 'Got it', cancelButtonText: 'Do not show again' },
      )
      if (!doNotPrompt) {
        localStorage.setItem('hide_replace_prompt', '1')
        hideReplacePrompt = true
      }
    }
    managerEdit(false)
    setDWidgets([])
    setTempId(item.id)

    let result = null
    if (!item.data) {
      const res = await api.home.getTempDetail({ id: item.id })
      result = JSON.parse(res.data)
    } else {
      result = JSON.parse(item.data)
    }
    if (Array.isArray(result)) {
      const { global, layers } = result[0]
      setDPage(global)
      setTemplate(layers)
    } else {
      const { page, widgets } = result
      setDPage(page)
      setTemplate(widgets)
    }
    setTimeout(() => {
      setZoomScreenChange()
    }, 300)
    selectWidget({ uuid: '-1' })
  }

  function setTempId(tempId: number | string) {
    const { id } = readQuery()
    replaceQuery({ tempid: String(tempId), id })
  }

  const openPSD = () => {
    window.open('/psd', '_blank')
  }

  return (
    <div className="wrap temp-list-wrap">
      <SearchHeader value={searchKeyword} onChange={setSearchKeyword} onCateChange={cateChange} onSearch={searchChange} />

      {title ? (
        <Divider style={{ marginTop: '1.7rem' }} contentPosition="left">
          <span style={{ fontWeight: 'bold' }}>{title}</span>
        </Divider>
      ) : null}

      <Button className="upload-psd" plain type="primary" onClick={openPSD}>
        Import a PSD file
      </Button>

      <ul ref={listRef} className="infinite-list" style={{ overflow: 'auto' }}>
        <ImgWaterFall listData={list} onSelect={selectItem} />
        {loading ? (
          <div className="loading">
            <i className="el-icon-loading" /> Loading
          </div>
        ) : null}
        {loadDone ? <div className="loading">That is everything</div> : null}
      </ul>
    </div>
  )
}
