// src/views/Psd.tsx
import { useEffect, useRef, useState } from 'react'
import RcMenu from '@/components/business/right-click-menu/RcMenu'
import Moveable from '@/components/business/moveable/Moveable'
import DesignBoard from '@/components/modules/layout/designBoard/DesignBoard'
import ZoomControl, { type ZoomControlHandle } from '@/components/modules/layout/zoomControl/ZoomControl'
import StylePanel from '@/components/modules/panel/StylePanel'
import ProgressLoading from '@/components/common/ProgressLoading/ProgressLoading'
import Uploader from '@/components/common/Uploader/Uploader'
import Button from '@/components/ui/Button'
import { UploadFilledIcon } from '@/components/ui/icons'
import useLoading from '@/common/methods/loading'
import { readQuery } from '@/common/hooks/useRouteQuery'
import { handleKeydowm, handleKeyup } from '@/mixins/shortcuts'
import WebWorker from '@/utils/plugins/webWorker'
import psdWorker from '../utils/plugins/worker/loadPSD.worker?worker'
import { createBase64 } from '@/utils/plugins/psd'
import wImageSetting from '@/components/modules/widgets/wImage/wImageSetting'
import { wTextSetting } from '@/components/modules/widgets/wText/wTextSetting'
import { wGroupSetting } from '@/components/modules/widgets/wGroup/groupSetting'
import { canvasState, widgetState } from '@/store/state'
import { setDPage } from '@/store/canvas'
import { setShowMoveable } from '@/store/control'
import { initGroupJson } from '@/store/group'
import { addWidget, selectWidget, setDWidgets } from '@/store/widget'
import { useSnapshot } from 'valtio'
import UploadTemplate, { type TEmitChangeData } from './components/UploadTemplate'
import './psd.less'

const types: Record<string, any> = {
  text: wTextSetting,
  image: wImageSetting,
}

export default function Psd() {
  const canvas = useSnapshot(canvasState)
  // Starts true so the zoom control mounts once and sizes the page, exactly as
  // the original does, then drops to false to show the drop zone.
  const [isDone, setIsDone] = useState(true)
  const [downloadPercent, setDownloadPercent] = useState(0)
  const [downloadText, setDownloadText] = useState('')
  const [downloadMsg, setDownloadMsg] = useState('')
  const [cancelText, setCancelText] = useState('')
  const zoomControlRef = useRef<ZoomControlHandle | null>(null)
  const worker = useRef<WebWorker | null>(null)
  const loading = useRef<ReturnType<typeof useLoading> | null>(null)

  useEffect(() => {
    initGroupJson(JSON.stringify(wGroupSetting))
    worker.current = new WebWorker(psdWorker)
    zoomControlRef.current?.screenChange()
    setIsDone(false)

    const instanceFn = { save: () => {}, zoomAdd: () => zoomControlRef.current?.add(), zoomSub: () => zoomControlRef.current?.sub() }
    const onKeyDown = handleKeydowm(instanceFn)
    const onKeyUp = handleKeyup()
    document.addEventListener('keydown', onKeyDown, false)
    document.addEventListener('keyup', onKeyUp, false)
    return () => {
      document.removeEventListener('keydown', onKeyDown, false)
      document.removeEventListener('keyup', onKeyUp, false)
      document.oncontextmenu = null
    }
  }, [])

  async function selectFile(file: File) {
    loading.current = useLoading()
    await loadPSD(file)
    loading.current.close()
    setIsDone(true)
  }

  async function loadPSD(file: File) {
    const { data }: any = await worker.current!.start(file)

    for (let i = 0; i < data.clouds.length; i++) {
      const x: any = data.clouds[i]
      const rawData = JSON.parse(JSON.stringify(types[x.type])) || {}
      delete x.type
      x.src && (x.imgUrl = createBase64(x.src, { width: x.width, height: x.height })) && delete x.src
      addWidget(Object.assign(rawData, x))
    }

    const { width, height, background: bg } = data
    setDPage(
      Object.assign(canvasState.dPage, {
        width,
        height,
        backgroundColor: bg.color,
        backgroundImage: createBase64(bg.image, { width, height }),
      }),
    )
    await loadDone()
  }

  async function loadDone() {
    await nextPaint()
    zoomControlRef.current?.screenChange()
    setTimeout(() => {
      selectWidget({ uuid: '-1' })
    }, 100)
  }

  async function clear() {
    setDWidgets([])
    setDPage(Object.assign(canvasState.dPage, { width: 1920, height: 1080, backgroundColor: '#ffffff', backgroundImage: '' }))
    setShowMoveable(false)
    await nextPaint()
    setIsDone(false)
  }

  function optionsChange({ downloadPercent: percent, downloadText: text, downloadMsg: msg = '', cancelText: cancel = '' }: TEmitChangeData) {
    typeof percent === 'number' && setDownloadPercent(percent)
    setDownloadText(text)
    setDownloadMsg(msg)
    setCancelText(cancel)
  }

  function cancel() {
    setDownloadPercent(100)
    const { id } = readQuery()
    window.open(`${window.location.protocol + '//' + window.location.host}/home?id=${id}`)
  }

  const shelterWidth = (canvas.dPage.width * canvas.dZoom) / 100 + 'px'
  const shelterHeight = (canvas.dPage.height * canvas.dZoom) / 100 + 'px'

  return (
    <div id="page-design-index" className="ds-psd-view">
      <div className="top-nav">
        <div className="top-nav-wrap">
          <div className="top-left">
            <div className="name" style={{ fontSize: 15 }}>
              PSD import
            </div>
          </div>
          <div style={{ flex: 1 }} />
          {isDone ? <Button onClick={clear}>Clear template</Button> : null}
          <div className="v-tips">
            <UploadTemplate isDone={isDone} onChange={optionsChange} />
          </div>
        </div>
      </div>

      <div className="page-design-index-wrap">
        <DesignBoard className="page-design-wrap" pageDesignCanvasId="page-design-canvas">
          {isDone ? (
            <div className="shelter" style={{ width: shelterWidth, height: shelterHeight }} />
          ) : (
            <Uploader hold drag accept=".psd" className="uploader" onLoad={selectFile}>
              <div className="uploader__box">
                <UploadFilledIcon style={{ width: 48, height: 48, marginRight: '1rem' }} />
                <div className="uploader__copy">
                  <span>Drop a PSD file here, or choose one</span>
                  <span className="uploader__hint">
                    Text, pictures and shapes arrive as separate layers. Effects, masks and adjustment layers are flattened.
                  </span>
                </div>
              </div>
            </Uploader>
          )}
        </DesignBoard>
        <div style={{ display: isDone ? 'contents' : 'none' }}>
          <StylePanel />
        </div>
      </div>
      {isDone ? <ZoomControl ref={zoomControlRef} /> : null}
      <RcMenu />
      <Moveable />
      <ProgressLoading
        percent={downloadPercent}
        text={downloadText}
        cancelText={cancelText}
        msg={downloadMsg}
        onCancel={cancel}
        onDone={() => setDownloadPercent(0)}
      />
    </div>
  )
}

function nextPaint() {
  return new Promise<void>((resolve) => requestAnimationFrame(() => resolve()))
}

// src/views/Psd.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-01-10 14:57:53
 * @Description: Psd文件解析
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2025-01-15 22:05:57
-->
<template>
  <div id="page-design-index" ref="pageDesignIndex">
    <div class="top-nav">
      <div class="top-nav-wrap">
        <div class="top-left">
          <div class="name" style="font-size: 15px">PSD import</div>
        </div>
        <div style="flex: 1"></div>
        <el-button v-show="state.isDone" @click="clear">Clear template</el-button>
        <div class="v-tips">
          <HeaderOptions :isDone="state.isDone" @change="optionsChange" />
        </div>
      </div>
    </div>

    <div class="page-design-index-wrap">
      <!-- <widget-panel></widget-panel> -->
      <design-board class="page-design-wrap" pageDesignCanvasId="page-design-canvas">
        <div v-if="state.isDone" class="shelter" :style="{ width: (dPage.width * dZoom) / 100 + 'px', height: (dPage.height * dZoom) / 100 + 'px' }"></div>
        <uploader v-else accept=".psd" :hold="true" :drag="true" class="uploader" @load="selectFile">
          <div class="uploader__box">
            <upload-filled style="width: 48px; height: 48px; margin-right: 1rem" />
            <div class="uploader__copy">
              <span>Drop a PSD file here, or choose one</span>
              <span class="uploader__hint">Text, pictures and shapes arrive as separate layers. Effects, masks and adjustment layers are flattened.</span>
            </div>
          </div>
        </uploader>
      </design-board>
      <style-panel v-show="state.isDone"></style-panel>
    </div>
    <!-- 缩放控制 -->
    <zoom-control v-if="state.isDone" ref="zoomControlRef" />
    <!-- 右键菜单 -->
    <right-click-menu />
    <!-- 旋转缩放组件 -->
    <Moveable />
    <!-- 遮罩百分比进度条 -->
    <ProgressLoading :percent="state.downloadPercent" :text="state.downloadText" :cancelText="state.cancelText" :msg="state.downloadMsg" @cancel="cancel" @done="state.downloadPercent = 0" />
  </div>
</template>

<script lang="ts" setup>
import { reactive, onMounted, nextTick, onBeforeMount, ref, getCurrentInstance } from 'vue'
import { useRoute } from 'vue-router'
import RightClickMenu from '@/components/business/right-click-menu/RcMenu.vue'
import Moveable from '@/components/business/moveable/Moveable.vue'
import shortcuts from '@/mixins/shortcuts'
// import wText from '@/components/modules/widgets/wText/wText.vue'
// import wImage from '@/components/modules/widgets/wImage/wImage.vue'
import wImageSetting from '@/components/modules/widgets/wImage/wImageSetting'
import useLoading from '@/common/methods/loading'
import uploader from '@/components/common/Uploader/index.vue'
import { UploadFilled } from '@element-plus/icons-vue'
import designBoard from '@/components/modules/layout/designBoard/index.vue'
import zoomControl from '@/components/modules/layout/zoomControl/index.vue'
import HeaderOptions, { TEmitChangeData } from './components/UploadTemplate.vue'
import ProgressLoading from '@/components/common/ProgressLoading/index.vue'
import useWorker from '@/utils/plugins/webWorker'
import psdWorker from '../utils/plugins/worker/loadPSD.worker.ts?worker'
// import { processPSD2Page } from '@/utils/plugins/psd'
import { createBase64 } from '@/utils/plugins/psd'
// import { useSetupMapGetters } from '@/common/hooks/mapGetters'
import { wTextSetting } from '@/components/modules/widgets/wText/wTextSetting'
import { useCanvasStore, useControlStore, useWidgetStore, useGroupStore } from '@/store'
import { storeToRefs } from 'pinia'
import { wGroupSetting } from '@/components/modules/widgets/wGroup/groupSetting'

type TState = {
  isDone: boolean
  downloadPercent: number // Download progress
  downloadText: string
  downloadMsg: string
  cancelText: string
}

// mixins: [shortcuts],
const state = reactive<TState>({
  isDone: true,
  downloadPercent: 0, // Download progress
  downloadText: '',
  downloadMsg: '',
  cancelText: '',
})
const widgetStore = useWidgetStore()
const controlStore = useControlStore()

const route = useRoute()

// const { dZoom } = useSetupMapGetters(['dZoom'])
const groupStore = useGroupStore()
const pageStore = useCanvasStore()
const { dPage } = storeToRefs(pageStore)
const { dZoom } = storeToRefs(useCanvasStore())

const zoomControlRef = ref<typeof zoomControl | null>()

let loading: ReturnType<typeof useLoading> | null = null
const myWorker = new useWorker(psdWorker)

onMounted(async () => {
  groupStore.initGroupJson(JSON.stringify(wGroupSetting))
  await nextTick()
  if (zoomControlRef.value) {
    zoomControlRef.value.screenChange()
  }
  state.isDone = false
})

async function selectFile(file: File) {
  loading = useLoading()
  await loadPSD(file)
  loading.close()
  state.isDone = true
}

const types: any = {
  text: wTextSetting,
  image: wImageSetting,
}

async function loadPSD(file: File) {
  // const { compositeBuffer, psdFile } = await myWorker.start(file)
  const { data }: any = await myWorker.start(file)
  // const data = await processPSD2Page(file)

  for (let i = 0; i < data.clouds.length; i++) {
    const x: any = data.clouds[i]
    const rawData = JSON.parse(JSON.stringify(types[x.type])) || {}
    delete x.type
    x.src && (x.imgUrl = createBase64(x.src, { width: x.width, height: x.height })) && delete x.src
    widgetStore.addWidget(Object.assign(rawData, x))
  }

  const { width, height, background: bg } = data
  pageStore.setDPage(Object.assign(pageStore.dPage, { width, height, backgroundColor: bg.color, backgroundImage: createBase64(bg.image, { width, height }) }))
  await loadDone()
}

async function clear() {
  widgetStore.setDWidgets([])
  pageStore.setDPage(Object.assign(pageStore.dPage, { width: 1920, height: 1080, backgroundColor: '#ffffff', backgroundImage: '' }))
  controlStore.setShowMoveable(false)

  await nextTick()
  state.isDone = false
}

const optionsChange = ({ downloadPercent, downloadText, downloadMsg = '', cancelText = '' }: TEmitChangeData) => {
  typeof downloadPercent === 'number' && (state.downloadPercent = downloadPercent)
  state.downloadText = downloadText
  state.downloadMsg = downloadMsg
  state.cancelText = cancelText
}

const cancel = () => {
  state.downloadPercent = 100
  window.open(`${window.location.protocol + '//' + window.location.host}/home?id=${route.query.id}`)
}

const { handleKeydowm, handleKeyup, dealCtrl } = shortcuts.methods

// ...mapGetters(['dPage', 'dZoom']),

let checkCtrl: number | undefined

onMounted(() => {
  const instance = getCurrentInstance()
  document.addEventListener('keydown', handleKeydowm(controlStore, checkCtrl, instance, dealCtrl), false)
  document.addEventListener('keyup', handleKeyup(controlStore, checkCtrl), false)
})

onBeforeMount(() => {
  const instance = getCurrentInstance()
  document.removeEventListener('keydown', handleKeydowm(controlStore, checkCtrl, instance, dealCtrl), false)
  document.removeEventListener('keyup', handleKeyup(controlStore, checkCtrl), false)
  document.oncontextmenu = null
})
// ...mapActions(['selectWidget']),

async function loadDone() {
  await nextTick()
  if (!zoomControlRef.value) return
  zoomControlRef.value.screenChange()
  setTimeout(() => {
    widgetStore.selectWidget({ uuid: '-1' })
    // store.dispatch('selectWidget', { uuid: '-1' })
    // selectWidget({
    //   uuid: '-1',
    // })
    // this.$store.commit('setShowMoveable', false)
  }, 100)
}
defineExpose({
  selectFile,
  clear,
  cancel,
  optionsChange,
})
</script>

<style lang="less" scoped>
@import url('@/assets/styles/design.less');
.uploader {
  position: absolute;
  z-index: 999;
  left: 50%;
  transform: translate(-50%, -50%);
  top: 50%;
  &__box {
    color: @ink-2;
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    height: 100%;
  }
  &__copy {
    display: flex;
    flex-direction: column;
    gap: 4px;
    text-align: left;
  }
  &__hint {
    color: @ink-3;
    font-size: @text-sm;
    max-width: 34ch;
    line-height: 1.4;
  }
}
.v-tips {
  padding: 0 1rem;
  font-size: 15px;
  color: @ink-2;
}
</style>
