// src/components/business/qrcode/index.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2022-03-16 09:15:52
 * @Description:  
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @Date: 2024-03-04 18:50:00
-->
<template>
  <div ref="qrCodeDom" class="qrcode__wrap"></div>
</template>

<script lang="ts" setup>
import { onMounted, ref, watch, nextTick } from 'vue'
import QRCodeStyling, { Options } from 'qr-code-styling'
import { debounce } from 'throttle-debounce'
import { generateOption } from './method'

export type TQrcodeProps = {
  width?: number
  height?: number
  image?: string
  value?: string
  dotsOptions: Options['dotsOptions']
}

const props = withDefaults(defineProps<TQrcodeProps>(), {
  width: 300,
  height: 300,
  dotsOptions: () => ({
    color: '#41b583',
    type: 'rounded',
  })
})

let options: Options = {}
watch(
  () => [props.width, props.height, props.dotsOptions],
  () => {
    render()
  },
)

const render = debounce(300, false, async () => {
  options = generateOption(props)
  if (props.value) {
    options && qrCode.update(options)
    await nextTick()
    if (!qrCodeDom?.value?.firstChild) return
    (qrCodeDom.value.firstChild as HTMLElement).setAttribute('style', "width: 100%;") // Force it to refit
  }
})

const qrCode = new QRCodeStyling(options)
const qrCodeDom = ref<HTMLElement>()

onMounted(() => {
  render()
  qrCode.append(qrCodeDom.value)
})

</script>

// react/src/components/business/qrcode/QrCode.tsx
import { useEffect, useRef } from 'react'
import QRCodeStyling, { type Options } from 'qr-code-styling'
import { debounce } from 'throttle-debounce'
import { generateOption } from './method'

export type TQrcodeProps = {
  width?: number
  height?: number
  image?: string
  value?: string
  dotsOptions?: Options['dotsOptions']
  className?: string
}

const defaultDots: Options['dotsOptions'] = { color: '#41b583', type: 'rounded' }

export default function QrCode({ width = 300, height = 300, image, value, dotsOptions = defaultDots, className }: TQrcodeProps) {
  const domRef = useRef<HTMLDivElement | null>(null)
  const qrCodeRef = useRef<QRCodeStyling | null>(null)
  const propsRef = useRef({ width, height, image, value, dotsOptions })
  propsRef.current = { width, height, image, value, dotsOptions }

  const renderRef = useRef(
    debounce(300, false, () => {
      const qrCode = qrCodeRef.current
      if (!qrCode) return
      const options = generateOption(propsRef.current)
      if (propsRef.current.value) {
        options && qrCode.update(options)
        requestAnimationFrame(() => {
          const first = domRef.current?.firstChild as HTMLElement | null
          if (!first) return
          first.setAttribute('style', 'width: 100%;')
        })
      }
    }),
  )

  useEffect(() => {
    qrCodeRef.current = new QRCodeStyling({})
    renderRef.current()
    domRef.current && qrCodeRef.current.append(domRef.current)
  }, [])

  useEffect(() => {
    renderRef.current()
  }, [width, height, image, value, dotsOptions])

  return <div ref={domRef} className={className ? `qrcode__wrap ${className}` : 'qrcode__wrap'} />
}
