// src/components/business/save-download/CreateCover.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-01 11:12:17
 * @Description: 前端出图 - 用于封面
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @Date: 2024-03-04 18:50:00
-->
<template>
  <div id="cover-wrap"></div>
</template>

<script lang="ts" setup>
import html2canvas from 'html2canvas'
import Qiniu from '@/common/methods/QiNiu'
// import { useSetupMapGetters } from '@/common/hooks/mapGetters'
import { storeToRefs } from 'pinia'
import { useCanvasStore, useWidgetStore } from '@/store'
import FontFaceObserver from 'fontfaceobserver'

// const { dZoom } = useSetupMapGetters(['dZoom'])

const canvasStore = useCanvasStore()
const widgetStore = useWidgetStore()
const { dZoom } = storeToRefs(canvasStore)

// props: ['modelValue'],
// emits: ['update:modelValue'],

async function createCover(cb: any) {
  const nowZoom = dZoom.value
  // Deselect元素
  widgetStore.selectWidget({
    uuid: '-1',
  })
  // store.dispatch('selectWidget', {
  //   uuid: '-1',
  // })

  canvasStore.updateZoom(100)
  // store.dispatch('updateZoom', 100)

  const opts = {
    useCORS: true, // 跨域图片
    scale: 0.2,
  }
  setTimeout(async () => {
    const clonePage = document.getElementById('page-design-canvas')?.cloneNode(true) as HTMLElement
    if (!clonePage) return
    clonePage.setAttribute('id', 'clone-page')
    document.body.appendChild(clonePage)
    html2canvas(clonePage, opts).then((canvas) => {
      canvas.toBlob(
        async (blobObj) => {
          if (blobObj) {
            const result = await Qiniu.upload(blobObj, { bucket: 'xp-design', prePath: 'cover/user' })
            cb(result)
          }
        },
        'image/jpeg',
        0.15,
      )
      canvasStore.updateZoom(nowZoom)
      // store.dispatch('updateZoom', nowZoom)
      clonePage.remove()
    })
  }, 10)
}

async function createPoster() {
  await checkFonts() // Wait for the fonts to finish loading
  const fonts = document.fonts
  const opts = {
    backgroundColor: null, // No background, so transparent PNGs work
    useCORS: true,
    scale: 100 / dZoom.value, // * window.devicePixelRatio
    onclone: (document: any) => fonts.forEach((font) => document.fonts.add(font)),
  }
  // const style = document.createElement('style')
  // document.head.appendChild(style)
  // style.sheet?.insertRule('body > img { display: initial; }')
  return new Promise((resolve) => {
    const clonePage = document.getElementById('page-design-canvas')?.cloneNode(true) as HTMLElement
    if (!clonePage) return
    clonePage.setAttribute('id', 'clone-page')
    document.body.appendChild(clonePage)
    html2canvas(clonePage, opts).then((canvas) => {
      canvas.toBlob(async (blob) => resolve({ blob }), `image/png`)
      clonePage.remove()
    })
  })
}

// 检查字体是否加载完成
async function checkFonts() {
  const widgets = widgetStore.getWidgets()
  const fontLoaders: Promise<void>[] = []
  widgets.forEach((item: any) => {
    if (item.fontClass && item.fontClass.value) {
      const loader = new FontFaceObserver(item.fontClass.value)
      fontLoaders.push(loader.load(null, 120000)) // A long timeout so slow fonts still get picked up
    }
  })
  await Promise.all(fontLoaders)
}

defineExpose({
  createCover,
  createPoster,
})
</script>

<style lang="less">
#clone-page {
  position: absolute;
  z-index: 99999;
  left: -99999px;
}
</style>

// react/src/components/business/save-download/CreateCover.tsx
import { forwardRef, useImperativeHandle } from 'react'
import html2canvas from 'html2canvas'
import FontFaceObserver from 'fontfaceobserver'
import Qiniu from '@/common/methods/QiNiu'
import { canvasState } from '@/store/state'
import { updateZoom } from '@/store/canvas'
import { selectWidget } from '@/store/widget/select'
import { getWidgets } from '@/store/widget/widget'
import './createCover.less'

export type CreateCoverHandle = {
  createCover: (cb: (result: any) => void) => Promise<void>
  createPoster: () => Promise<{ blob: Blob | null }>
}

const CreateCover = forwardRef<CreateCoverHandle>(function CreateCover(_props, ref) {
  async function createCover(cb: (result: any) => void) {
    const nowZoom = canvasState.dZoom
    selectWidget({ uuid: '-1' })
    updateZoom(100)

    const opts = {
      useCORS: true,
      scale: 0.2,
    }
    setTimeout(async () => {
      const clonePage = document.getElementById('page-design-canvas')?.cloneNode(true) as HTMLElement
      if (!clonePage) return
      clonePage.setAttribute('id', 'clone-page')
      document.body.appendChild(clonePage)
      html2canvas(clonePage, opts).then((canvas) => {
        canvas.toBlob(
          async (blobObj) => {
            if (blobObj) {
              const result = await Qiniu.upload(blobObj, { bucket: 'xp-design', prePath: 'cover/user' })
              cb(result)
            }
          },
          'image/jpeg',
          0.15,
        )
        updateZoom(nowZoom)
        clonePage.remove()
      })
    }, 10)
  }

  async function createPoster(): Promise<{ blob: Blob | null }> {
    await checkFonts()
    const fonts = document.fonts
    const opts = {
      backgroundColor: null,
      useCORS: true,
      scale: 100 / canvasState.dZoom,
      onclone: (doc: any) => fonts.forEach((font) => doc.fonts.add(font)),
    }
    return new Promise((resolve) => {
      const clonePage = document.getElementById('page-design-canvas')?.cloneNode(true) as HTMLElement
      if (!clonePage) return resolve({ blob: null })
      clonePage.setAttribute('id', 'clone-page')
      document.body.appendChild(clonePage)
      html2canvas(clonePage, opts as any).then((canvas) => {
        canvas.toBlob(async (blob) => resolve({ blob }), `image/png`)
        clonePage.remove()
      })
    })
  }

  async function checkFonts() {
    const widgets = getWidgets()
    const fontLoaders: Promise<void>[] = []
    widgets.forEach((item: any) => {
      if (item.fontClass && item.fontClass.value) {
        const loader = new FontFaceObserver(item.fontClass.value)
        fontLoaders.push(loader.load(null, 120000))
      }
    })
    await Promise.all(fontLoaders)
  }

  useImperativeHandle(ref, () => ({ createCover, createPoster }), [])

  return <div id="cover-wrap" />
})

export default CreateCover
