// src/views/components/Helper.tsx
import { useState, type ReactNode } from 'react'
import Dropdown, { DropdownItem } from '@/components/ui/DropdownMenu'
import Divider from '@/components/ui/Divider'
import scKeyCodes from '@/mixins/scKeyCodes'
import './helper.less'

export default function Helper({ onSelect, children }: { onSelect: (name: string) => void; children: ReactNode }) {
  const [type, setType] = useState<'menu' | 'shortkey'>('menu')
  const [open, setOpen] = useState(false)

  const openTour = () => {
    onSelect('openTour')
    setOpen(false)
  }

  const openIssues = () => {
    window.open('https://github.com/palxiao/poster-design/issues', '_blank')
  }

  return (
    <Dropdown
      placement="bottom-start"
      size="large"
      maxHeight="70vh"
      menuClassName="ds-helper-menu"
      open={open}
      onOpenChange={(next) => {
        setOpen(next)
        if (!next) setType('menu')
      }}
      menu={
        type === 'shortkey' ? (
          <div className="help-list">
            <div onClick={() => setType('menu')} className="back">
              <span className="icon-box">
                <i className="iconfont icon-right" />
              </span>{' '}
              <b>Keyboard shortcuts</b>
            </div>
            <Divider />
            {scKeyCodes.map((sc, si) => (
              <div key={'sc' + si} className="item">
                <span className="title">{sc.feat}</span>
                <span className="instruct">{sc.info}</span>
              </div>
            ))}
          </div>
        ) : (
          <>
            <DropdownItem closeOnSelect={false} onSelect={() => setType('shortkey')}>
              Keyboard shortcuts
            </DropdownItem>
            <DropdownItem onSelect={openTour}>Take the tour</DropdownItem>
            <DropdownItem onSelect={openIssues}>
              <div className="menu-item">Send feedback</div>
            </DropdownItem>
          </>
        )
      }
    >
      <span className="el-dropdown-link">{children}</span>
    </Dropdown>
  )
}

// src/views/components/Helper.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2024-04-03 19:15:21
 * @Description: 文件 
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-04-05 04:46:03
-->
<template>
  <el-dropdown ref="dropdownRef" max-height="70vh" :hide-on-click="false" trigger="click" size="large" placement="bottom-start">
    <span class="el-dropdown-link">
      <slot />
    </span>
    <template #dropdown>
      <div v-show="type === 'shortkey'" class="help-list">
        <div @click="type = 'menu'" class="back">
          <span class="icon-box"><i class="iconfont icon-right"></i></span> <b>Keyboard shortcuts</b>
        </div>
        <el-divider />
        <div v-for="(sc, si) in scKeyCodes" :key="'sc' + si" class="item">
          <span class="title">{{ sc.feat }}</span
          ><span class="instruct">{{ sc.info }}</span>
        </div>
      </div>
      <el-dropdown-menu v-show="type === 'menu'">
        <el-dropdown-item @click="type = 'shortkey'">Keyboard shortcuts</el-dropdown-item>
        <el-dropdown-item @click="openTour">Take the tour</el-dropdown-item>
        <el-dropdown-item @click="openIssues"><div class="menu-item">Send feedback</div></el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ElDropdown, ElDropdownItem, ElDropdownMenu } from 'element-plus'
import scKeyCodes from '@/mixins/scKeyCodes'
const emit = defineEmits()

const type = ref('menu')
const dropdownRef = ref()

const openTour = () => {
  emit('select', 'openTour')
  dropdownRef.value?.handleClose()
}

const openIssues = () => {
  window.open('https://github.com/palxiao/poster-design/issues', '_blank')
}
</script>

<style lang="less" scoped>
:deep(.el-divider--horizontal) {
  margin: 12px 0;
}
.menu-item {
  width: 170px;
}
.help-list {
  user-select: none;
  .back {
    margin-top: 4px;
    cursor: pointer;
    display: flex;
    padding: 8px 16px 0 6px;
    .icon-box {
      display: inline-block;
      transform: rotate(180deg);
    }
  }
  .item {
    width: 240px;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 16px;
    margin-bottom: 0;
    color: @ink-2;
    white-space: nowrap;
    .title {
      color: @ink;
      font-size: 14px;
      font-weight: 400;
    }
    .instruct {
      padding: 7px 8px;
      margin-left: 14px;
      color: @ink;
      background: @surface-2;
      border-radius: 8px;
    }
  }
}
</style>
