// react/src/components/modules/widgets/wGroup/wGroup.tsx
import { memo, useEffect, useRef } from 'react'
import { useSnapshot } from 'valtio'
import { widgetState } from '@/store/state'
import { updateWidgetData } from '@/store/widget/widget'
import { cx, setTransformAttribute } from '@/utils/dom'
import type { WidgetProps } from '../types'
import './wGroup.less'

function WGroup({ params, parent, id, className, child, children, ...rest }: WidgetProps) {
  const p = useSnapshot(params) as any

  const widgetRef = useRef<HTMLDivElement | null>(null)
  const ratio = useRef(0)
  const temp = useRef<Record<string, any>>({})
  const compWidgetsRecord = useRef<Record<string, any>>({})
  const mounted = useRef(false)

  useEffect(() => {
    updateRecord()
  })

  useEffect(() => {
    touchstart()
    document.addEventListener('mousedown', touchstart, false)
    document.addEventListener('mouseup', touchend, false)
    if (!mounted.current) {
      mounted.current = true
      if (params.rotate && widgetRef.current) {
        widgetRef.current.style.transformOrigin = 'left top'
        widgetRef.current.style.transform += `rotate(${params.rotate})`
      }
    }
    return () => {
      document.removeEventListener('mousedown', touchstart, false)
      document.removeEventListener('mouseup', touchend, false)
    }
  }, [params])

  function updateRecord(tempScale?: number) {
    const active = widgetState.dActiveElement
    if (active?.uuid === params.uuid) {
      const record = active.record
      if (record?.width <= 0) {
        touchend()
      }
      ratio.current = tempScale || (params.width || 0) / record?.width

      if (ratio.current != 1) {
        if (record?.width != 0) {
          for (let i = widgetState.dWidgets.length - 1; i >= 0; --i) {
            const w = widgetState.dWidgets[i]
            if (w.parent === params.uuid) {
              temp.current[w.uuid] = { width: w.width * ratio.current, height: w.height * ratio.current, raw: w }
            }
          }
        }
        if (widgetRef.current) {
          widgetRef.current.style.transformOrigin = 'left top'
          setTransformAttribute(widgetRef.current, 'scale', ratio.current)
        }
      }
    }
  }

  function touchstart() {
    if (widgetState.dActiveElement?.uuid !== params.uuid) {
      return
    }
    for (let i = widgetState.dWidgets.length - 1; i >= 0; --i) {
      const w = widgetState.dWidgets[i]
      if (w.parent === params.uuid) {
        const el = document.getElementById(w.uuid)
        if (el) {
          compWidgetsRecord.current[w.uuid] = {
            left: Number(el.style.left.replace('px', '')),
            top: Number(el.style.top.replace('px', '')),
            fontSize: Number(el.style.fontSize?.replace('px', '')),
          }
        }
      }
    }
  }

  function touchend() {
    if (widgetState.dActiveElement?.uuid !== params.uuid) {
      return
    }
    setTimeout(() => {
      if (!temp.current || !widgetRef.current) {
        return
      }
      widgetRef.current.style.opacity = `${0}`
      setTransformAttribute(widgetRef.current, 'scale', 1)
      setTimeout(() => {
        if (!widgetRef.current) return
        widgetRef.current.style.opacity = `${params.opacity}`
      }, 100)

      for (const key in temp.current) {
        if (Object.hasOwnProperty.call(temp.current, key)) {
          keyChange(key, 'width', temp.current[key].width)
          keyChange(key, 'height', temp.current[key].height)
          keySetValue(key, 'left', compWidgetsRecord.current[key]?.left * ratio.current)
          keySetValue(key, 'top', compWidgetsRecord.current[key]?.top * ratio.current)
          if (temp.current[key].raw.type === 'w-text') {
            keyChange(key, 'fontSize', compWidgetsRecord.current[key]?.fontSize * ratio.current)
          }
        }
      }
      temp.current = {}
      const active = widgetState.dActiveElement
      if (!active) return
      if (active.uuid === params.uuid) {
        const record = active.record
        record.width = widgetRef.current?.offsetWidth
        record.height = widgetRef.current?.offsetHeight
        active.width = widgetRef.current?.offsetWidth as number
        active.height = widgetRef.current?.offsetHeight as number
      }
    }, 10)
  }

  function keyChange(uuid: string, key: string, value: number) {
    updateWidgetData({ uuid, key: key as any, value })
  }

  function keySetValue(uuid: string, key: string, value: number) {
    setTimeout(() => {
      const widget = widgetState.dWidgets.find((item) => item.uuid === uuid)
      if (!widget) return
      ;(widget as any)[key] = value + Number((params as any)[key] || '')
    }, 10)
  }

  return (
    <div
      {...rest}
      id={id ?? params.uuid}
      ref={widgetRef}
      className={cx('w-group', { 'layer-lock': !!p.lock }, className || '')}
      style={{
        position: 'absolute',
        left: (p.left || 0) - (parent?.left || 0) + 'px',
        top: (p.top || 0) - (parent?.top || 0) + 'px',
        width: p.width + 'px',
        height: p.height + 'px',
        opacity: p.opacity,
      }}
    >
      {children}
    </div>
  )
}

export default memo(WGroup)

// src/components/modules/widgets/wGroup/wGroup.vue
<!--
 * @Author: ShawnPhang
 * @Date: 2021-08-02 09:41:41
 * @Description: 
 * @LastEditors: ShawnPhang <https://m.palxp.cn>
 * @LastEditTime: 2024-11-12 13:47:21
-->
<template>
  <div
    ref="widget"
    :class="['w-group', { 'layer-lock': props.params?.lock }]"
    :style="{
      position: 'absolute',
      left: (props.params.left || 0) - (props.parent?.left || 0) + 'px',
      top: (props.params.top || 0) - (props.parent.top || 0) + 'px',
      width: params.width + 'px',
      height: params.height + 'px',
      opacity: params.opacity,
    }"
  >
    <slot></slot>
  </div>
</template>

<script lang="ts" setup>
// 组合组件
const NAME = 'w-group'
import { nextTick, onBeforeUnmount, onMounted, onUpdated, ref } from 'vue'

import { setTransformAttribute } from '@/common/methods/handleTransform'
import { useWidgetStore } from '@/store';
import { storeToRefs } from 'pinia';
// import { useSetupMapGetters } from '@/common/hooks/mapGetters';

export type TParamsData = {
  left: number
  top: number
  width: number
  height: number
  opacity: number
  rotate: number
  uuid: string
  lock: boolean
  fontSize: number
}

type TProps = {
  params?: Partial<TParamsData>
  parent?: Partial<Pick<TParamsData, "top" | "left">>
}
const props = withDefaults(defineProps<TProps>(), {
  params: () => ({}),
  parent: () => ({})
})
;
const widgetStore = useWidgetStore()

const widget = ref<HTMLElement | null>(null)
const ratio = ref(0)
const temp = ref<Record<string, any>>({})
const compWidgetsRecord = ref<Record<string, any>>({})

const timer = ref<number | null>(null)
// const { dActiveElement, dWidgets } = useSetupMapGetters(['dActiveElement', 'dWidgets'])
const { dActiveElement, dWidgets } = storeToRefs(widgetStore)

// watch: {
//   params: {
//     async handler(nval) {
//       this.updateRecord(nval.tempScale)
//     },
//     immediate: true,
//     deep: true,
//   },
// },

onUpdated(() => {
  updateRecord()
})

onMounted(async () => {
  await nextTick()
  touchstart()
  updateRecord()
  document.addEventListener('mousedown', touchstart, false)
  document.addEventListener('mouseup', touchend, false)
  if (props.params?.rotate && widget.value) {
    // TODO: 设置原点是为了暂时解决组合旋转后缩放保存数据错位问题
    widget.value.style.transformOrigin = 'left top'
    widget.value.style.transform += `rotate(${props.params.rotate})`
  }
})

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', touchstart, false)
  document.removeEventListener('mouseup', touchend, false)
})
// ...mapActions(['updateWidgetData']),

function updateRecord(tempScale ?: number) {
  if (dActiveElement.value?.uuid === props.params.uuid) {
    // clearTimeout(this.timer)
    let record = dActiveElement.value?.record
    if (!record) return
    if (record.width <= 0) {
      touchend()
    }
    // if (this.tempRecord && this.tempRecord.width && this.tempRecord.width != record.width) {
    //   return
    // }
    ratio.value = tempScale || (props.params.width || 0) / record?.width

    if (ratio.value != 1) {
      if (record?.width != 0) {
        for (let i = dWidgets.value.length - 1; i >= 0; --i) {
          if (dWidgets.value[i].parent === props.params.uuid) {
            temp.value[dWidgets.value[i].uuid] = { width: dWidgets.value[i].width * ratio.value, height: dWidgets.value[i].height * ratio.value, raw: dWidgets.value[i] }
          }
        }
      }
      // TODO DOM Change
      // this.dActiveElement.scale = this.ratio
      if (widget.value) {
        // 缩放原点在左上角，旋转原点在中心
        widget.value.style.transformOrigin = 'left top' // 设置scale的原点
        setTransformAttribute(widget.value, 'scale', ratio.value)
      }
      // this.timer = setTimeout(() => {
      //   this.touchend()
      // }, 300)
    }
  }
}

function touchstart() {
  if (dActiveElement.value?.uuid !== props.params.uuid) {
    return
  }
  const tempRecord = {
    width: props.params.width,
    height: props.params.height,
  }
  for (let i = dWidgets.value.length - 1; i >= 0; --i) {
    if (dWidgets.value[i].parent === props.params.uuid) {
      const el = document.getElementById(dWidgets.value[i].uuid)
      if (el) {
        compWidgetsRecord.value[dWidgets.value[i].uuid] = {
          left: Number(el.style.left.replace('px', '')),
          top: Number(el.style.top.replace('px', '')),
          fontSize: Number(el.style.fontSize?.replace('px', '')),
        }
      }
    }
  }
}

function touchend() {
  if (dActiveElement.value?.uuid !== props.params.uuid) {
    return
  }
  // const opacity = this.$refs.widget.style.opacity
  // this.$refs.widget.style.opacity = 1
  setTimeout(() => {
    if (!temp.value || !widget.value) {
      return
    }
    widget.value.style.opacity = `${0}`
    setTransformAttribute(widget.value, 'scale', 1)
    setTimeout(() => {
      if (!widget.value) return
      widget.value.style.opacity = `${props.params.opacity}`
      // widget.value.style.transformOrigin = 'center' // 设置scale的原点
    }, 100)

    // const opacity = this.$refs.widget.style.opacity
    // setTransformAttribute(this.$refs.widget, 'scale', 1)
    for (const key in temp.value) {
      if (Object.hasOwnProperty.call(temp.value, key)) {
        keyChange(key, 'width', temp.value[key].width)
        keyChange(key, 'height', temp.value[key].height)
        // 重新拿前面设定好的，实时DOM修改过了
        keySetValue(key, 'left', compWidgetsRecord.value[key]?.left * ratio.value)
        keySetValue(key, 'top', compWidgetsRecord.value[key]?.top * ratio.value)
        // this.keySetValue(key, 'left', Number(document.getElementById(key).style.left.replace('px', '')) * this.ratio)
        // this.keySetValue(key, 'top', Number(document.getElementById(key).style.top.replace('px', '')) * this.ratio)
        if (temp.value[key].raw.type === 'w-text') {
          keyChange(key, 'fontSize', compWidgetsRecord.value[key]?.fontSize * ratio.value)
          // this.keyChange(key, 'fontSize', this.temp[key].raw.fontSize * this.ratio)
          // this.keyChange(key, 'letterSpacing', this.temp[key].raw.letterSpacing * this.ratio)
        }
      }
    }
    // this.$refs.widget.style.opacity = opacity
    temp.value = {}
    if (!dActiveElement.value) return
    if (dActiveElement.value.uuid === props.params.uuid) {
      let record = dActiveElement.value?.record
      if (!record) return
      record.width = widget.value?.offsetWidth
      record.height = widget.value?.offsetHeight
      dActiveElement.value.width = widget.value?.offsetWidth
      dActiveElement.value.height = widget.value?.offsetHeight
    }
  }, 10)
}
function keyChange(uuid: string, key: keyof TParamsData, value: number) {
  widgetStore.updateWidgetData({
    uuid,
    key,
    value
  })
  // store.dispatch('updateWidgetData', {
  //   uuid,
  //   key,
  //   value,
  //   pushHistory: false,
  // })
}

function keySetValue(uuid: string, key: keyof TParamsData, value: number) {
  setTimeout(() => {
    const widget = dWidgets.value.find((item) => item.uuid === uuid)
    if (!widget) return
    (widget[key] as Number) = value + Number(props.params[key] || '')
  }, 10)
}

// defineExpose({
//   setting
// })

</script>

<style lang="less" scoped>
.w-group {
  // cursor: pointer;
  outline: none;
}
</style>
